const sections={
S01:{title:'Identificación general',question:'¿Qué proyecto quieres construir y dónde se desarrollará?',meaning:'Ubica el proyecto: nombre, territorio, entidad, responsables y duración preliminar.',fields:[['nombre_del_proyecto','Nombre del proyecto',1],['entidad_u_organizacion','Entidad u organización'],['pais','País'],['departamento','Departamento'],['municipio','Municipio'],['institucion_o_sede','Institución o sede'],['responsable','Responsable'],['sector_o_campo_cultural','Sector o campo cultural'],['duracion_preliminar','Duración preliminar']]},
S02:{title:'Contexto territorial, cultural y social',question:'¿Qué características del territorio y de la comunidad ayudan a comprender el proyecto?',meaning:'Describe el territorio y el proceso cultural antes de explicar el problema.',fields:[['territorio_o_lugar_de_intervencion','Territorio o lugar de intervención',1],['caracteristicas_culturales','Características culturales'],['principales_dinamicas_sociales','Principales dinámicas sociales'],['antecedentes','Antecedentes']]},
S03:{title:'Población',question:'¿Quiénes participan o son atendidos por el proyecto?',meaning:'Diferencia población atendida, participantes y otros grupos pertinentes sin inventar cifras.',fields:[['poblacion_afectada','Población atendida',1],['poblacion_participante','Población participante'],['caracterizacion','Caracterización'],['cantidad_estimada','Cantidad estimada']]},
S04:{title:'Evidencia',question:'¿Qué datos, hechos o fuentes respaldan la necesidad identificada?',meaning:'Separa evidencia disponible, origen de la información y vacíos por verificar.',fields:[['evidencia_disponible','Evidencia disponible',1],['fuentes','Fuentes'],['datos_por_verificar','Datos por verificar'],['observaciones','Observaciones']]},
S05:{title:'Situaciones problemáticas',question:'¿Qué situaciones observables expresan el problema en el territorio o población?',meaning:'Registra situaciones concretas y diferenciadas antes de ordenar sus relaciones.',fields:[['situaciones_observables','Situaciones observables',1],['descripcion','Descripción'],['evidencia_asociada','Evidencia asociada'],['prioridad_preliminar','Prioridad preliminar']]},
S06:{title:'Matriz Vester',question:'¿Qué situaciones influyen directamente sobre otras y con qué intensidad?',meaning:'Vester organiza juicios de influencia. La valoración 0–3 corresponde a decisión humana y requiere justificación.',fields:[['variables_vester','Variables Vester',1],['relaciones_causales','Relaciones causales'],['valoracion_0_3','Valoración 0–3'],['justificacion','Justificación']]},
S07:{title:'Árbol de problemas',question:'¿Cuáles son las causas, el problema central y sus efectos?',meaning:'Organiza causas, problema y efectos manteniendo la lógica causal identificada y la revisión humana.',fields:[['causas_indirectas','Causas indirectas',1],['causas_directas','Causas directas'],['problema_central','Problema central'],['efectos_directos','Efectos directos'],['efectos_indirectos','Efectos indirectos']]},
S08:{title:'Problema central',question:'¿Cómo expresarías el problema principal de manera concreta y verificable?',meaning:'Describe una condición negativa existente sin anticipar la solución.',fields:[['enunciado','Enunciado del problema',1],['poblacion_afectada','Población atendida'],['evidencia_soporte','Evidencia soporte'],['alcance','Alcance']]}
};

const SUPABASE_URL='https://rmaevwlxcuqimxdzxdmq.supabase.co';
const SUPABASE_KEY='sb_publishable_YYXIMlsNUfi5RhZfhevMJw_6DovU9RK';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const order=Object.keys(sections);
let active=localStorage.getItem('fc_active')||'S01';
const storeKey='formulador-cultural-prototipo-v1';
const draft=JSON.parse(localStorage.getItem(storeKey)||'{}');
let dirty=false,session=null,cloudProject=null,loginCooldownTimer=null;
const q=s=>document.querySelector(s);

function guide(label){return [`¿Qué información concreta corresponde a «${label}»?`,`¿Qué datos están confirmados?`,`¿Qué falta por verificar?`]}
function shortTitle(t){return t.replace('Identificación general','Identificación').replace('Contexto territorial, cultural y social','Contexto').replace('Situaciones problemáticas','Situaciones').replace('Matriz Vester','Vester').replace('Árbol de problemas','Árbol').replace('Problema central','Problema')}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function collect(){draft[active]=draft[active]||{};document.querySelectorAll('[data-field]').forEach(el=>draft[active][el.dataset.field]=el.value)}
function setSaved(ok,cloud=false){const dot=q('#savedDot');if(dot){dot.classList.toggle('ok',ok&&!cloud);dot.classList.toggle('cloud',ok&&cloud)}}
function setStatus(text,cloud=false){q('#status').innerHTML=`<span class="saved-dot ${cloud?'cloud':'ok'}" id="savedDot"></span>${text}`}
function saveLocal(){collect();localStorage.setItem(storeKey,JSON.stringify(draft));dirty=false;setSaved(true,false);setStatus(`Borrador de ${active} guardado en este navegador.`)}
function authValues(){return {email:q('#email')?.value.trim()||'',password:q('#password')?.value||''}}
function validateCredentials(){const {email,password}=authValues();if(!email){q('#authHelp').textContent='Escribe un correo válido.';return null}if(password.length<8){q('#authHelp').textContent='La contraseña debe tener al menos 8 caracteres.';return null}return {email,password}}
function startLoginCooldown(seconds=60){const btn=q('#loginBtn');if(loginCooldownTimer)clearInterval(loginCooldownTimer);let remaining=seconds;btn.disabled=true;btn.textContent=`Espera ${remaining} s`;loginCooldownTimer=setInterval(()=>{remaining-=1;if(remaining<=0){clearInterval(loginCooldownTimer);loginCooldownTimer=null;btn.disabled=false;btn.textContent='Enviar enlace de acceso';return}btn.textContent=`Espera ${remaining} s`},1000)}

async function ensureProject(){if(!session||!sb)return null;if(cloudProject)return cloudProject;const {data,error}=await sb.from('projects').select('*').order('updated_at',{ascending:false}).limit(1);if(error)throw error;if(data?.length){cloudProject=data[0];return cloudProject}const title=draft.S01?.nombre_del_proyecto?.trim()||'Proyecto cultural';const created=await sb.from('projects').insert({title}).select().single();if(created.error)throw created.error;cloudProject=created.data;return cloudProject}
async function syncSection(code=active){if(!session||!sb)return false;collect();const project=await ensureProject();const payload={project_id:project.id,code,data:draft[code]||{},updated_at:new Date().toISOString()};const {error}=await sb.from('sections').upsert(payload,{onConflict:'project_id,code'});if(error)throw error;const title=draft.S01?.nombre_del_proyecto?.trim();if(title&&title!==project.title){await sb.from('projects').update({title,updated_at:new Date().toISOString()}).eq('id',project.id);project.title=title}return true}
async function save(){saveLocal();if(!session){setStatus(`Borrador de ${active} guardado localmente. Inicia sesión para sincronizar.`);return}try{await syncSection(active);setStatus(`${active} guardada y sincronizada en la nube.`,true)}catch(e){console.error(e);setStatus(`Guardado local correcto. La sincronización falló: ${e.message||'error desconocido'}`)}}
async function loadCloud(){if(!session||!sb)return;try{const project=await ensureProject();const {data,error}=await sb.from('sections').select('code,data').eq('project_id',project.id);if(error)throw error;for(const row of data||[])draft[row.code]={...(draft[row.code]||{}),...(row.data||{})};localStorage.setItem(storeKey,JSON.stringify(draft));render();setStatus(`Proyecto «${project.title}» cargado desde la nube.`,true)}catch(e){console.error(e);setStatus(`No fue posible cargar la nube: ${e.message||'error desconocido'}`)}}

function renderAuth(){const out=q('#authSignedOut'),inside=q('#authSignedIn');if(session){out.classList.add('hidden');inside.classList.remove('hidden');q('#userLabel').textContent=session.user.email||'Sesión activa';q('#authHelp').textContent='Sesión activa. El proyecto puede sincronizarse entre dispositivos.'}else{inside.classList.add('hidden');out.classList.remove('hidden');if(!/límite|contraseña|correo|cuenta|credenciales/i.test(q('#authHelp').textContent))q('#authHelp').textContent='Puedes entrar con correo y contraseña. El enlace por correo queda como alternativa.'}}

async function passwordLogin(){const creds=validateCredentials();if(!creds)return;q('#passwordLoginBtn').disabled=true;q('#authHelp').textContent='Iniciando sesión…';const {error}=await sb.auth.signInWithPassword(creds);q('#passwordLoginBtn').disabled=false;if(error){q('#authHelp').textContent=`No fue posible iniciar sesión: ${error.message}`;return}q('#authHelp').textContent='Sesión iniciada correctamente.'}
async function signupWithPassword(){const creds=validateCredentials();if(!creds)return;q('#signupBtn').disabled=true;q('#authHelp').textContent='Creando cuenta…';const redirectTo=location.origin+location.pathname;const {data,error}=await sb.auth.signUp({...creds,options:{emailRedirectTo:redirectTo}});q('#signupBtn').disabled=false;if(error){q('#authHelp').textContent=`No fue posible crear la cuenta: ${error.message}`;return}if(data.session){q('#authHelp').textContent='Cuenta creada y sesión iniciada.'}else{q('#authHelp').textContent='Cuenta creada. Supabase requiere confirmar el correo antes del primer ingreso.'}}
async function setPassword(){const next=prompt('Escribe una nueva contraseña de al menos 8 caracteres:');if(next===null)return;if(next.length<8){q('#authHelp').textContent='La contraseña debe tener al menos 8 caracteres.';return}const {error}=await sb.auth.updateUser({password:next});q('#authHelp').textContent=error?`No fue posible actualizar la contraseña: ${error.message}`:'Contraseña actualizada. En adelante puedes entrar sin solicitar un enlace por correo.'}
async function sendMagicLink(){const email=q('#email').value.trim();if(!email){q('#authHelp').textContent='Escribe un correo válido.';return}q('#loginBtn').disabled=true;q('#authHelp').textContent='Enviando enlace de acceso…';const redirectTo=location.origin+location.pathname;const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});if(error){const rateLimited=/rate limit|too many/i.test(error.message||'');if(rateLimited){q('#authHelp').textContent='Se alcanzó temporalmente el límite de correos. Usa contraseña si ya la definiste o espera antes de solicitar otro enlace.';startLoginCooldown(60)}else{q('#loginBtn').disabled=false;q('#authHelp').textContent=`No se pudo enviar: ${error.message}`}return}q('#authHelp').textContent='Enlace enviado. Revisa tu correo y evita solicitar otro mientras llega este mensaje.';startLoginCooldown(60)}

async function initAuth(){if(!sb){q('#authHelp').textContent='Conexión de nube no disponible.';return}const {data}=await sb.auth.getSession();session=data.session;renderAuth();if(session)await loadCloud();sb.auth.onAuthStateChange(async(_event,newSession)=>{session=newSession;cloudProject=null;renderAuth();if(session)await loadCloud()})}
function render(){const s=sections[active],idx=order.indexOf(active);localStorage.setItem('fc_active',active);q('#counter').textContent=`${active} · ${idx+1} de ${order.length}`;q('#title').textContent=s.title;q('#question').textContent=s.question;q('#meaning').textContent=s.meaning;q('#progressBar').style.width=`${((idx+1)/order.length)*100}%`;q('#nav').innerHTML=order.map(k=>`<button data-k="${k}" class="${k===active?'active':''}">${k} · ${shortTitle(sections[k].title)}</button>`).join('');q('#nav .active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{collect();active=b.dataset.k;render();q('#panel').scrollIntoView({behavior:'smooth',block:'start'})});const d=draft[active]||{};q('#fields').innerHTML=s.fields.map(([id,label,req])=>`<div class="field"><label for="${id}">${label} ${req?'<span class="required">· requerido</span>':''}</label><div class="help">Registre información pertinente y mantenga explícitos los vacíos.</div><details class="guide"><summary>Preguntas orientadoras</summary><ul class="questions">${guide(label).map(x=>`<li>${x}</li>`).join('')}</ul></details><textarea id="${id}" data-field="${id}" placeholder="Escriba aquí o use [POR VERIFICAR] cuando corresponda.">${esc(d[id]||'')}</textarea></div>`).join('');document.querySelectorAll('[data-field]').forEach(el=>{el.addEventListener('input',()=>{dirty=true;setSaved(false)});el.addEventListener('blur',()=>{if(dirty)saveLocal()})});['#prev','#mPrev'].forEach(sel=>q(sel).disabled=idx===0);['#next','#mNext'].forEach(sel=>q(sel).disabled=idx===order.length-1);setSaved(true,false)}
function move(delta){collect();const idx=Math.max(0,Math.min(order.length-1,order.indexOf(active)+delta));active=order[idx];render();q('#panel').scrollIntoView({behavior:'smooth',block:'start'})}

q('#save').onclick=save;q('#mSave').onclick=save;q('#next').onclick=()=>move(1);q('#mNext').onclick=()=>move(1);q('#prev').onclick=()=>move(-1);q('#mPrev').onclick=()=>move(-1);q('#clear').onclick=()=>{if(confirm(`¿Limpiar los campos de ${active}?`)){draft[active]={};localStorage.setItem(storeKey,JSON.stringify(draft));render()}};q('#loginBtn').onclick=sendMagicLink;q('#passwordLoginBtn').onclick=passwordLogin;q('#signupBtn').onclick=signupWithPassword;q('#setPasswordBtn').onclick=setPassword;q('#logoutBtn').onclick=async()=>{await sb.auth.signOut();session=null;cloudProject=null;renderAuth();setStatus('Sesión cerrada. El borrador local permanece en este navegador.')};q('#syncBtn').onclick=async()=>{try{saveLocal();for(const code of order){if(draft[code])await syncSection(code)}setStatus('Proyecto completo sincronizado en la nube.',true)}catch(e){setStatus(`Sincronización incompleta: ${e.message||'error desconocido'}`)}};window.addEventListener('beforeunload',()=>{if(dirty)saveLocal()});render();initAuth();