const sections={
S01:{title:'Identificación general',question:'¿Qué proyecto quieres construir y dónde se desarrollará?',meaning:'Ubica el proyecto: nombre, territorio, entidad, responsables y duración preliminar.',fields:[['nombre_del_proyecto','Nombre del proyecto',1],['entidad_u_organizacion','Entidad u organización'],['pais','País'],['departamento','Departamento'],['municipio','Municipio'],['institucion_o_sede','Institución o sede'],['responsable','Responsable'],['sector_o_campo_cultural','Sector o campo cultural'],['duracion_preliminar','Duración preliminar']]},
S02:{title:'Contexto territorial, cultural y social',question:'¿Qué características del territorio y de la comunidad ayudan a comprender el proyecto?',meaning:'Describe el territorio y el proceso cultural antes de explicar el problema.',fields:[['territorio_o_lugar_de_intervencion','Territorio o lugar de intervención',1],['caracteristicas_culturales','Características culturales'],['principales_dinamicas_sociales','Principales dinámicas sociales'],['antecedentes','Antecedentes']]},
S03:{title:'Población',question:'¿Quiénes participan o son afectados por la situación que aborda el proyecto?',meaning:'Diferencia población afectada, participantes y otros grupos pertinentes sin inventar cifras.',fields:[['poblacion_afectada','Población afectada',1],['poblacion_participante','Población participante'],['caracterizacion','Caracterización'],['cantidad_estimada','Cantidad estimada']]},
S04:{title:'Evidencia',question:'¿Qué datos, hechos o fuentes respaldan la necesidad identificada?',meaning:'Separa evidencia disponible, origen de la información y vacíos por verificar.',fields:[['evidencia_disponible','Evidencia disponible',1],['fuentes','Fuentes'],['datos_por_verificar','Datos por verificar'],['observaciones','Observaciones']]},
S05:{title:'Situaciones problemáticas',question:'¿Qué situaciones observables expresan el problema en el territorio o población?',meaning:'Registra situaciones concretas y diferenciadas antes de ordenar sus relaciones.',fields:[['situaciones_observables','Situaciones observables',1],['descripcion','Descripción'],['evidencia_asociada','Evidencia asociada'],['prioridad_preliminar','Prioridad preliminar']]},
S06:{title:'Matriz Vester',question:'¿Qué situaciones influyen directamente sobre otras y con qué intensidad?',meaning:'Vester organiza juicios de influencia. La valoración 0–3 corresponde a decisión humana y requiere justificación.',fields:[['variables_vester','Variables Vester',1],['relaciones_causales','Relaciones causales'],['valoracion_0_3','Valoración 0–3'],['justificacion','Justificación']]},
S07:{title:'Árbol de problemas',question:'¿Cuáles son las causas, el problema central y sus efectos?',meaning:'Organiza causas, problema y efectos manteniendo la lógica causal identificada y la revisión humana.',fields:[['causas_indirectas','Causas indirectas',1],['causas_directas','Causas directas'],['problema_central','Problema central'],['efectos_directos','Efectos directos'],['efectos_indirectos','Efectos indirectos']]},
S08:{title:'Problema central',question:'¿Cómo expresarías el problema principal de manera concreta y verificable?',meaning:'Describe una condición negativa existente sin anticipar la solución.',fields:[['enunciado','Enunciado del problema',1],['poblacion_afectada','Población afectada'],['evidencia_soporte','Evidencia soporte'],['alcance','Alcance']]}
};
const order=Object.keys(sections);let active=localStorage.getItem('fc_active')||'S01';const storeKey='formulador-cultural-prototipo-v1';const draft=JSON.parse(localStorage.getItem(storeKey)||'{}');let dirty=false;const q=s=>document.querySelector(s);
function guide(label){return [`¿Qué información concreta corresponde a «${label}»?`,`¿Qué datos están confirmados?`,`¿Qué falta por verificar?`]}
function shortTitle(t){return t.replace('Identificación general','Identificación').replace('Contexto territorial, cultural y social','Contexto').replace('Situaciones problemáticas','Situaciones').replace('Matriz Vester','Vester').replace('Árbol de problemas','Árbol').replace('Problema central','Problema')}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function collect(){draft[active]=draft[active]||{};document.querySelectorAll('[data-field]').forEach(el=>draft[active][el.dataset.field]=el.value)}
function setSaved(ok){const dot=q('#savedDot');if(dot)dot.classList.toggle('ok',ok)}
function save(){collect();localStorage.setItem(storeKey,JSON.stringify(draft));dirty=false;setSaved(true);q('#status').innerHTML=`<span class="saved-dot ok" id="savedDot"></span>Borrador de ${active} guardado en este navegador.`}
function render(){const s=sections[active],idx=order.indexOf(active);localStorage.setItem('fc_active',active);q('#counter').textContent=`${active} · ${idx+1} de ${order.length}`;q('#title').textContent=s.title;q('#question').textContent=s.question;q('#meaning').textContent=s.meaning;q('#progressBar').style.width=`${((idx+1)/order.length)*100}%`;
q('#nav').innerHTML=order.map(k=>`<button data-k="${k}" class="${k===active?'active':''}">${k} · ${shortTitle(sections[k].title)}</button>`).join('');q('#nav .active')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{collect();active=b.dataset.k;render();q('#panel').scrollIntoView({behavior:'smooth',block:'start'})});
const d=draft[active]||{};q('#fields').innerHTML=s.fields.map(([id,label,req])=>`<div class="field"><label for="${id}">${label} ${req?'<span class="required">· requerido</span>':''}</label><div class="help">Registre información pertinente y mantenga explícitos los vacíos.</div><details class="guide"><summary>Preguntas orientadoras</summary><ul class="questions">${guide(label).map(x=>`<li>${x}</li>`).join('')}</ul></details><textarea id="${id}" data-field="${id}" placeholder="Escriba aquí o use [POR VERIFICAR] cuando corresponda.">${esc(d[id]||'')}</textarea></div>`).join('');
document.querySelectorAll('[data-field]').forEach(el=>{el.addEventListener('input',()=>{dirty=true;setSaved(false)});el.addEventListener('blur',()=>{if(dirty)save()})});['#prev','#mPrev'].forEach(sel=>q(sel).disabled=idx===0);['#next','#mNext'].forEach(sel=>q(sel).disabled=idx===order.length-1);setSaved(true)}
function move(delta){collect();const idx=Math.max(0,Math.min(order.length-1,order.indexOf(active)+delta));active=order[idx];render();q('#panel').scrollIntoView({behavior:'smooth',block:'start'})}
q('#save').onclick=save;q('#mSave').onclick=save;q('#next').onclick=()=>move(1);q('#mNext').onclick=()=>move(1);q('#prev').onclick=()=>move(-1);q('#mPrev').onclick=()=>move(-1);q('#clear').onclick=()=>{if(confirm(`¿Limpiar los campos de ${active}?`)){draft[active]={};localStorage.setItem(storeKey,JSON.stringify(draft));render()}};window.addEventListener('beforeunload',()=>{if(dirty)save()});render();