(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const KEY='formulador-cultural-causal-validation-v1';
const VESTER_KEY='formulador-cultural-vester-v1';
let state={sourceSignature:'',variables:[],pairs:[],updatedAt:null};

function vester(){try{return draft?.S06?.vester_state||JSON.parse(localStorage.getItem(VESTER_KEY)||'{}')}catch{return {}}}
function relationKey(a,b){return `${a}>${b}`}
function complete(){const s=vester(),ps=s.selected||[];if(ps.length<2)return false;for(let i=0;i<ps.length;i++)for(let j=0;j<ps.length;j++)if(i!==j&&!Number.isInteger(s.relations?.[relationKey(ps[i].id,ps[j].id)]?.score))return false;return true}
function signature(){const s=vester(),ps=s.selected||[],rel=s.relations||{};return ps.map(p=>`${p.id}:${p.text}`).join('|')+'#'+Object.keys(rel).sort().map(k=>`${k}:${rel[k]?.score??''}`).join('|')}
function totals(){const s=vester(),ps=s.selected||[],rel=s.relations||{},m=new Map(ps.map(p=>[p.id,{id:p.id,text:p.text,influence:0,dependence:0}]));Object.entries(rel).forEach(([k,r])=>{if(!Number.isInteger(r?.score))return;const [a,b]=k.split('>');if(m.has(a))m.get(a).influence+=r.score;if(m.has(b))m.get(b).dependence+=r.score});const rows=[...m.values()],mi=rows.length?rows.reduce((a,b)=>a+b.influence,0)/rows.length:0,md=rows.length?rows.reduce((a,b)=>a+b.dependence,0)/rows.length:0;rows.forEach(r=>r.quadrant=r.influence>=mi?(r.dependence>=md?'Crítico':'Activo'):(r.dependence>=md?'Pasivo':'Indiferente'));return rows}
function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{};const cloud=typeof draft!=='undefined'?draft?.S06?.causal_validation:null;if(cloud){const lt=Date.parse(state.updatedAt||0)||0,ct=Date.parse(cloud.updatedAt||0)||0;if(!state.variables.length||ct>=lt)state={...state,...cloud}}}
function save({syncCloud=false}={}){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));if(typeof draft!=='undefined'){draft.S06=draft.S06||{};draft.S06.causal_validation=JSON.parse(JSON.stringify(state));localStorage.setItem(storeKey,JSON.stringify(draft));if(typeof markLocalUpdate==='function')markLocalUpdate('S06',state.updatedAt)}if(syncCloud&&typeof session!=='undefined'&&session){const fn=window.fcQueueSectionSync||syncSection;if(typeof fn==='function')fn('S06').catch(()=>{})}}
function build(force=false){const sig=signature();if(!force&&state.sourceSignature===sig&&state.variables.length)return;const s=vester(),oldV=new Map((state.variables||[]).map(x=>[x.id,x])),oldP=new Map((state.pairs||[]).map(x=>[x.key,x])),ts=new Map(totals().map(x=>[x.id,x]));state.variables=(s.selected||[]).map(p=>{const old=oldV.get(p.id);return old&&old.sourceText===p.text?old:{id:p.id,sourceText:p.text,text:p.text,status:'pending',role:'unclassified',note:'',quadrant:ts.get(p.id)?.quadrant||'',influence:ts.get(p.id)?.influence||0,dependence:ts.get(p.id)?.dependence||0}});const ps=s.selected||[];state.pairs=[];for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++){const a=ps[i],b=ps[j],key=[a.id,b.id].sort().join('|'),ab=s.relations?.[relationKey(a.id,b.id)]?.score,ba=s.relations?.[relationKey(b.id,a.id)]?.score,old=oldP.get(key);state.pairs.push(old?{...old,aId:a.id,bId:b.id,aText:a.text,bText:b.text,ab,ba}:{key,aId:a.id,bId:b.id,aText:a.text,bText:b.text,ab,ba,decision:'pending',note:''})}state.sourceSignature=sig;save()}
function suggestedDirection(p){if(!Number.isInteger(p.ab)||!Number.isInteger(p.ba))return 'Completa primero ambas direcciones en Vester.';const d=p.ab-p.ba;if(d>=2&&p.ab>=2)return `La asimetría orienta a revisar ${p.aText} → ${p.bText}.` ;if(d<=-2&&p.ba>=2)return `La asimetría orienta a revisar ${p.bText} → ${p.aText}.`;if(p.ab===0&&p.ba===0)return 'Vester no registra influencia directa en ninguna dirección.';if(Math.abs(d)<=1)return 'Los valores son cercanos; Vester por sí solo no ofrece una dirección causal clara.';return 'La diferencia es moderada; conviene revisar el mecanismo antes de aceptar una dirección.'}
function variableCard(v){return `<article class="cv-card"><header><div><strong>${esc(v.text)}</strong><small>Vester: ${esc(v.quadrant)} · influencia ${v.influence} · dependencia ${v.dependence}</small></div><span>${v.status==='confirmed'?'Confirmada':v.status==='excluded'?'Excluida':v.status==='reformulate'?'Reformular':'Pendiente'}</span></header><label>Formulación para el árbol<textarea data-cv-text="${v.id}">${esc(v.text)}</textarea></label><div class="cv-grid"><label>Decisión<select data-cv-status="${v.id}"><option value="pending" ${v.status==='pending'?'selected':''}>Pendiente</option><option value="confirmed" ${v.status==='confirmed'?'selected':''}>Confirmar variable</option><option value="reformulate" ${v.status==='reformulate'?'selected':''}>Reformular</option><option value="excluded" ${v.status==='excluded'?'selected':''}>Excluir</option></select></label><label>Rol preliminar<select data-cv-role="${v.id}"><option value="unclassified" ${v.role==='unclassified'?'selected':''}>Sin clasificar</option><option value="possible_cause" ${v.role==='possible_cause'?'selected':''}>Posible causa</option><option value="possible_central" ${v.role==='possible_central'?'selected':''}>Posible problema central</option><option value="possible_effect" ${v.role==='possible_effect'?'selected':''}>Posible efecto</option><option value="context" ${v.role==='context'?'selected':''}>Condición de contexto</option></select></label></div><label>Nota conceptual<textarea data-cv-note="${v.id}" placeholder="Explica por qué esta variable puede cumplir ese papel o qué falta verificar.">${esc(v.note||'')}</textarea></label></article>`}
function pairCard(p){const opts=[['pending','Pendiente'],['a_to_b','A antecede plausiblemente a B'],['b_to_a','B antecede plausiblemente a A'],['indirect','Relación indirecta / mediada'],['association','Asociación sin causalidad suficiente'],['none','Sin relación causal útil para el árbol']];return `<article class="cv-pair"><div class="cv-pair-head"><strong>A ↔ B</strong><span>A→B: <b>${p.ab}</b> · B→A: <b>${p.ba}</b></span></div><div class="cv-ab"><div><b>A</b> ${esc(p.aText)}</div><div><b>B</b> ${esc(p.bText)}</div></div><p class="cv-hint">${esc(suggestedDirection(p))}</p><label>Validación conceptual<select data-pair-decision="${p.key}">${opts.map(([v,l])=>`<option value="${v}" ${p.decision===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Justificación / mecanismo<textarea data-pair-note="${p.key}" placeholder="Describe el mecanismo causal plausible o por qué la relación debe descartarse.">${esc(p.note||'')}</textarea></label></article>`}
function counts(){return {confirmed:state.variables.filter(x=>x.status==='confirmed').length,excluded:state.variables.filter(x=>x.status==='excluded').length,pending:state.variables.filter(x=>x.status==='pending'||x.status==='reformulate').length,pairs:state.pairs.filter(x=>x.decision==='pending').length}}
function render(){const host=$('#causalValidationBody');if(!host)return;build(false);const c=counts();host.innerHTML=`<div class="cv-note"><strong>Qué valida esta etapa</strong><p>Vester identifica patrones de influencia y dependencia. Aquí decides si esas relaciones son causalmente plausibles para construir el árbol. La herramienta no convierte cuadrantes en causas o efectos de forma automática.</p></div><div class="cv-summary"><span>${c.confirmed} variables confirmadas</span><span>${c.pending} variables por revisar</span><span>${c.excluded} excluidas</span><span>${c.pairs} pares pendientes</span></div><div class="cv-tabs"><button type="button" id="cvVariables" class="primary">1. Variables</button><button type="button" id="cvPairs">2. Relaciones A↔B</button><button type="button" id="cvFinish">3. Preparar S07</button></div><div id="cvContent">${state.variables.map(variableCard).join('')}</div>`;bind()}
function bindFields(){document.querySelectorAll('[data-cv-text]').forEach(x=>x.onchange=()=>{const v=state.variables.find(v=>v.id===x.dataset.cvText);if(v){v.text=x.value.trim();v.status='reformulate';save()}});document.querySelectorAll('[data-cv-status]').forEach(x=>x.onchange=()=>{const v=state.variables.find(v=>v.id===x.dataset.cvStatus);if(v){v.status=x.value;save();render()}});document.querySelectorAll('[data-cv-role]').forEach(x=>x.onchange=()=>{const v=state.variables.find(v=>v.id===x.dataset.cvRole);if(v){v.role=x.value;save()}});document.querySelectorAll('[data-cv-note]').forEach(x=>x.oninput=()=>{const v=state.variables.find(v=>v.id===x.dataset.cvNote);if(v){v.note=x.value.trim();save({syncCloud:true})}});document.querySelectorAll('[data-pair-decision]').forEach(x=>x.onchange=()=>{const p=state.pairs.find(p=>p.key===x.dataset.pairDecision);if(p){p.decision=x.value;save()}});document.querySelectorAll('[data-pair-note]').forEach(x=>x.oninput=()=>{const p=state.pairs.find(p=>p.key===x.dataset.pairNote);if(p){p.note=x.value.trim();save({syncCloud:true})}})}
function bind(){bindFields();$('#cvVariables').onclick=()=>{$('#cvContent').innerHTML=state.variables.map(variableCard).join('');bindFields()};$('#cvPairs').onclick=()=>{$('#cvContent').innerHTML=state.pairs.map(pairCard).join('');bindFields()};$('#cvFinish').onclick=()=>{const admitted=state.variables.filter(x=>x.status==='confirmed');if(admitted.length<2){alert('Confirma al menos dos variables antes de preparar el árbol.');return}const pendingPairs=state.pairs.filter(x=>x.decision==='pending');if(pendingPairs.length){if(!confirm(`Quedan ${pendingPairs.length} relaciones pendientes. Puedes continuar, pero aparecerán como [POR VERIFICAR] en S07. ¿Continuar?`))return}save();if(typeof window.fcNavigate==='function')window.fcNavigate('S07');else document.querySelector('#nav button[data-k="S07"]')?.click()}}
function mount(){const counter=$('#counter'),fields=$('#fields');if(!counter||!fields||!counter.textContent.startsWith('S06'))return;if(!complete())return;load();build(false);let host=$('#causalValidation');if(host)return;host=document.createElement('section');host.id='causalValidation';host.className='cv-wrap';host.innerHTML='<span class="vester-mode">Validación causal</span><h3>Revisar Vester antes de construir el árbol</h3><p>Confirma qué variables y relaciones son conceptualmente utilizables para S07.</p><div id="causalValidationBody"></div>';fields.appendChild(host);render();}
window.fcGetCausalValidatedProblems=()=>{load();build(false);return state.variables.filter(x=>x.status==='confirmed'&&x.text.trim()).map(x=>({id:x.id,text:x.text,role:x.role,note:x.note,status:x.status}))};
window.fcGetCausalValidatedPairs=()=>{load();build(false);return state.pairs.filter(x=>x.decision!=='pending').map(x=>({...x}))};
window.fcCausalValidationReady=()=>{load();build(false);return state.variables.filter(x=>x.status==='confirmed').length>=2};
const style=document.createElement('style');style.textContent='.cv-wrap{margin-top:22px;border-top:2px solid var(--ink);padding-top:18px}.cv-note,.cv-card,.cv-pair{border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px;margin:10px 0}.cv-note p,.cv-hint{color:var(--muted);font-size:.88rem}.cv-summary,.cv-tabs{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.cv-summary span{border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:.78rem}.cv-tabs button,.cv-card select,.cv-pair select{border:1px solid #aeb8c2;background:#fff;border-radius:9px;padding:8px 10px;font:inherit}.cv-card header,.cv-pair-head{display:flex;justify-content:space-between;gap:10px}.cv-card header small{display:block;color:var(--muted);margin-top:3px}.cv-card label,.cv-pair label{display:grid;gap:5px;margin-top:9px;font-weight:700;font-size:.84rem}.cv-card textarea,.cv-pair textarea{width:100%;min-height:70px;border:1px solid #b8c2cc;border-radius:9px;padding:9px;font:inherit}.cv-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.cv-ab{display:grid;gap:6px;margin:10px 0}.cv-pair-head span{font-size:.82rem;color:var(--muted)}@media(max-width:720px){.cv-grid{grid-template-columns:1fr}.cv-tabs{display:grid}.cv-tabs button{width:100%}.cv-card header,.cv-pair-head{display:block}}';document.head.appendChild(style);
new MutationObserver(mount).observe(document.body,{subtree:true,childList:true});mount();
})();