(()=>{
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function arr(v){return Array.isArray(v)?v:[]}
function tree(){try{return draft?.S07?.tree_state||JSON.parse(localStorage.getItem('formulador-cultural-problem-tree-v1')||'{}')}catch{return {}}}
function objectives(){try{return draft?.S09?.objectives_state||JSON.parse(localStorage.getItem('formulador-cultural-objectives-v1')||'{}')}catch{return {}}}
function alternatives(){try{return window.fcGetAlternatives?.()||[]}catch{return []}}
function results(){try{return window.fcGetResults?.()||[]}catch{return []}}
function activities(){try{return window.fcGetActivities?.()||[]}catch{return []}}
function indicators(){try{return (window.fcGetIndicators?.()||[]).filter(x=>!x.stale&&(x.selected!==false||x.confirmed))}catch{return []}}
function schedule(){try{return window.fcGetSchedule?.()||[]}catch{return []}}
function budget(){try{return window.fcGetBudget?.()||[]}catch{return []}}
function budgetState(){try{return window.fcGetBudgetState?.()||{}}catch{return {}}}
function risks(){try{return window.fcGetRisks?.()||[]}catch{return []}}
function riskState(){try{return window.fcGetRiskState?.()||{}}catch{return {}}}
function evidence(){const d=draft?.S04||{};return [d.evidencia_disponible,d.fuentes].filter(x=>String(x||'').trim()).length}
function pendingValue(v){return !String(v||'').trim()||/\[POR (VERIFICAR|REVISAR|DEFINIR)\]/i.test(String(v||''))}
function currentValidationSnapshot(){
 const res=results().filter(x=>x.confirmed),acts=activities().filter(x=>x.confirmed),inds=indicators(),sch=schedule(),bud=budget(),rsk=risks();
 const indicatorFields=['formula','unidad','lineaBase','meta','medioVerificacion','periodicidad','responsable','plazo'];
 const indicatorPending=inds.filter(x=>x.selected!==false||x.confirmed).map(x=>({
  id:x.id||x.indicatorId,
  definitionPending:!x.confirmed||x.definitionStatus==='PENDIENTE'||pendingValue(x.indicator),
  technicalPending:x.confirmed&&indicatorFields.some(k=>pendingValue(x[k])),
  missingFields:x.confirmed?indicatorFields.filter(k=>pendingValue(x[k])):[],
  item:x
 }));
 const orphanResults=res.filter(r=>!acts.some(a=>a.resultId===r.id));
 const orphanActivities=acts.filter(a=>!a.resultId||!res.some(r=>r.id===a.resultId));
 const schedulePending=acts.filter(a=>!sch.some(s=>s.activityId===a.id&&s.confirmed));
 const budgetStateNow=budgetState(),activityStatus=budgetStateNow.activityStatus||{};
 const budgetPending=acts.filter(a=>!activityStatus[a.id]||activityStatus[a.id]==='pending');
 const highRiskPending=rsk.filter(x=>x.riskLevel==='Alto'&&(!x.confirmed||pendingValue(x.preventiveResponse)||pendingValue(x.contingencyResponse)||pendingValue(x.owner)));
 return {indicatorPending,orphanResults,orphanActivities,schedulePending,budgetPending,highRiskPending}
}

function checks(){const out=[];const tn=arr(tree().nodes),on=arr(objectives().items),alts=alternatives(),res=results(),acts=activities(),inds=indicators();const central=tn.find(x=>x.zone==='central');const directCauses=tn.filter(x=>x.zone==='direct_cause'),indirectCauses=tn.filter(x=>x.zone==='indirect_cause');const objCentral=on.find(x=>x.zone==='central'&&x.confirmed);const objSpecific=on.filter(x=>x.confirmed&&x.zone==='direct_cause');const selAlt=alts.find(x=>x.selected&&x.confirmed),sch=schedule(),bud=budget(),bs=budgetState(),rsk=risks(),rs=riskState();
const add=(dimension,label,ok,msg,status)=>out.push({dimension,label,status:status||((ok)?'COHERENTE':'REQUIERE AJUSTE'),message:msg});
add('Evidencia','Problema conectado con el análisis previo',!!central&&!!String(central.origin||'').trim(),central?'El problema central tiene una conexión con información registrada antes.':'Todavía falta definir el problema central.');
add('Evidencia','Existe información de respaldo',evidence()>0,evidence()>0?'Hay información registrada que ayuda a respaldar la formulación.':'Aún falta registrar evidencia o fuentes.',evidence()>0?'COHERENTE':'INSUFFICIENT_EVIDENCE');
add('Lógica del proyecto','Problema → objetivo general',!!central&&!!objCentral,objCentral?'El objetivo general está conectado con el problema central.':'Confirma un objetivo general que responda directamente al problema central.');
add('Lógica del proyecto','Causas directas → objetivos específicos',directCauses.length>0&&objSpecific.length===directCauses.length,directCauses.length?(objSpecific.length===directCauses.length?'Cada causa directa tiene un objetivo específico confirmado.':`Hay ${directCauses.length} causa(s) directa(s) y ${objSpecific.length} objetivo(s) específico(s) confirmado(s).`):'El árbol no contiene causas directas. Revisa S07 antes de formular objetivos específicos.');add('Lógica del proyecto','Causas indirectas → medios',true,indirectCauses.length?`${indirectCauses.length} causa(s) indirecta(s) se conservan como medios del árbol y no se cuentan como objetivos específicos.`:'No hay causas indirectas registradas.');
const resByObj=new Map();res.filter(x=>x.confirmed).forEach(x=>resByObj.set(x.objectiveId,(resByObj.get(x.objectiveId)||0)+1));const orphanObj=objSpecific.filter(x=>!resByObj.get(x.id));add('Lógica del proyecto','Objetivos → resultados',objSpecific.length>0&&orphanObj.length===0,orphanObj.length?`${orphanObj.length} objetivo(s) todavía no tienen un resultado o producto claro.`:'Cada objetivo específico tiene al menos un resultado definido.');
const resultIds=new Set(res.filter(x=>x.confirmed).map(x=>x.id));const orphanActs=acts.filter(x=>x.confirmed&&!x.resultId);const actsByResult=new Map();acts.filter(x=>x.confirmed&&x.resultId).forEach(x=>actsByResult.set(x.resultId,(actsByResult.get(x.resultId)||0)+1));const orphanRes=res.filter(x=>x.confirmed&&!actsByResult.get(x.id));if(!resultIds.size)add('Lógica del proyecto','Resultados → actividades',false,'Todavía no hay resultados confirmados para evaluar esta relación.','AÚN NO EVALUABLE');else add('Lógica del proyecto','Resultados → actividades',orphanActs.length===0&&orphanRes.length===0,orphanActs.length||orphanRes.length?`${orphanActs.length} actividad(es) sin resultado asociado y ${orphanRes.length} resultado(s) sin actividades.`:'Los resultados confirmados tienen actividades asociadas.');
const confirmedInd=inds.filter(x=>x.confirmed),indByAct=new Set(confirmedInd.filter(x=>(x.linkedType||'Actividad')==='Actividad').map(x=>x.linkedId||x.activityId)),indByResult=new Set(confirmedInd.filter(x=>x.linkedType==='Resultado').map(x=>x.linkedId||x.resultId)),indByObjective=new Set(confirmedInd.filter(x=>x.linkedType==='Objetivo').map(x=>x.linkedId||x.objectiveId));
const missingInd=acts.filter(x=>x.confirmed&&!indByAct.has(x.id));if(!acts.some(x=>x.confirmed))add('Cómo comprobar avances','Actividades → indicadores',false,'Todavía no hay actividades confirmadas para evaluar indicadores.','AÚN NO EVALUABLE');else add('Cómo comprobar avances','Actividades → indicadores',missingInd.length===0,missingInd.length?`${missingInd.length} actividad(es) confirmada(s) todavía no tienen indicador.`:'Las actividades confirmadas tienen una forma de seguimiento.');
const missingResultInd=res.filter(x=>x.confirmed&&!indByResult.has(x.id));if(!res.some(x=>x.confirmed))add('Cómo comprobar avances','Resultados → indicadores',false,'Todavía no hay resultados confirmados para evaluar indicadores.','AÚN NO EVALUABLE');else add('Cómo comprobar avances','Resultados → indicadores',missingResultInd.length===0,missingResultInd.length?`${missingResultInd.length} resultado(s) todavía no tienen indicador de resultado.`:'Los resultados confirmados tienen indicador.');
add('Cómo comprobar avances','Objetivo general → indicador',!!objCentral&&indByObjective.has(objCentral.id),objCentral?(indByObjective.has(objCentral.id)?'El objetivo general tiene un indicador asociado.':'Falta un indicador para el objetivo general.'):'Primero confirma el objetivo general.');
const current=currentValidationSnapshot(),undefinedInd=current.indicatorPending.filter(x=>x.definitionPending),incompleteInd=current.indicatorPending.filter(x=>x.technicalPending&&!x.definitionPending);
add('Cómo comprobar avances','Indicadores definidos',inds.length>0&&undefinedInd.length===0,undefinedInd.length?`${undefinedInd.length} indicador(es) todavía requieren una definición confirmada.`:'Todos los indicadores necesarios tienen una definición confirmada.');
if(!confirmedInd.length)add('Cómo comprobar avances','Fichas técnicas de indicadores',false,'Todavía no hay indicadores aprobados para evaluar fichas técnicas.','AÚN NO EVALUABLE');else add('Cómo comprobar avances','Fichas técnicas de indicadores',incompleteInd.length===0,incompleteInd.length?`${incompleteInd.length} indicador(es) están definidos, pero su ficha técnica todavía tiene datos por completar.`:'Las fichas técnicas de los indicadores definidos están completas.',incompleteInd.length?'COHERENTE CON DATOS PENDIENTES':'COHERENTE');
add('Lógica del proyecto','Alternativa elegida',!!selAlt,selAlt?'Ya existe una alternativa confirmada para orientar las actividades.':'Todavía falta confirmar cuál alternativa seguirá el proyecto.');
const confirmedActs=acts.filter(x=>x.confirmed),schMap=new Map(sch.map(x=>[x.activityId,x])),missingSchedule=confirmedActs.filter(a=>!schMap.get(a.id)?.confirmed);
if(!confirmedActs.length)add('Tiempo','Actividades → cronograma',false,'Todavía no hay actividades confirmadas para evaluar el cronograma.','AÚN NO EVALUABLE');else add('Tiempo','Actividades → cronograma',missingSchedule.length===0,missingSchedule.length?`${missingSchedule.length} actividad(es) todavía no tienen fecha, duración y responsable confirmados.`:'Todas las actividades confirmadas están ubicadas en el tiempo.');
const scheduleIssues=window.fcGetScheduleIssues?.()||[];add('Tiempo','Dependencias temporales',scheduleIssues.length===0,scheduleIssues.length?scheduleIssues.join(' · '):'No se detectan dependencias temporales contradictorias.');
const activityStatus=bs.activityStatus||{},unbudgeted=confirmedActs.filter(a=>!activityStatus[a.id]||activityStatus[a.id]==='pending');
if(!confirmedActs.length)add('Presupuesto','Actividades → recursos y costos',false,'Todavía no hay actividades confirmadas para evaluar recursos y costos.','AÚN NO EVALUABLE');else add('Presupuesto','Actividades → recursos y costos',unbudgeted.length===0,unbudgeted.length?`${unbudgeted.length} actividad(es) aún no indican cómo se cubrirán sus recursos.`:'Cada actividad confirmada indica su tratamiento financiero.');
const actIds=new Set(confirmedActs.map(x=>x.id)),orphanBudget=bud.filter(x=>!actIds.has(x.activityId));add('Presupuesto','Rubros vinculados a actividades',orphanBudget.length===0,orphanBudget.length?`${orphanBudget.length} rubro(s) no tienen una actividad vigente asociada.`:'Los rubros presupuestales están vinculados a actividades.');
const highUnanswered=rsk.filter(x=>x.riskLevel==='Alto'&&(!x.confirmed||/POR VERIFICAR/.test([x.preventiveResponse,x.contingencyResponse,x.owner].join(' '))));
add('Riesgos','Riesgos prioritarios con respuesta',highUnanswered.length===0,highUnanswered.length?`${highUnanswered.length} riesgo(s) alto(s) todavía no tienen respuesta y responsable confirmados.`:'Los riesgos altos identificados tienen respuesta y responsable.');
const targets=rs.targets||[],ass=rs.assessments||{},pendingRisks=targets.filter(t=>!ass[t.id]||ass[t.id]==='pending');add('Riesgos','Cobertura de revisión de riesgos',targets.length>0&&pendingRisks.length===0,pendingRisks.length?`${pendingRisks.length} elemento(s) todavía no han sido revisados frente a riesgos.`:'Las causas, resultados y actividades seleccionadas fueron revisadas frente a riesgos.');
return out}
function report(){const cs=checks(),evals=cs.filter(x=>x.status!=='AÚN NO EVALUABLE'),weight=s=>s==='COHERENTE'?1:s==='COHERENTE CON DATOS PENDIENTES'?0.5:0,total=evals.reduce((a,x)=>a+weight(x.status),0),score=evals.length?Math.round(total/evals.length*100):0;const dims={};for(const c of evals){dims[c.dimension]=dims[c.dimension]||{total:0,points:0};dims[c.dimension].total++;dims[c.dimension].points+=weight(c.status)}return {score,checks:cs,dimensions:Object.entries(dims).map(([name,v])=>({name,score:Math.round(v.points/v.total*100),...v}))}}
function traceRows(){const r=[];for(const n of arr(tree().nodes).filter(x=>x.zone!=='outside'))r.push({Tipo:'Problema',ID:n.id,Elemento:n.text,Deriva_de:n.origin||'S05',Conecta_con:n.parentId||'',Estado:n.reviewed?'COHERENTE':'REQUIERE AJUSTE'});for(const o of arr(objectives().items))r.push({Tipo:'Objetivo/medio/fin',ID:o.id,Elemento:o.text,Deriva_de:o.sourceText||'S07',Conecta_con:o.parentId||'',Estado:o.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of alternatives())r.push({Tipo:'Alternativa',ID:x.id,Elemento:x.text,Deriva_de:(x.sourceIds||[]).join(','),Conecta_con:'',Estado:x.confirmed?(x.selected?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'):'REQUIERE AJUSTE'});for(const x of results())r.push({Tipo:'Resultado',ID:x.id,Elemento:x.text,Deriva_de:x.objectiveId||'',Conecta_con:'',Estado:x.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of activities())r.push({Tipo:'Actividad',ID:x.id,Elemento:x.text,Deriva_de:x.resultId||x.objectiveId||'',Conecta_con:x.resultId||'',Estado:x.confirmed?(x.resultId?'COHERENTE':'INCONSISTENCIA LÓGICA'):'REQUIERE AJUSTE'});for(const x of schedule())r.push({Tipo:'Cronograma',ID:x.id,Elemento:x.activityText||x.activityId,Deriva_de:x.activityId||'',Conecta_con:(x.dependencyIds||[]).join(','),Estado:x.confirmed?'COHERENTE':'REQUIERE AJUSTE'});
for(const x of budget())r.push({Tipo:'Presupuesto',ID:x.id,Elemento:x.description||'[POR VERIFICAR]',Deriva_de:x.activityId||'',Conecta_con:x.activityId||'',Estado:x.confirmed?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'});
for(const x of risks())r.push({Tipo:'Riesgo',ID:x.id,Elemento:x.event||'[POR VERIFICAR]',Deriva_de:x.linkedObjectId||'',Conecta_con:x.targetId||'',Estado:x.confirmed?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'});
for(const x of indicators())r.push({Tipo:'Indicador',ID:x.id,Elemento:x.indicator,Deriva_de:x.linkedId||x.activityId||x.resultId||x.objectiveId||'',Conecta_con:(x.linkedType||'Actividad')+':'+(x.linkedId||x.activityId||x.resultId||x.objectiveId||''),Estado:!x.confirmed?'REQUIERE AJUSTE':(x.technicalStatus==='COMPLETA'||x.verificationStatus==='VERIFICADO'?'COHERENTE':'COHERENTE CON DATOS PENDIENTES')});return r}
function humanStatus(s){return {'COHERENTE':'Bien','COHERENTE CON DATOS PENDIENTES':'Bien, pero faltan datos','REQUIERE AJUSTE':'Revisar','INCONSISTENCIA LÓGICA':'Hay una ruptura','INSUFFICIENT_EVIDENCE':'Falta evidencia','AÚN NO EVALUABLE':'Todavía no aplica'}[s]||s}
function render(){
 const c=$('#counter')?.textContent||'';if(!/^S(0[5-9]|1[0-6])/.test(c)||c.startsWith('S16'))return;const fields=$('#fields');if(!fields||$('#coherencePanel'))return;const r=report(),needs=r.checks.filter(x=>!['COHERENTE'].includes(x.status)),n=needs.length;
 const panel=document.createElement('section');panel.id='coherencePanel';panel.className='coherence-panel coherence-compact';
 panel.innerHTML=`<details><summary><span><strong>Revisión del proyecto</strong><small>${n?`${n} aspecto(s) necesitan atención`:'Todo lo revisado está conectado'}</small></span><b>Ver ›</b></summary><div class="coh-help">${r.score>=80?'La estructura está bien conectada. Revisa únicamente los datos pendientes.':r.score>=50?'El proyecto avanza, pero hay relaciones que todavía conviene revisar.':'Hay conexiones importantes que todavía faltan.'}</div><div class="coh-list">${needs.slice(0,6).map(x=>`<article><b>${esc(humanStatus(x.status))}</b> · ${esc(x.label)}<p>${esc(x.message)}</p></article>`).join('')||'<p>No hay alertas en esta etapa.</p>'}</div><p class="coh-explain">El porcentaje técnico y el diagnóstico completo se muestran en la revisión final S16.</p></details>`;
 fields.appendChild(panel)
}
window.fcGetCoherenceReport=report;window.fcGetTraceabilityRows=traceRows;window.fcGetCurrentValidationSnapshot=currentValidationSnapshot;
const style=document.createElement('style');style.textContent='.coherence-compact{margin-top:16px;border:1px solid var(--line);border-radius:12px;background:#fff}.coherence-compact details{padding:0}.coherence-compact summary{list-style:none;cursor:pointer;display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px}.coherence-compact summary::-webkit-details-marker{display:none}.coherence-compact summary span{display:grid;gap:2px}.coherence-compact summary small{color:var(--muted);font-weight:400}.coherence-compact summary>b{font-weight:600;color:#52606d}.coherence-compact .coh-help,.coherence-compact .coh-list,.coherence-compact .coh-explain{margin:0 12px 12px}.coherence-compact .coh-help{background:#f7f9fb;border-radius:9px;padding:9px}.coherence-compact .coh-list article{border-top:1px solid var(--line);padding:8px 0}.coherence-compact .coh-list article p,.coherence-compact .coh-explain{margin:4px 0;color:var(--muted);font-size:.84rem}';document.head.appendChild(style);new MutationObserver(render).observe(document.body,{subtree:true,childList:true});render();
})();