(()=>{
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function arr(v){return Array.isArray(v)?v:[]}
function tree(){try{return draft?.S07?.tree_state||JSON.parse(localStorage.getItem('formulador-cultural-problem-tree-v1')||'{}')}catch{return {}}}
function objectives(){try{return draft?.S09?.objectives_state||JSON.parse(localStorage.getItem('formulador-cultural-objectives-v1')||'{}')}catch{return {}}}
function alternatives(){try{return window.fcGetAlternatives?.()||[]}catch{return []}}
function results(){try{return window.fcGetResults?.()||[]}catch{return []}}
function activities(){try{return window.fcGetActivities?.()||[]}catch{return []}}
function indicators(){try{return window.fcGetIndicators?.()||[]}catch{return []}}
function evidence(){const d=draft?.S04||{};return [d.evidencia_disponible,d.fuentes].filter(x=>String(x||'').trim()).length}
function checks(){const out=[];const tn=arr(tree().nodes),on=arr(objectives().items),alts=alternatives(),res=results(),acts=activities(),inds=indicators();const central=tn.find(x=>x.zone==='central');const causes=tn.filter(x=>/cause/.test(x.zone||''));const effects=tn.filter(x=>/effect/.test(x.zone||''));const objCentral=on.find(x=>x.zone==='central'&&x.confirmed);const objSpecific=on.filter(x=>x.confirmed&&(x.zone==='direct_cause'||x.zone==='indirect_cause'));const selAlt=alts.find(x=>x.selected&&x.confirmed);
const add=(dimension,label,ok,msg,status)=>out.push({dimension,label,status:status||((ok)?'COHERENTE':'REQUIERE AJUSTE'),message:msg});
add('Evidencial','Problema central con antecedente',!!central&&!!String(central.origin||'').trim(),central?'El problema central está conectado con una entrada previa del análisis.':'Falta definir el problema central.');
add('Evidencial','Evidencia disponible',evidence()>0,'La formulación tiene al menos una referencia/evidencia registrada.','COHERENTE CON DATOS PENDIENTES');
add('Vertical','Problema → objetivo general',!!central&&!!objCentral,objCentral?'Existe objetivo central confirmado derivado de S07.':'Falta confirmar el objetivo central derivado del problema.');
add('Vertical','Causas → objetivos específicos',causes.length>0&&objSpecific.length>0,`${objSpecific.length} objetivos/medios confirmados para ${causes.length} causas registradas.`);
const resByObj=new Map();res.filter(x=>x.confirmed).forEach(x=>resByObj.set(x.objectiveId,(resByObj.get(x.objectiveId)||0)+1));const orphanObj=objSpecific.filter(x=>!resByObj.get(x.id));add('Vertical','Objetivos → resultados',objSpecific.length>0&&orphanObj.length===0,orphanObj.length?`${orphanObj.length} objetivo(s) específico(s) aún no tienen resultado/producto confirmado.`:'Cada objetivo específico tiene al menos un resultado confirmado.');
const resultIds=new Set(res.filter(x=>x.confirmed).map(x=>x.id));const orphanActs=acts.filter(x=>x.confirmed&&!x.resultId);const actsByResult=new Map();acts.filter(x=>x.confirmed&&x.resultId).forEach(x=>actsByResult.set(x.resultId,(actsByResult.get(x.resultId)||0)+1));const orphanRes=res.filter(x=>x.confirmed&&!actsByResult.get(x.id));add('Vertical','Resultados → actividades',resultIds.size>0&&orphanActs.length===0&&orphanRes.length===0,`${orphanActs.length} actividad(es) huérfana(s); ${orphanRes.length} resultado(s) sin actividades.`);
const indByAct=new Set(inds.filter(x=>x.confirmed).map(x=>x.activityId));const missingInd=acts.filter(x=>x.confirmed&&!indByAct.has(x.id));add('Horizontal','Actividades → indicadores',acts.some(x=>x.confirmed)&&missingInd.length===0,missingInd.length?`${missingInd.length} actividad(es) confirmada(s) sin indicador confirmado.`:'Las actividades confirmadas tienen indicador.');
const incompleteInd=inds.filter(x=>x.confirmed).filter(x=>['meta','lineaBase','medioVerificacion','responsable','plazo'].some(k=>!String(x[k]||'').trim()||/\[POR VERIFICAR\]/i.test(String(x[k]||''))));add('Horizontal','Indicador completo',inds.some(x=>x.confirmed)&&incompleteInd.length===0,incompleteInd.length?`${incompleteInd.length} indicador(es) confirmado(s) conservan datos [POR VERIFICAR].`:'Los indicadores confirmados tienen meta, línea base, fuente, responsable y plazo.','COHERENTE CON DATOS PENDIENTES');
add('Vertical','Alternativa seleccionada',!!selAlt,selAlt?'Existe una alternativa confirmada y seleccionada.':'Falta una alternativa confirmada y seleccionada.');
[['Temporal','Cronograma'],['Financiera','Presupuesto'],['Financiera','Recursos'],['Riesgos','Riesgos']].forEach(([d,l])=>add(d,l,false,'Componente aún no construido; no se incluye en la puntuación.','AÚN NO EVALUABLE'));
return out}
function report(){const cs=checks(),evals=cs.filter(x=>x.status!=='AÚN NO EVALUABLE'),ok=evals.filter(x=>x.status==='COHERENTE'||x.status==='COHERENTE CON DATOS PENDIENTES').length,score=evals.length?Math.round(ok/evals.length*100):0;const dims={};for(const c of evals){dims[c.dimension]=dims[c.dimension]||{total:0,ok:0};dims[c.dimension].total++;if(c.status==='COHERENTE'||c.status==='COHERENTE CON DATOS PENDIENTES')dims[c.dimension].ok++}return {score,checks:cs,dimensions:Object.entries(dims).map(([name,v])=>({name,score:Math.round(v.ok/v.total*100),...v}))}}
function traceRows(){const r=[];for(const n of arr(tree().nodes).filter(x=>x.zone!=='outside'))r.push({Tipo:'Problema',ID:n.id,Elemento:n.text,Deriva_de:n.origin||'S05',Conecta_con:n.parentId||'',Estado:n.reviewed?'COHERENTE':'REQUIERE AJUSTE'});for(const o of arr(objectives().items))r.push({Tipo:'Objetivo/medio/fin',ID:o.id,Elemento:o.text,Deriva_de:o.sourceText||'S07',Conecta_con:o.parentId||'',Estado:o.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of alternatives())r.push({Tipo:'Alternativa',ID:x.id,Elemento:x.text,Deriva_de:(x.sourceIds||[]).join(','),Conecta_con:'',Estado:x.confirmed?(x.selected?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'):'REQUIERE AJUSTE'});for(const x of results())r.push({Tipo:'Resultado',ID:x.id,Elemento:x.text,Deriva_de:x.objectiveId||'',Conecta_con:'',Estado:x.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of activities())r.push({Tipo:'Actividad',ID:x.id,Elemento:x.text,Deriva_de:x.resultId||x.objectiveId||'',Conecta_con:x.resultId||'',Estado:x.confirmed?(x.resultId?'COHERENTE':'INCONSISTENCIA LÓGICA'):'REQUIERE AJUSTE'});for(const x of indicators())r.push({Tipo:'Indicador',ID:x.id,Elemento:x.indicator,Deriva_de:x.activityId||'',Conecta_con:x.activityId||'',Estado:x.confirmed?'COHERENTE CON DATOS PENDIENTES':'REQUIERE AJUSTE'});return r}
function render(){const c=$('#counter')?.textContent||'';if(!/^S(0[5-9]|1[0-2])/.test(c))return;const fields=$('#fields');if(!fields||$('#coherencePanel'))return;const r=report();const panel=document.createElement('section');panel.id='coherencePanel';panel.className='coherence-panel';panel.innerHTML=`<div class="coh-head"><div><strong>Motor de coherencia y trazabilidad</strong><p>Auditoría incremental del proyecto. La puntuación solo usa dimensiones actualmente evaluables.</p></div><div class="coh-score">${r.score}%</div></div><div class="coh-dims">${r.dimensions.map(d=>`<span>${esc(d.name)} ${d.score}%</span>`).join('')}</div><details><summary>Ver diagnóstico acumulado</summary><div class="coh-list">${r.checks.map(x=>`<article><b>${esc(x.status)}</b> · ${esc(x.label)}<p>${esc(x.message)}</p></article>`).join('')}</div></details>`;fields.appendChild(panel)}
window.fcGetCoherenceReport=report;window.fcGetTraceabilityRows=traceRows;
const style=document.createElement('style');style.textContent='.coherence-panel{margin-top:20px;border:2px solid var(--ink);border-radius:14px;padding:14px;background:#fff}.coh-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.coh-head p{margin:4px 0;color:var(--muted);font-size:.86rem}.coh-score{font-size:1.35rem;font-weight:800}.coh-dims{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.coh-dims span{border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:.76rem}.coh-list article{border-top:1px solid var(--line);padding:9px 0}.coh-list article p{margin:4px 0;color:var(--muted);font-size:.84rem}@media(max-width:720px){.coh-head{display:block}.coh-score{margin-top:8px}}';document.head.appendChild(style);new MutationObserver(render).observe(document.body,{subtree:true,childList:true});render();
})();