(()=>{
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function arr(v){return Array.isArray(v)?v:[]}
function tree(){try{return draft?.S07?.tree_state||JSON.parse(localStorage.getItem('formulador-cultural-problem-tree-v1')||'{}')}catch{return {}}}
function objectives(){try{return draft?.S09?.objectives_state||JSON.parse(localStorage.getItem('formulador-cultural-objectives-v1')||'{}')}catch{return {}}}
function alternatives(){try{return window.fcGetAlternatives?.()||[]}catch{return []}}
function results(){try{return window.fcGetResults?.()||[]}catch{return []}}
function activities(){try{return window.fcGetActivities?.()||[]}catch{return []}}
function indicators(){try{return window.fcGetIndicators?.()||[]}catch{return []}}
function schedule(){try{return window.fcGetSchedule?.()||[]}catch{return []}}
function budget(){try{return window.fcGetBudget?.()||[]}catch{return []}}
function budgetState(){try{return window.fcGetBudgetState?.()||{}}catch{return {}}}
function risks(){try{return window.fcGetRisks?.()||[]}catch{return []}}
function riskState(){try{return window.fcGetRiskState?.()||{}}catch{return {}}}
function evidence(){const d=draft?.S04||{};return [d.evidencia_disponible,d.fuentes].filter(x=>String(x||'').trim()).length}
function checks(){const out=[];const tn=arr(tree().nodes),on=arr(objectives().items),alts=alternatives(),res=results(),acts=activities(),inds=indicators();const central=tn.find(x=>x.zone==='central');const causes=tn.filter(x=>/cause/.test(x.zone||''));const objCentral=on.find(x=>x.zone==='central'&&x.confirmed);const objSpecific=on.filter(x=>x.confirmed&&(x.zone==='direct_cause'||x.zone==='indirect_cause'));const selAlt=alts.find(x=>x.selected&&x.confirmed),sch=schedule(),bud=budget(),bs=budgetState(),rsk=risks(),rs=riskState();
const add=(dimension,label,ok,msg,status)=>out.push({dimension,label,status:status||((ok)?'COHERENTE':'REQUIERE AJUSTE'),message:msg});
add('Evidencia','Problema conectado con el análisis previo',!!central&&!!String(central.origin||'').trim(),central?'El problema central tiene una conexión con información registrada antes.':'Todavía falta definir el problema central.');
add('Evidencia','Existe información de respaldo',evidence()>0,evidence()>0?'Hay información registrada que ayuda a respaldar la formulación.':'Aún falta registrar evidencia o fuentes.',evidence()>0?'COHERENTE':'INSUFFICIENT_EVIDENCE');
add('Lógica del proyecto','Problema → objetivo general',!!central&&!!objCentral,objCentral?'El objetivo general está conectado con el problema central.':'Confirma un objetivo general que responda directamente al problema central.');
add('Lógica del proyecto','Causas → objetivos específicos',causes.length>0&&objSpecific.length>0,objSpecific.length?`Hay ${objSpecific.length} objetivo(s) específico(s) relacionado(s) con las causas del árbol.`:'Faltan objetivos específicos derivados de las causas principales.');
const resByObj=new Map();res.filter(x=>x.confirmed).forEach(x=>resByObj.set(x.objectiveId,(resByObj.get(x.objectiveId)||0)+1));const orphanObj=objSpecific.filter(x=>!resByObj.get(x.id));add('Lógica del proyecto','Objetivos → resultados',objSpecific.length>0&&orphanObj.length===0,orphanObj.length?`${orphanObj.length} objetivo(s) todavía no tienen un resultado o producto claro.`:'Cada objetivo específico tiene al menos un resultado definido.');
const resultIds=new Set(res.filter(x=>x.confirmed).map(x=>x.id));const orphanActs=acts.filter(x=>x.confirmed&&!x.resultId);const actsByResult=new Map();acts.filter(x=>x.confirmed&&x.resultId).forEach(x=>actsByResult.set(x.resultId,(actsByResult.get(x.resultId)||0)+1));const orphanRes=res.filter(x=>x.confirmed&&!actsByResult.get(x.id));add('Lógica del proyecto','Resultados → actividades',resultIds.size>0&&orphanActs.length===0&&orphanRes.length===0,orphanActs.length||orphanRes.length?`${orphanActs.length} actividad(es) sin resultado asociado y ${orphanRes.length} resultado(s) sin actividades.`:'Los resultados tienen actividades asociadas.');
const confirmedInd=inds.filter(x=>x.confirmed),indByAct=new Set(confirmedInd.filter(x=>(x.linkedType||'Actividad')==='Actividad').map(x=>x.linkedId||x.activityId)),indByResult=new Set(confirmedInd.filter(x=>x.linkedType==='Resultado').map(x=>x.linkedId||x.resultId)),indByObjective=new Set(confirmedInd.filter(x=>x.linkedType==='Objetivo').map(x=>x.linkedId||x.objectiveId));
const missingInd=acts.filter(x=>x.confirmed&&!indByAct.has(x.id));add('Cómo comprobar avances','Actividades → indicadores',acts.some(x=>x.confirmed)&&missingInd.length===0,missingInd.length?`${missingInd.length} actividad(es) confirmada(s) todavía no tienen indicador.`:'Las actividades confirmadas tienen una forma de seguimiento.');
const missingResultInd=res.filter(x=>x.confirmed&&!indByResult.has(x.id));add('Cómo comprobar avances','Resultados → indicadores',res.some(x=>x.confirmed)&&missingResultInd.length===0,missingResultInd.length?`${missingResultInd.length} resultado(s) todavía no tienen indicador de resultado.`:'Los resultados confirmados tienen indicador.');
add('Cómo comprobar avances','Objetivo general → indicador',!!objCentral&&indByObjective.has(objCentral.id),objCentral?(indByObjective.has(objCentral.id)?'El objetivo general tiene un indicador asociado.':'Falta un indicador para el objetivo general.'):'Primero confirma el objetivo general.');
const incompleteInd=confirmedInd.filter(x=>['meta','lineaBase','unidad','periodicidad','medioVerificacion','responsable','plazo'].some(k=>!String(x[k]||'').trim()||/\[POR VERIFICAR\]/i.test(String(x[k]||''))));add('Cómo comprobar avances','Indicadores completos',confirmedInd.length>0&&incompleteInd.length===0,incompleteInd.length?`${incompleteInd.length} indicador(es) todavía tienen línea base, unidad, periodicidad, meta, fuente, responsable o plazo por completar.`:'Los indicadores tienen los campos mínimos completos.',incompleteInd.length?'COHERENTE CON DATOS PENDIENTES':'COHERENTE');
add('Lógica del proyecto','Alternativa elegida',!!selAlt,selAlt?'Ya existe una alternativa confirmada para orientar las actividades.':'Todavía falta confirmar cuál alternativa seguirá el proyecto.');
const confirmedActs=acts.filter(x=>x.confirmed),schMap=new Map(sch.map(x=>[x.activityId,x])),missingSchedule=confirmedActs.filter(a=>!schMap.get(a.id)?.confirmed);
add('Tiempo','Actividades → cronograma',confirmedActs.length>0&&missingSchedule.length===0,missingSchedule.length?`${missingSchedule.length} actividad(es) todavía no tienen fecha, duración y responsable confirmados.`:'Todas las actividades confirmadas están ubicadas en el tiempo.');
const scheduleIssues=window.fcGetScheduleIssues?.()||[];add('Tiempo','Dependencias temporales',scheduleIssues.length===0,scheduleIssues.length?scheduleIssues.join(' · '):'No se detectan dependencias temporales contradictorias.');
const activityStatus=bs.activityStatus||{},unbudgeted=confirmedActs.filter(a=>!activityStatus[a.id]||activityStatus[a.id]==='pending');
add('Presupuesto','Actividades → recursos y costos',confirmedActs.length>0&&unbudgeted.length===0,unbudgeted.length?`${unbudgeted.length} actividad(es) aún no indican cómo se cubrirán sus recursos.`:'Cada actividad indica si tiene costo, aporte en especie o no requiere costo adicional.');
const actIds=new Set(confirmedActs.map(x=>x.id)),orphanBudget=bud.filter(x=>!actIds.has(x.activityId));add('Presupuesto','Rubros vinculados a actividades',orphanBudget.length===0,orphanBudget.length?`${orphanBudget.length} rubro(s) no tienen una actividad vigente asociada.`:'Los rubros presupuestales están vinculados a actividades.');
const highUnanswered=rsk.filter(x=>x.riskLevel==='Alto'&&(!x.confirmed||/POR VERIFICAR/.test([x.preventiveResponse,x.contingencyResponse,x.owner].join(' '))));
add('Riesgos','Riesgos prioritarios con respuesta',highUnanswered.length===0,highUnanswered.length?`${highUnanswered.length} riesgo(s) alto(s) todavía no tienen respuesta y responsable confirmados.`:'Los riesgos altos identificados tienen respuesta y responsable.');
const targets=rs.targets||[],ass=rs.assessments||{},pendingRisks=targets.filter(t=>!ass[t.id]||ass[t.id]==='pending');add('Riesgos','Cobertura de revisión de riesgos',targets.length>0&&pendingRisks.length===0,pendingRisks.length?`${pendingRisks.length} elemento(s) todavía no han sido revisados frente a riesgos.`:'Las causas, resultados y actividades seleccionadas fueron revisadas frente a riesgos.');
return out}
function report(){const cs=checks(),evals=cs.filter(x=>x.status!=='AÚN NO EVALUABLE'),weight=s=>s==='COHERENTE'?1:s==='COHERENTE CON DATOS PENDIENTES'?0.5:0,total=evals.reduce((a,x)=>a+weight(x.status),0),score=evals.length?Math.round(total/evals.length*100):0;const dims={};for(const c of evals){dims[c.dimension]=dims[c.dimension]||{total:0,points:0};dims[c.dimension].total++;dims[c.dimension].points+=weight(c.status)}return {score,checks:cs,dimensions:Object.entries(dims).map(([name,v])=>({name,score:Math.round(v.points/v.total*100),...v}))}}
function traceRows(){const r=[];for(const n of arr(tree().nodes).filter(x=>x.zone!=='outside'))r.push({Tipo:'Problema',ID:n.id,Elemento:n.text,Deriva_de:n.origin||'S05',Conecta_con:n.parentId||'',Estado:n.reviewed?'COHERENTE':'REQUIERE AJUSTE'});for(const o of arr(objectives().items))r.push({Tipo:'Objetivo/medio/fin',ID:o.id,Elemento:o.text,Deriva_de:o.sourceText||'S07',Conecta_con:o.parentId||'',Estado:o.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of alternatives())r.push({Tipo:'Alternativa',ID:x.id,Elemento:x.text,Deriva_de:(x.sourceIds||[]).join(','),Conecta_con:'',Estado:x.confirmed?(x.selected?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'):'REQUIERE AJUSTE'});for(const x of results())r.push({Tipo:'Resultado',ID:x.id,Elemento:x.text,Deriva_de:x.objectiveId||'',Conecta_con:'',Estado:x.confirmed?'COHERENTE':'REQUIERE AJUSTE'});for(const x of activities())r.push({Tipo:'Actividad',ID:x.id,Elemento:x.text,Deriva_de:x.resultId||x.objectiveId||'',Conecta_con:x.resultId||'',Estado:x.confirmed?(x.resultId?'COHERENTE':'INCONSISTENCIA LÓGICA'):'REQUIERE AJUSTE'});for(const x of schedule())r.push({Tipo:'Cronograma',ID:x.id,Elemento:x.activityText||x.activityId,Deriva_de:x.activityId||'',Conecta_con:(x.dependencyIds||[]).join(','),Estado:x.confirmed?'COHERENTE':'REQUIERE AJUSTE'});
for(const x of budget())r.push({Tipo:'Presupuesto',ID:x.id,Elemento:x.description||'[POR VERIFICAR]',Deriva_de:x.activityId||'',Conecta_con:x.activityId||'',Estado:x.confirmed?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'});
for(const x of risks())r.push({Tipo:'Riesgo',ID:x.id,Elemento:x.event||'[POR VERIFICAR]',Deriva_de:x.linkedObjectId||'',Conecta_con:x.targetId||'',Estado:x.confirmed?'COHERENTE':'COHERENTE CON DATOS PENDIENTES'});
for(const x of indicators())r.push({Tipo:'Indicador',ID:x.id,Elemento:x.indicator,Deriva_de:x.linkedId||x.activityId||x.resultId||x.objectiveId||'',Conecta_con:(x.linkedType||'Actividad')+':'+(x.linkedId||x.activityId||x.resultId||x.objectiveId||''),Estado:x.confirmed?'COHERENTE CON DATOS PENDIENTES':'REQUIERE AJUSTE'});return r}
function humanStatus(s){return {'COHERENTE':'Bien','COHERENTE CON DATOS PENDIENTES':'Bien, pero faltan datos','REQUIERE AJUSTE':'Revisar','INCONSISTENCIA LÓGICA':'Hay una ruptura','INSUFFICIENT_EVIDENCE':'Falta evidencia','AÚN NO EVALUABLE':'Todavía no aplica'}[s]||s}
function render(){const c=$('#counter')?.textContent||'';if(!/^S(0[5-9]|1[0-6])/.test(c))return;const fields=$('#fields');if(!fields||$('#coherencePanel'))return;const r=report();const panel=document.createElement('section');panel.id='coherencePanel';panel.className='coherence-panel';panel.innerHTML=`<div class="coh-head"><div><strong>¿El proyecto sigue teniendo sentido?</strong><p>Revisamos si lo que acabas de escribir sigue conectado con lo anterior. No necesitas conocer la metodología para usar esta revisión.</p></div><div class="coh-score">${r.score}%</div></div><div class="coh-help">${r.score>=80?'La cadena del proyecto está bien conectada. Revisa los datos pendientes antes de cerrar.':r.score>=50?'La estructura va tomando forma, pero todavía hay relaciones por revisar.':'Hay varios puntos que conviene revisar antes de seguir avanzando.'}</div><div class="coh-dims">${r.dimensions.map(d=>`<span>${esc(d.name)} · ${d.score}%</span>`).join('')}</div><details><summary>¿Qué debo revisar?</summary><div class="coh-list">${r.checks.map(x=>`<article><b>${esc(humanStatus(x.status))}</b> · ${esc(x.label)}<p>${esc(x.message)}</p></article>`).join('')}</div></details><details><summary>¿Qué significa este porcentaje?</summary><p class="coh-explain">Es una guía, no una calificación. Solo cuenta las relaciones que ya pueden revisarse. El porcentaje resume únicamente relaciones que ya pueden comprobarse y siempre debe leerse junto con el diagnóstico.</p></details>`;fields.appendChild(panel)}
window.fcGetCoherenceReport=report;window.fcGetTraceabilityRows=traceRows;
const style=document.createElement('style');style.textContent='.coherence-panel{margin-top:20px;border:2px solid var(--ink);border-radius:14px;padding:14px;background:#fff}.coh-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.coh-head p{margin:4px 0;color:var(--muted);font-size:.9rem}.coh-score{font-size:1.35rem;font-weight:800}.coh-help{margin:10px 0;padding:10px;border-radius:10px;background:#f7f9fb;font-size:.9rem}.coh-dims{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.coh-dims span{border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:.76rem}.coh-list article{border-top:1px solid var(--line);padding:9px 0}.coh-list article p,.coh-explain{margin:4px 0;color:var(--muted);font-size:.86rem}@media(max-width:720px){.coh-head{display:block}.coh-score{margin-top:8px}}';document.head.appendChild(style);new MutationObserver(render).observe(document.body,{subtree:true,childList:true});render();
})();