(()=>{
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const KEYS={S10:'formulador-cultural-alternatives-v1',S11:'formulador-cultural-activities-v1',S12:'formulador-cultural-indicators-v1'};
function read(code){try{return draft?.[code]?.completion_state||JSON.parse(localStorage.getItem(KEYS[code])||'{}')}catch{return {}}}
function write(code,state){state.updatedAt=new Date().toISOString();localStorage.setItem(KEYS[code],JSON.stringify(state));if(typeof draft!=='undefined'){draft[code]=draft[code]||{};draft[code].completion_state=state;localStorage.setItem(storeKey,JSON.stringify(draft))}}
function objectives(){try{return draft?.S09?.objectives_state||JSON.parse(localStorage.getItem('formulador-cultural-objectives-v1')||'{}')}catch{return {}}}
function confirmedMeans(){return (objectives().items||[]).filter(x=>x.confirmed&&(x.zone==='direct_cause'||x.zone==='indirect_cause')).map(x=>({id:x.id,text:x.text,zone:x.zone}))}
function selectedAlternative(){return (read('S10').items||[]).find(x=>x.selected)||null}
function confirmedActivities(){return (read('S11').items||[]).filter(x=>x.confirmed)}
function makeAlternatives(){const means=confirmedMeans();const items=means.map((m,i)=>({id:`A${i+1}`,title:`Alternativa ${i+1}`,text:`Desarrollar una estrategia orientada a: ${m.text}`,sourceIds:[m.id],scores:{pertinencia:'',viabilidad:'',evidencia:'',alcance:''},selected:false,confirmed:false,note:''}));if(means.length>1)items.push({id:`A${items.length+1}`,title:'Alternativa integrada',text:`Articular acciones sobre: ${means.map(x=>x.text).join(' + ')}`,sourceIds:means.map(x=>x.id),scores:{pertinencia:'',viabilidad:'',evidencia:'',alcance:''},selected:false,confirmed:false,note:''});return items}
function ensureS10(){let s=read('S10');const sig=confirmedMeans().map(x=>`${x.id}:${x.text}`).join('|');if(!s.items||s.sourceSignature!==sig){const old=new Map((s.items||[]).map(x=>[x.id,x]));s={sourceSignature:sig,items:makeAlternatives().map(x=>old.get(x.id)||x),updatedAt:null};write('S10',s)}return s}
function activityProposals(){const alt=selectedAlternative(),means=confirmedMeans();if(!alt)return[];let n=1,out=[];for(const m of means.filter(x=>alt.sourceIds?.includes(x.id))){out.push({id:`ACT${n++}`,objectiveId:m.id,objectiveText:m.text,text:`Realizar un diagnóstico de las condiciones relacionadas con: ${m.text}`,confirmed:false,status:'propuesta',note:''});out.push({id:`ACT${n++}`,objectiveId:m.id,objectiveText:m.text,text:`Definir y priorizar acciones para avanzar en: ${m.text}`,confirmed:false,status:'propuesta',note:''});out.push({id:`ACT${n++}`,objectiveId:m.id,objectiveText:m.text,text:`Implementar y documentar las acciones priorizadas asociadas a: ${m.text}`,confirmed:false,status:'propuesta',note:''});out.push({id:`ACT${n++}`,objectiveId:m.id,objectiveText:m.text,text:`Verificar los resultados obtenidos respecto de: ${m.text}`,confirmed:false,status:'propuesta',note:''})}return out}
function ensureS11(){let s=read('S11');const alt=selectedAlternative(),sig=alt?`${alt.id}:${alt.text}:${(alt.sourceIds||[]).join(',')}`:'';if(!s.items||s.sourceSignature!==sig){s={sourceSignature:sig,alternativeId:alt?.id||'',alternativeText:alt?.text||'',items:activityProposals(),updatedAt:null};write('S11',s)}return s}
function indicatorProposal(a,i){return{id:`I${i+1}`,activityId:a.id,activityText:a.text,indicator:`Avance verificable de la actividad: ${a.text}`,meta:'[POR VERIFICAR]',lineaBase:'[POR VERIFICAR]',medioVerificacion:'[POR VERIFICAR]',responsable:'[POR VERIFICAR]',plazo:'[POR VERIFICAR]',confirmed:false}}
function ensureS12(){let s=read('S12');const acts=confirmedActivities(),sig=acts.map(x=>`${x.id}:${x.text}`).join('|');if(!s.items||s.sourceSignature!==sig){const old=new Map((s.items||[]).map(x=>[x.activityId,x]));s={sourceSignature:sig,items:acts.map((a,i)=>old.get(a.id)||indicatorProposal(a,i)),updatedAt:null};write('S12',s)}return s}
function sync(code){if(typeof session!=='undefined'&&session&&typeof syncSection==='function')syncSection(code).catch(()=>{})}
function renderS10(){const host=$('#fields');if(!host)return;const s=ensureS10();host.innerHTML=`<section class="completion-wrap"><div class="completion-note"><strong>Análisis de alternativas</strong><p>El sistema propone rutas a partir de los medios confirmados en S09. Evalúa cada alternativa y selecciona explícitamente la que mejor responda al proyecto.</p></div>${s.items.length?s.items.map(x=>`<article class="completion-card" data-alt="${x.id}"><div><strong>${esc(x.title)}</strong> <span class="completion-status ${x.confirmed?'ok':'pending'}">${x.confirmed?'Confirmada':'Propuesta asistida'}</span></div><label>Formulación<textarea data-alt-text="${x.id}">${esc(x.text)}</textarea></label><div class="completion-grid">${['pertinencia','viabilidad','evidencia','alcance'].map(k=>`<label>${k.charAt(0).toUpperCase()+k.slice(1)} (1–3)<select data-alt-score="${x.id}:${k}"><option value="">Sin valorar</option>${[1,2,3].map(n=>`<option ${String(x.scores?.[k])===String(n)?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}</div><label>Nota de decisión<textarea data-alt-note="${x.id}" placeholder="Explica por qué esta alternativa resulta pertinente o qué falta verificar.">${esc(x.note||'')}</textarea></label><div class="completion-actions"><button data-alt-confirm="${x.id}">${x.confirmed?'Actualizar confirmación':'Confirmar alternativa'}</button><button data-alt-select="${x.id}" class="${x.selected?'primary':''}">${x.selected?'Alternativa seleccionada':'Seleccionar para el proyecto'}</button></div></article>`).join(''):'<div class="completion-note"><strong>No hay medios confirmados en S09.</strong><p>Confirma al menos un medio antes de analizar alternativas.</p></div>'}<div class="completion-toolbar"><button id="goS11" class="primary" ${s.items.some(x=>x.selected&&x.confirmed)?'':'disabled'}>Continuar a S11 · actividades</button></div></section>`;bindS10(s)}
function bindS10(s){document.querySelectorAll('[data-alt-text]').forEach(el=>el.onchange=()=>{const x=s.items.find(i=>i.id===el.dataset.altText);x.text=el.value.trim();x.confirmed=false;write('S10',s)});document.querySelectorAll('[data-alt-score]').forEach(el=>el.onchange=()=>{const [id,k]=el.dataset.altScore.split(':');const x=s.items.find(i=>i.id===id);x.scores[k]=el.value?Number(el.value):'';write('S10',s)});document.querySelectorAll('[data-alt-note]').forEach(el=>el.onchange=()=>{const x=s.items.find(i=>i.id===el.dataset.altNote);x.note=el.value.trim();write('S10',s)});document.querySelectorAll('[data-alt-confirm]').forEach(b=>b.onclick=()=>{const x=s.items.find(i=>i.id===b.dataset.altConfirm);x.confirmed=!!x.text.trim();write('S10',s);sync('S10');renderS10()});document.querySelectorAll('[data-alt-select]').forEach(b=>b.onclick=()=>{s.items.forEach(i=>i.selected=i.id===b.dataset.altSelect);write('S10',s);renderS10()});$('#goS11')?.addEventListener('click',()=>window.fcNavigate?.('S11'))}
function renderS11(){const host=$('#fields');if(!host)return;const s=ensureS11();host.innerHTML=`<section class="completion-wrap"><div class="completion-note"><strong>Actividades propuestas</strong><p>Las actividades son borradores derivados de la alternativa seleccionada. Puedes editar, confirmar, eliminar o añadir actividades propias.</p><p><b>Alternativa:</b> ${esc(s.alternativeText||'[POR VERIFICAR]')}</p></div><div id="actList">${s.items.map(x=>`<article class="completion-card"><div><strong>${esc(x.id)}</strong> · ${esc(x.objectiveText||'')}</div><label>Actividad<textarea data-act-text="${x.id}">${esc(x.text)}</textarea></label><label>Observación<textarea data-act-note="${x.id}">${esc(x.note||'')}</textarea></label><div class="completion-actions"><button data-act-confirm="${x.id}">${x.confirmed?'Confirmada ✓':'Confirmar actividad'}</button><button data-act-delete="${x.id}">Eliminar</button></div></article>`).join('')}</div><div class="completion-toolbar"><button id="addAct">+ Añadir actividad</button><button id="goS12" class="primary" ${s.items.some(x=>x.confirmed)?'':'disabled'}>Continuar a S12 · metas e indicadores</button></div></section>`;bindS11(s)}
function bindS11(s){document.querySelectorAll('[data-act-text]').forEach(el=>el.onchange=()=>{const x=s.items.find(i=>i.id===el.dataset.actText);x.text=el.value.trim();x.confirmed=false;write('S11',s)});document.querySelectorAll('[data-act-note]').forEach(el=>el.onchange=()=>{const x=s.items.find(i=>i.id===el.dataset.actNote);x.note=el.value.trim();write('S11',s)});document.querySelectorAll('[data-act-confirm]').forEach(b=>b.onclick=()=>{const x=s.items.find(i=>i.id===b.dataset.actConfirm);x.confirmed=!!x.text.trim();write('S11',s);sync('S11');renderS11()});document.querySelectorAll('[data-act-delete]').forEach(b=>b.onclick=()=>{s.items=s.items.filter(i=>i.id!==b.dataset.actDelete);write('S11',s);renderS11()});$('#addAct').onclick=()=>{const id=`ACT${s.items.length+1}-${Date.now().toString().slice(-4)}`;s.items.push({id,objectiveId:'',objectiveText:'Actividad adicional',text:'',confirmed:false,status:'manual',note:''});write('S11',s);renderS11()};$('#goS12')?.addEventListener('click',()=>window.fcNavigate?.('S12'))}
function renderS12(){const host=$('#fields');if(!host)return;const s=ensureS12();host.innerHTML=`<section class="completion-wrap"><div class="completion-note"><strong>Metas e indicadores sugeridos</strong><p>El sistema propone la estructura de seguimiento. No inventa cifras: metas, línea base, responsable o plazo permanecen [POR VERIFICAR] hasta que el usuario disponga de datos.</p></div><div class="completion-scroll"><table class="completion-table"><thead><tr><th>Actividad</th><th>Indicador</th><th>Meta</th><th>Línea base</th><th>Medio de verificación</th><th>Responsable</th><th>Plazo</th><th>Estado</th></tr></thead><tbody>${s.items.map(x=>`<tr><td>${esc(x.activityText)}</td>${['indicator','meta','lineaBase','medioVerificacion','responsable','plazo'].map(k=>`<td><textarea data-ind-field="${x.id}:${k}">${esc(x[k])}</textarea></td>`).join('')}<td><button data-ind-confirm="${x.id}">${x.confirmed?'Confirmado ✓':'Confirmar'}</button></td></tr>`).join('')}</tbody></table></div><div class="completion-toolbar"><button id="exportFull" class="primary">Generar Excel completo</button></div></section>`;bindS12(s)}
function bindS12(s){document.querySelectorAll('[data-ind-field]').forEach(el=>el.onchange=()=>{const [id,k]=el.dataset.indField.split(':');const x=s.items.find(i=>i.id===id);x[k]=el.value.trim()||'[POR VERIFICAR]';x.confirmed=false;write('S12',s)});document.querySelectorAll('[data-ind-confirm]').forEach(b=>b.onclick=()=>{const x=s.items.find(i=>i.id===b.dataset.indConfirm);x.confirmed=true;write('S12',s);sync('S12');renderS12()});$('#exportFull').onclick=()=>window.fcExportCompleteWorkbook?.()}
function mount(){const c=$('#counter')?.textContent||'';if(c.startsWith('S10'))renderS10();else if(c.startsWith('S11'))renderS11();else if(c.startsWith('S12'))renderS12()}
window.fcGetAlternatives=()=>ensureS10().items||[];window.fcGetActivities=()=>ensureS11().items||[];window.fcGetIndicators=()=>ensureS12().items||[];
new MutationObserver(mount).observe(document.body,{subtree:true,childList:true});mount();
})();