(()=>{
const CV_KEY='formulador-cultural-causal-validation-v1';
const VESTER_KEY='formulador-cultural-vester-v1';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function cv(){try{return draft?.S06?.causal_validation||JSON.parse(localStorage.getItem(CV_KEY)||'{}')}catch{return {}}}
function vs(){try{return draft?.S06?.vester_state||JSON.parse(localStorage.getItem(VESTER_KEY)||'{}')}catch{return {}}}
function saveCV(s){s.updatedAt=new Date().toISOString();localStorage.setItem(CV_KEY,JSON.stringify(s));if(typeof draft!=='undefined'){draft.S06=draft.S06||{};draft.S06.causal_validation=s;try{localStorage.setItem(storeKey,JSON.stringify(draft))}catch{}}}
function pairRecommendation(p){
  if(!Number.isInteger(p.ab)||!Number.isInteger(p.ba))return {decision:'pending',title:'Completa ambas direcciones',why:'Antes de interpretar el par, asigna un valor a A→B y a B→A.'};
  const d=p.ab-p.ba;
  if(p.ab===0&&p.ba===0)return {decision:'none',title:'Probablemente no usar como relación causal',why:'Ninguna dirección registra influencia directa. Mantener este vínculo en el árbol aportaría poca información causal.'};
  if(d>=2&&p.ab>=2)return {decision:'a_to_b',title:'Revisar A como antecedente de B',why:`A→B=${p.ab} y B→A=${p.ba}. La diferencia sugiere una dirección de influencia más clara de A hacia B. Confirma que exista un mecanismo comprensible y plausible.`};
  if(d<=-2&&p.ba>=2)return {decision:'b_to_a',title:'Revisar B como antecedente de A',why:`B→A=${p.ba} y A→B=${p.ab}. La diferencia sugiere una dirección de influencia más clara de B hacia A. Confirma que exista un mecanismo comprensible y plausible.`};
  if(p.ab>=2&&p.ba>=2)return {decision:'indirect',title:'Evita asumir una causa directa automáticamente',why:'Ambas direcciones tienen valores altos. Puede existir retroalimentación, un factor intermedio o dos problemas estrechamente asociados. Conviene explicar el mecanismo antes de ubicarlos en el árbol.'};
  if(Math.abs(d)<=1)return {decision:'association',title:'La dirección causal no es clara',why:'Los valores son muy próximos. Vester muestra relación, pero no permite distinguir con claridad qué condición antecede a la otra.'};
  return {decision:'indirect',title:'Revisar como relación posiblemente mediada',why:'Existe una diferencia entre direcciones, pero todavía es moderada. Antes de usarla como causa directa, identifica si interviene otra variable.'};
}
function variableRecommendation(v){
  const q=String(v.quadrant||'').toLowerCase();
  if(q==='activo')return {role:'possible_cause',title:'Puede revisarse como posible causa',why:'Tiene influencia relativamente alta y dependencia baja dentro de la matriz. Esto orienta a revisar si antecede a otros problemas, aunque no lo demuestra.'};
  if(q==='pasivo')return {role:'possible_effect',title:'Puede revisarse como posible efecto',why:'Recibe relativamente más influencia de la que ejerce. Esto orienta a revisar si aparece como consecuencia de otros problemas.'};
  if(q==='crítico')return {role:'possible_central',title:'Puede ser candidato a problema central',why:'Combina influencia y dependencia altas. Puede articular varias relaciones, pero requiere revisar alcance, formulación y evidencia antes de elegirlo como central.'};
  if(q==='indiferente')return {role:'context',title:'Revisar si pertenece al núcleo del árbol',why:'Registra influencia y dependencia relativamente bajas. Puede ser una condición de contexto o una variable secundaria.'};
  return {role:'unclassified',title:'Aún no hay una orientación suficiente',why:'Revisa la formulación, las relaciones y la evidencia antes de asignar un papel en el árbol.'};
}
function overallGuide(){return `<div class="dg-overall"><strong>Cómo tomar estas decisiones</strong><ol><li><b>Lee primero la recomendación.</b> Está basada en tus propias puntuaciones de Vester.</li><li><b>Pregunta por el mecanismo.</b> ¿Cómo podría A producir realmente un cambio en B?</li><li><b>Revisa la evidencia.</b> Si falta soporte, conserva [POR VERIFICAR].</li><li><b>Decide tú.</b> La herramienta orienta, pero no convierte automáticamente una puntuación en causa, efecto o problema central.</li></ol><p><b>Objetivo:</b> ayudarte a presentar un proyecto con una lógica causal más clara, aun cuando no tengas formación especializada en formulación.</p></div>`}
function decorateVariables(){const s=cv(),cards=[...document.querySelectorAll('#causalValidation .cv-card')];cards.forEach((card,i)=>{if(card.querySelector('.dg-advice'))return;const v=s.variables?.[i];if(!v)return;const r=variableRecommendation(v);const box=document.createElement('div');box.className='dg-advice';box.innerHTML=`<strong>Orientación del formulador</strong><h4>${esc(r.title)}</h4><p>${esc(r.why)}</p><button type="button" data-dg-role="${esc(v.id)}" data-role="${r.role}">Usar esta orientación como rol preliminar</button>`;card.querySelector('header')?.insertAdjacentElement('afterend',box);box.querySelector('button')?.addEventListener('click',()=>{const fresh=cv(),item=fresh.variables?.find(x=>x.id===v.id);if(!item)return;item.role=r.role;saveCV(fresh);const sel=card.querySelector(`[data-cv-role="${CSS.escape(v.id)}"]`);if(sel)sel.value=r.role;box.querySelector('button').textContent='Orientación aplicada · puedes cambiarla';})})}
function decoratePairs(){const s=cv(),cards=[...document.querySelectorAll('#causalValidation .cv-pair')];cards.forEach((card,i)=>{if(card.querySelector('.dg-advice'))return;const p=s.pairs?.[i];if(!p)return;const r=pairRecommendation(p);const box=document.createElement('div');box.className='dg-advice';box.innerHTML=`<strong>Orientación del formulador</strong><h4>${esc(r.title)}</h4><p>${esc(r.why)}</p>${r.decision!=='pending'?`<button type="button" data-dg-pair="${esc(p.key)}">Usar esta recomendación</button>`:''}`;card.querySelector('.cv-ab')?.insertAdjacentElement('afterend',box);box.querySelector('button')?.addEventListener('click',()=>{const fresh=cv(),item=fresh.pairs?.find(x=>x.key===p.key);if(!item)return;item.decision=r.decision;saveCV(fresh);const sel=card.querySelector(`[data-pair-decision="${CSS.escape(p.key)}"]`);if(sel)sel.value=r.decision;box.querySelector('button').textContent='Recomendación aplicada · puedes cambiarla';})})}
function readiness(){const root=document.querySelector('#causalValidationBody');if(!root||root.querySelector('.dg-readiness'))return;const s=cv(),vars=s.variables||[],pairs=s.pairs||[];const confirmed=vars.filter(x=>x.status==='confirmed').length,pendingVars=vars.filter(x=>x.status==='pending'||x.status==='reformulate').length,pendingPairs=pairs.filter(x=>x.decision==='pending').length;const box=document.createElement('div');box.className='dg-readiness';box.innerHTML=`<strong>Estado para construir S07</strong><p>${confirmed>=2?'✓':'⚠'} ${confirmed} variables confirmadas · ${pendingVars?'⚠':'✓'} ${pendingVars} variables por revisar · ${pendingPairs?'⚠':'✓'} ${pendingPairs} relaciones pendientes.</p><p>${confirmed<2?'Confirma al menos dos variables.':pendingPairs?'Puedes avanzar, pero las relaciones pendientes llegarán al árbol como [POR VERIFICAR].':'El análisis tiene una base suficiente para pasar al árbol; todavía debes confirmar allí la ubicación final de causas y efectos.'}</p>`;root.prepend(box)}
function mount(){const root=document.querySelector('#causalValidation');if(!root)return;if(!root.querySelector('.dg-overall')){const h=root.querySelector('h3');h?.insertAdjacentHTML('afterend',overallGuide())}readiness();decorateVariables();decoratePairs()}
const style=document.createElement('style');style.textContent='.dg-overall,.dg-advice,.dg-readiness{border:1px solid #b8c7d6;background:#f7fbff;border-radius:11px;padding:11px 12px;margin:10px 0}.dg-overall ol{padding-left:20px;margin:8px 0}.dg-overall li{margin:5px 0}.dg-advice h4{margin:4px 0;font-size:.96rem}.dg-advice p,.dg-readiness p{margin:5px 0;color:#52606d;font-size:.86rem}.dg-advice button{margin-top:7px;border:1px solid #9fb0bf;background:#fff;border-radius:9px;padding:8px 10px;font:inherit}';document.head.appendChild(style);
new MutationObserver(mount).observe(document.body,{subtree:true,childList:true});mount();
})();