(()=>{
const CV_KEY='formulador-cultural-causal-validation-v1';
const VESTER_KEY='formulador-cultural-vester-v1';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function cv(){try{return draft?.S06?.causal_validation||JSON.parse(localStorage.getItem(CV_KEY)||'{}')}catch{return {}}}
function saveCV(s){s.updatedAt=new Date().toISOString();localStorage.setItem(CV_KEY,JSON.stringify(s));if(typeof draft!=='undefined'){draft.S06=draft.S06||{};draft.S06.causal_validation=s;try{localStorage.setItem(storeKey,JSON.stringify(draft))}catch{}}}
function pairRecommendation(p){
  if(!Number.isInteger(p.ab)||!Number.isInteger(p.ba))return {decision:'pending',title:'Falta completar esta comparación',why:'Primero califica A→B y luego B→A. Necesitamos las dos direcciones para poder orientarte.'};
  const d=p.ab-p.ba;
  if(p.ab===0&&p.ba===0)return {decision:'none',title:'Parece que estas dos situaciones no necesitan unirse',why:'Ninguna muestra influencia directa sobre la otra. Puedes dejarlas separadas en el árbol.'};
  if(d>=2&&p.ab>=2)return {decision:'a_to_b',title:'A podría ir antes que B',why:`A→B=${p.ab} y B→A=${p.ba}. Tus respuestas sugieren que A puede ayudar a explicar B. Antes de aceptarlo, pregúntate: ¿puedo explicar claramente cómo A produce un cambio en B?`};
  if(d<=-2&&p.ba>=2)return {decision:'b_to_a',title:'B podría ir antes que A',why:`B→A=${p.ba} y A→B=${p.ab}. Tus respuestas sugieren que B puede ayudar a explicar A. Antes de aceptarlo, pregúntate: ¿puedo explicar claramente cómo B produce un cambio en A?`};
  if(p.ab>=2&&p.ba>=2)return {decision:'indirect',title:'La relación existe, pero la dirección no es sencilla',why:'Las dos direcciones tienen valores altos. Puede haber un tercer factor o una relación más compleja. No la conviertas todavía en causa directa.'};
  if(Math.abs(d)<=1)return {decision:'association',title:'Todavía no sabemos cuál va primero',why:'Los valores son muy parecidos. Vester muestra que están relacionadas, pero no dice con claridad cuál causa a cuál.'};
  return {decision:'indirect',title:'Puede existir una relación, pero conviene revisarla',why:'Hay diferencia entre las dos direcciones, aunque no es suficiente para asumir una causa directa. Revisa si existe otra situación en medio.'};
}
function variableRecommendation(v){
  const q=String(v.quadrant||'').toLowerCase();
  if(q==='activo')return {role:'possible_cause',title:'Puede ser una causa',why:'Influye bastante sobre otras situaciones y depende poco de ellas. Úsalo como pista, no como conclusión automática.'};
  if(q==='pasivo')return {role:'possible_effect',title:'Puede ser un efecto',why:'Recibe más influencia de otras situaciones de la que ejerce. Revisa si aparece como consecuencia.'};
  if(q==='crítico')return {role:'possible_central',title:'Puede ser candidato a problema central',why:'Está muy conectado con otras situaciones. Antes de elegirlo, revisa si realmente resume el núcleo del problema.'};
  if(q==='indiferente')return {role:'context',title:'Puede ser una condición de contexto',why:'Tiene poca influencia y poca dependencia dentro de esta matriz. Tal vez ayude a explicar el entorno, pero no sea central.'};
  return {role:'unclassified',title:'Todavía no hay una orientación clara',why:'Revisa la redacción, las relaciones y la evidencia antes de decidir dónde ubicarlo.'};
}
function overallGuide(){return `<div class="dg-overall"><strong>¿Cómo usar esta revisión?</strong><ol><li><b>Mira la sugerencia.</b> Sale de las puntuaciones que tú diste en Vester.</li><li><b>Hazte una pregunta sencilla.</b> ¿Puedo explicar cómo una situación produce un cambio en la otra?</li><li><b>Revisa si tienes respaldo.</b> Si falta información, conserva [POR VERIFICAR].</li><li><b>Toma la decisión.</b> Puedes aceptar, cambiar o descartar la sugerencia.</li></ol><p>La herramienta te orienta para construir un árbol más claro; no decide por ti.</p></div>`}
function decorateVariables(){const s=cv(),cards=[...document.querySelectorAll('#causalValidation .cv-card')];cards.forEach((card,i)=>{if(card.querySelector('.dg-advice'))return;const v=s.variables?.[i];if(!v)return;const r=variableRecommendation(v);const box=document.createElement('div');box.className='dg-advice';box.innerHTML=`<strong>Una pista para decidir</strong><h4>${esc(r.title)}</h4><p>${esc(r.why)}</p><button type="button" data-dg-role="${esc(v.id)}" data-role="${r.role}">Usar esta sugerencia</button>`;card.querySelector('header')?.insertAdjacentElement('afterend',box);box.querySelector('button')?.addEventListener('click',()=>{const fresh=cv(),item=fresh.variables?.find(x=>x.id===v.id);if(!item)return;item.role=r.role;saveCV(fresh);const sel=card.querySelector(`[data-cv-role="${CSS.escape(v.id)}"]`);if(sel)sel.value=r.role;box.querySelector('button').textContent='Sugerencia aplicada · puedes cambiarla';})})}
function decoratePairs(){const s=cv(),cards=[...document.querySelectorAll('#causalValidation .cv-pair')];cards.forEach((card,i)=>{if(card.querySelector('.dg-advice'))return;const p=s.pairs?.[i];if(!p)return;const r=pairRecommendation(p);const box=document.createElement('div');box.className='dg-advice';box.innerHTML=`<strong>Una pista para decidir</strong><h4>${esc(r.title)}</h4><p>${esc(r.why)}</p>${r.decision!=='pending'?`<button type="button" data-dg-pair="${esc(p.key)}">Usar esta sugerencia</button>`:''}`;card.querySelector('.cv-ab')?.insertAdjacentElement('afterend',box);box.querySelector('button')?.addEventListener('click',()=>{const fresh=cv(),item=fresh.pairs?.find(x=>x.key===p.key);if(!item)return;item.decision=r.decision;saveCV(fresh);const sel=card.querySelector(`[data-pair-decision="${CSS.escape(p.key)}"]`);if(sel)sel.value=r.decision;box.querySelector('button').textContent='Sugerencia aplicada · puedes cambiarla';})})}
function readiness(){const root=document.querySelector('#causalValidationBody');if(!root||root.querySelector('.dg-readiness'))return;const s=cv(),vars=s.variables||[],pairs=s.pairs||[];const confirmed=vars.filter(x=>x.status==='confirmed').length,pendingVars=vars.filter(x=>x.status==='pending'||x.status==='reformulate').length,pendingPairs=pairs.filter(x=>x.decision==='pending').length;const box=document.createElement('div');box.className='dg-readiness';box.innerHTML=`<strong>¿Ya puedes pasar al árbol?</strong><p>${confirmed} variables listas · ${pendingVars} por revisar · ${pendingPairs} relaciones pendientes.</p><p>${confirmed<2?'Necesitas al menos dos variables confirmadas.':pendingPairs?'Puedes avanzar, pero las relaciones pendientes aparecerán como [POR VERIFICAR].':'Ya tienes una base suficiente para comenzar el árbol. Allí podrás cambiar cualquier ubicación.'}</p>`;root.prepend(box)}
function mount(){const root=document.querySelector('#causalValidation');if(!root)return;if(!root.querySelector('.dg-overall')){const h=root.querySelector('h3');h?.insertAdjacentHTML('afterend',overallGuide())}readiness();decorateVariables();decoratePairs()}
const style=document.createElement('style');style.textContent='.dg-overall,.dg-advice,.dg-readiness{border:1px solid #b8c7d6;background:#f7fbff;border-radius:11px;padding:11px 12px;margin:10px 0}.dg-overall ol{padding-left:20px;margin:8px 0}.dg-overall li{margin:5px 0}.dg-advice h4{margin:4px 0;font-size:.96rem}.dg-advice p,.dg-readiness p{margin:5px 0;color:#52606d;font-size:.88rem}.dg-advice button{margin-top:7px;border:1px solid #9fb0bf;background:#fff;border-radius:9px;padding:8px 10px;font:inherit}';document.head.appendChild(style);
new MutationObserver(mount).observe(document.body,{subtree:true,childList:true});mount();
})();