(()=>{
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function filename(){return (clean(draft?.S01?.nombre_del_proyecto)||'proyecto-cultural').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'proyecto-cultural'}
function problemNodes(){try{return (draft?.S07?.tree_state?.nodes||[]).filter(n=>n.zone!=='outside')}catch{return []}}
function objectiveNodes(){try{return window.fcGetObjectives?.()||draft?.S09?.objectives_state?.items||[]}catch{return []}}
function rows(fn){try{return fn?.()||[]}catch{return []}}
function svgFor(kind='problem'){
 const problem=kind==='problem',nodes=problem?problemNodes():objectiveNodes(),W=1400,cardW=270,cardH=74,gapY=125;
 const levels=problem?
 [['indirect_effect','Efectos indirectos','#fff0f0','#e35d5d'],['direct_effect','Efectos directos','#fff5f5','#e35d5d'],['central','Problema principal','#fff7d6','#d89a00'],['direct_cause','Causas directas','#eef9f1','#37a85b'],['indirect_cause','Causas indirectas','#f5fcf6','#37a85b']]:
 [['indirect_effect','Fines indirectos','#eef5ff','#4285f4'],['direct_effect','Fines directos','#f4f8ff','#4285f4'],['central','Objetivo central','#fff7d6','#d89a00'],['direct_cause','Medios directos','#eef9f1','#37a85b'],['indirect_cause','Medios indirectos','#f5fcf6','#37a85b']];
 const pos=new Map(),items=[];
 levels.forEach(([zone,label,bg,border],li)=>{const xs=nodes.filter(n=>n.zone===zone),count=Math.max(1,xs.length),total=count*cardW+(count-1)*26,start=(W-total)/2;xs.forEach((n,i)=>{const x=start+i*(cardW+26),y=35+li*gapY;pos.set(n.id,{x,y,zone});items.push({n,x,y,label,bg,border})})});
 const central=nodes.find(n=>n.zone==='central');let paths='';
 function anchor(n){if(n.zone==='direct_cause'||n.zone==='direct_effect')return central?.id||null;if(n.parentId)return n.parentId;if(n.zone==='indirect_cause')return nodes.find(x=>x.zone==='direct_cause')?.id||central?.id||null;if(n.zone==='indirect_effect')return nodes.find(x=>x.zone==='direct_effect')?.id||central?.id||null;return null}
 for(const n of nodes){if(n.zone==='central')continue;const a=pos.get(n.id),b=pos.get(anchor(n));if(!a||!b)continue;const above=['direct_effect','indirect_effect'].includes(n.zone),y1=above?a.y+cardH:a.y,y2=above?b.y:b.y+cardH,x1=a.x+cardW/2,x2=b.x+cardW/2,mid=(y1+y2)/2;paths+=`<path d="M${x1} ${y1} C${x1} ${mid},${x2} ${mid},${x2} ${y2}" fill="none" stroke="#34495e" stroke-width="2"/>`}
 const cards=items.map(({n,x,y,label,bg,border})=>{const words=clean(n.text).split(' '),ls=[];let cur='';for(const w of words){if((cur+' '+w).trim().length>34){ls.push(cur);cur=w}else cur=(cur+' '+w).trim()}if(cur)ls.push(cur);return `<g><rect x="${x}" y="${y}" width="${cardW}" height="${cardH}" rx="12" fill="${bg}" stroke="${border}" stroke-width="${n.zone==='central'?3:2}"/><text x="${x+cardW/2}" y="${y+19}" text-anchor="middle" font-family="Arial" font-size="13" font-weight="700" fill="${border}">${esc(label)}</text>${ls.slice(0,3).map((t,i)=>`<text x="${x+cardW/2}" y="${y+40+i*15}" text-anchor="middle" font-family="Arial" font-size="13" fill="#1f2933">${esc(t)}</text>`).join('')}</g>`}).join('');
 const H=35+levels.length*gapY;return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="white"/>${paths}${cards}</svg>`
}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportSvg(kind){download(filename()+'-'+(kind==='problem'?'arbol-problemas':'arbol-objetivos')+'.svg',new Blob([svgFor(kind)],{type:'image/svg+xml;charset=utf-8'}))}
function openSvg(kind){const w=window.open();if(w){w.document.write('<title>Diagrama</title><style>body{margin:0;background:#f4f6f8;display:grid;place-items:center;min-height:100vh}svg{max-width:98vw;height:auto;background:#fff}</style>'+svgFor(kind));w.document.close()}}
async function loadScript(src,test){if(test())return;await new Promise((ok,fail)=>{const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=fail;document.head.appendChild(s)})}
function p(v){const t=clean(v);return t||'[POR VERIFICAR]'}
function moneyRaw(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n):'[POR VERIFICAR]'}
function table(headers,body){return '<table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function reportHtml(){
 const acts=rows(window.fcGetActivities).filter(x=>x.confirmed),res=rows(window.fcGetResults).filter(x=>x.confirmed),inds=rows(window.fcGetIndicators).filter(x=>x.confirmed),sch=rows(window.fcGetSchedule),bud=rows(window.fcGetBudget),risks=rows(window.fcGetRisks),bs=window.fcGetBudgetSummary?.()||{};
 const obj=objectiveNodes().filter(x=>x.confirmed),central=obj.find(x=>x.zone==='central'),spec=obj.filter(x=>x.zone==='direct_cause'),meansIndirect=obj.filter(x=>x.zone==='indirect_cause'),ends=obj.filter(x=>x.zone==='direct_effect'||x.zone==='indirect_effect'),alt=rows(window.fcGetAlternatives).find(x=>x.selected&&x.confirmed),coherence=window.fcGetCoherenceReport?.()||{score:0,checks:[]};
 return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(p(draft?.S01?.nombre_del_proyecto))}</title><style>@page{margin:22mm}body{font-family:Arial,sans-serif;color:#1f2933;line-height:1.45;max-width:980px;margin:auto;padding:30px}h1{font-size:28px}h2{margin-top:30px;border-bottom:1px solid #dfe4e8;padding-bottom:6px}table{width:100%;border-collapse:collapse;margin:10px 0 18px}th,td{border:1px solid #dfe4e8;padding:7px;text-align:left;vertical-align:top;font-size:12px}th{background:#f5f7f9}.note{background:#fff8df;border:1px solid #eadc9b;border-radius:8px;padding:10px}.diagram{overflow:auto;margin:14px 0}.diagram svg{width:100%;height:auto}small{color:#66717c}</style></head><body>
 <h1>${esc(p(draft?.S01?.nombre_del_proyecto))}</h1><p><b>Entidad:</b> ${esc(p(draft?.S01?.entidad_u_organizacion))}<br><b>Territorio:</b> ${esc(p(draft?.S02?.territorio_o_lugar_de_intervencion||draft?.S01?.municipio))}<br><b>Responsable:</b> ${esc(p(draft?.S01?.responsable))}</p>
 <h2>1. Resumen ejecutivo</h2><p>${esc(p(draft?.S08?.enunciado))}</p>
 <h2>2. Contexto territorial, cultural y social</h2><p>${esc(p(draft?.S02?.territorio_o_lugar_de_intervencion))}</p><p>${esc(p(draft?.S02?.caracteristicas_culturales))}</p><p>${esc(p(draft?.S02?.principales_dinamicas_sociales))}</p>
 <h2>3. Población</h2><p><b>Población atendida:</b> ${esc(p(draft?.S03?.poblacion_afectada))}</p><p><b>Participantes:</b> ${esc(p(draft?.S03?.poblacion_participante))}</p><p>${esc(p(draft?.S03?.caracterizacion))}</p>
 <h2>4. Evidencia y antecedentes</h2><p>${esc(p(draft?.S04?.evidencia_disponible))}</p><p><b>Fuentes:</b> ${esc(p(draft?.S04?.fuentes))}</p>${draft?.S04?.datos_por_verificar?'<div class="note"><b>Datos por verificar:</b> '+esc(draft.S04.datos_por_verificar)+'</div>':''}
 <h2>5. Planteamiento del problema</h2><p>${esc(p(draft?.S08?.enunciado))}</p><div class="diagram">${svgFor('problem')}</div>
 <h2>6. Objetivos</h2><p><b>Objetivo general:</b> ${esc(p(central?.text))}</p><h3>Objetivos específicos</h3>${spec.length?'<ul>'+spec.map(x=>'<li>'+esc(x.text)+'</li>').join('')+'</ul>':'<p>[POR VERIFICAR] No hay objetivos específicos confirmados derivados de causas directas.</p>'}${meansIndirect.length?'<h3>Medios del árbol de objetivos</h3><ul>'+meansIndirect.map(x=>'<li>'+esc(x.text)+'</li>').join('')+'</ul>':''}${ends.length?'<h3>Fines esperados</h3><ul>'+ends.map(x=>'<li>'+esc(x.text)+'</li>').join('')+'</ul>':''}<div class="diagram">${svgFor('objective')}</div>
 <h2>7. Estrategia de intervención</h2><p>${esc(p(alt?.text))}</p><h2>8. Resultados esperados</h2>${res.length?'<ul>'+res.map(x=>'<li>'+esc(x.text)+'</li>').join('')+'</ul>':'<p>[POR VERIFICAR]</p>'}
 <h2>9. Actividades</h2>${acts.length?table(['ID','Resultado/objetivo','Actividad'],acts.map(x=>[x.id,x.resultText||x.objectiveText||'',x.text])):'<p>[POR VERIFICAR]</p>'}
 <h2>10. Cronograma</h2>${sch.length?table(['Actividad','Inicio','Fin','Responsable','Frecuencia'],sch.map(x=>[x.activityText,x.startDate||'[POR VERIFICAR]',x.endDate||'[POR VERIFICAR]',x.responsible||'[POR VERIFICAR]',x.frequency||''])):'<p>[POR VERIFICAR]</p>'}
 <h2>11. Indicadores y metas</h2>${inds.length?table(['Nivel','Elemento','Indicador','Fórmula/criterio','Línea base','Meta','Unidad','Periodicidad','Medio de verificación','Responsable','Plazo'],inds.map(x=>[x.linkedType||'Actividad',x.linkedText||x.activityText||'',x.indicator,x.formula||'[POR VERIFICAR]',x.lineaBase,x.meta,x.unidad,x.periodicidad,x.medioVerificacion,x.responsable,x.plazo])):'<p>[POR VERIFICAR]</p>'}
 <h2>12. Recursos y presupuesto</h2>${bud.length?table(['Actividad','Recurso','Unidad','Cantidad','Veces','Costo unitario','Total','Tipo'],bud.map(x=>[x.activityText,x.description,x.unit,String(x.quantity),String(x.frequency),moneyRaw(x.unitCost),moneyRaw(x.totalCost),x.costType])):'<p>[POR VERIFICAR]</p>'}<p><b>Total valorizado:</b> ${moneyRaw(bs.total)}</p>
 <h2>13. Riesgos y respuestas</h2>${risks.length?table(['Origen','Riesgo','Probabilidad','Impacto','Nivel','Prevención','Contingencia','Responsable'],risks.map(x=>[x.linkedObjectType,x.event,x.probability,x.impact,x.riskLevel,x.preventiveResponse,x.contingencyResponse,x.owner])):'<p>[POR VERIFICAR]</p>'}
 <h2>14. Coherencia y trazabilidad</h2><p><b>Índice orientativo de coherencia:</b> ${coherence.score}%</p>${coherence.checks?.length?'<ul>'+coherence.checks.map(x=>'<li><b>'+esc(x.label)+':</b> '+esc(x.message)+'</li>').join('')+'</ul>':''}
 <h2>15. Fuentes y anexos</h2><p>${esc(p(draft?.S04?.fuentes))}</p><small>Documento generado a partir de información registrada en el Formulador Cultural. Los vacíos conservan la marca [POR VERIFICAR].</small></body></html>`
}
function exportHtml(){download(filename()+'-proyecto.html',new Blob([reportHtml()],{type:'text/html;charset=utf-8'}))}
async function exportPdf(){await loadScript('https://cdn.jsdelivr.net/npm/html2pdf.js@0.10.1/dist/html2pdf.bundle.min.js',()=>typeof html2pdf!=='undefined');const holder=document.createElement('div');holder.innerHTML=reportHtml().match(/<body>([\s\S]*)<\/body>/i)?.[1]||reportHtml();document.body.appendChild(holder);try{await html2pdf().set({margin:10,filename:filename()+'-proyecto.pdf',image:{type:'jpeg',quality:.96},html2canvas:{scale:1.3,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from(holder).save()}finally{holder.remove()}}
function xmlEsc(v){return clean(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function docParagraph(text,style){return '<w:p>'+((style)?'<w:pPr><w:pStyle w:val="'+style+'"/></w:pPr>':'')+'<w:r><w:t xml:space="preserve">'+xmlEsc(text)+'</w:t></w:r></w:p>'}
function reportParagraphs(){
 const out=[],add=(h,t)=>{out.push(docParagraph(h,'Heading1'));(Array.isArray(t)?t:[t]).filter(Boolean).forEach(x=>out.push(docParagraph(x)))};
 add(p(draft?.S01?.nombre_del_proyecto),['Entidad: '+p(draft?.S01?.entidad_u_organizacion),'Territorio: '+p(draft?.S02?.territorio_o_lugar_de_intervencion||draft?.S01?.municipio)]);
 add('1. Resumen ejecutivo',p(draft?.S08?.enunciado));
 add('2. Contexto',[p(draft?.S02?.territorio_o_lugar_de_intervencion),p(draft?.S02?.caracteristicas_culturales)]);
 add('3. Población',[p(draft?.S03?.poblacion_afectada),p(draft?.S03?.poblacion_participante)]);
 add('4. Problema',p(draft?.S08?.enunciado));
 const docObj=objectiveNodes().filter(x=>x.confirmed);
 add('5. Objetivo general',p(docObj.find(x=>x.zone==='central')?.text));
 add('6. Objetivos específicos',docObj.filter(x=>x.zone==='direct_cause').map(x=>p(x.text)));
 if(docObj.some(x=>x.zone==='indirect_cause'))add('Medios del árbol de objetivos',docObj.filter(x=>x.zone==='indirect_cause').map(x=>p(x.text)));
 if(docObj.some(x=>x.zone==='direct_effect'||x.zone==='indirect_effect'))add('Fines esperados',docObj.filter(x=>x.zone==='direct_effect'||x.zone==='indirect_effect').map(x=>p(x.text)));
 add('7. Estrategia',p(rows(window.fcGetAlternatives).find(x=>x.selected&&x.confirmed)?.text));
 add('8. Resultados',rows(window.fcGetResults).filter(x=>x.confirmed).map(x=>p(x.text)));
 add('9. Actividades',rows(window.fcGetActivities).filter(x=>x.confirmed).map(x=>x.id+' · '+p(x.text)));
 add('10. Cronograma',rows(window.fcGetSchedule).map(x=>p(x.activityText)+' | '+p(x.startDate)+' - '+p(x.endDate)+' | '+p(x.responsible)));
 add('11. Indicadores y metas',rows(window.fcGetIndicators).filter(x=>x.confirmed).map(x=>p(x.linkedType)+' · '+p(x.indicator)+' | Fórmula/criterio: '+p(x.formula)+' | Línea base: '+p(x.lineaBase)+' | Meta: '+p(x.meta)+' | Unidad: '+p(x.unidad)+' | Periodicidad: '+p(x.periodicidad)+' | Fuente: '+p(x.medioVerificacion)+' | Responsable: '+p(x.responsable)+' | Plazo: '+p(x.plazo)));
 add('12. Presupuesto',rows(window.fcGetBudget).map(x=>p(x.activityText)+' | '+p(x.description)+' | '+moneyRaw(x.totalCost)));
 add('13. Riesgos',rows(window.fcGetRisks).map(x=>p(x.event)+' | '+p(x.riskLevel)+' | '+p(x.preventiveResponse)));
 add('14. Fuentes',p(draft?.S04?.fuentes));
 return out.join('')
}
async function exportDocx(){await loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js',()=>typeof JSZip!=='undefined');const zip=new JSZip(),body=reportParagraphs();zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.folder('word').folder('_rels').file('document.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>');zip.folder('word').file('document.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+body+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>');zip.folder('word').file('styles.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:rPr><w:b/><w:sz w:val="30"/></w:rPr></w:style></w:styles>');const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});download(filename()+'-proyecto.docx',blob)}
async function treePdf(kind){await loadScript('https://cdn.jsdelivr.net/npm/html2pdf.js@0.10.1/dist/html2pdf.bundle.min.js',()=>typeof html2pdf!=='undefined');const div=document.createElement('div');div.style.padding='20px';div.innerHTML='<h2>'+(kind==='problem'?'Árbol de problemas':'Árbol de objetivos')+'</h2>'+svgFor(kind);document.body.appendChild(div);try{await html2pdf().set({filename:filename()+'-'+(kind==='problem'?'arbol-problemas':'arbol-objetivos')+'.pdf',margin:8,html2canvas:{scale:1.5},jsPDF:{unit:'mm',format:'a3',orientation:'landscape'}}).from(div).save()}finally{div.remove()}}
window.fcTreeSvg=svgFor;window.fcExportProblemTreeSVG=()=>exportSvg('problem');window.fcExportObjectiveTreeSVG=()=>exportSvg('objective');window.fcOpenProblemTree=()=>openSvg('problem');window.fcOpenObjectiveTree=()=>openSvg('objective');window.fcExportProblemTreePDF=()=>treePdf('problem');window.fcExportObjectiveTreePDF=()=>treePdf('objective');window.fcExportProjectHTML=exportHtml;window.fcExportProjectPDF=exportPdf;window.fcExportProjectDOCX=exportDocx;window.fcProjectReportHTML=reportHtml;
})();
