(()=>{
const client=typeof sb!=='undefined'?sb:null;
let evidenceSession=null,evidenceProject=null,rendering=false,evidenceCache=[];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const kindLabel={institutional:'Documento institucional',research:'Investigación/publicación',administrative:'Registro administrativo',observation:'Observación directa',interview:'Entrevista o testimonio',web:'Fuente web',other:'Otro'};
const statusLabel={verificada:'Verificada',por_verificar:'Por verificar',descartada:'Descartada'};
async function currentProject(){if(evidenceProject)return evidenceProject;const {data,error}=await client.from('projects').select('*').order('updated_at',{ascending:false}).limit(1);if(error)throw error;evidenceProject=data?.[0]||null;return evidenceProject;}
function shell(){return `<section class="evidence-registry" id="evidenceRegistry"><div class="evidence-head"><div><h3>Registro trazable de evidencia</h3><p>Registra cada evidencia como una unidad independiente. Una propuesta generada por IA no se clasifica como evidencia.</p></div><span class="evidence-count" id="evidenceCount">0 registros</span></div><div class="evidence-review"><strong>Antes de guardar, revisa:</strong> que la fuente exista, que el dato corresponda al proyecto, que la fecha y referencia sean identificables y que el estado de verificación refleje lo realmente comprobado.</div><div id="evidenceAuthNote" class="evidence-note"></div><form id="evidenceForm" class="evidence-form"><label>Título o dato respaldado <span class="required">· requerido</span><input id="evTitle" type="text" placeholder="Ej.: Matrícula de la banda 2026" required></label><label>Descripción de la evidencia <span class="required">· requerido</span><textarea id="evText" placeholder="Describe el dato, hecho o contenido observable que aporta la fuente." required></textarea></label><div class="evidence-grid"><label>Tipo de fuente <select id="evKind"><option value="institutional">Documento institucional</option><option value="research">Investigación/publicación</option><option value="administrative">Registro administrativo</option><option value="observation">Observación directa</option><option value="interview">Entrevista o testimonio</option><option value="web">Fuente web</option><option value="other">Otro</option></select></label><label>Estado de verificación <select id="evStatus"><option value="por_verificar">Por verificar</option><option value="verificada">Verificada</option><option value="descartada">Descartada</option></select></label><label>Fecha de la fuente <input id="evDate" type="date"></label><label>Referencia / autor / entidad <input id="evRef" type="text" placeholder="Entidad, autor, documento o expediente"></label></div><label>URL o enlace de consulta <input id="evUrl" type="url" inputmode="url" placeholder="https://..."></label><label>Notas de trazabilidad <textarea id="evNotes" placeholder="Página, sección, condiciones de consulta, limitaciones o información pendiente."></textarea></label><button class="primary" type="submit" id="evSave">Guardar evidencia</button></form><div class="evidence-list" id="evidenceList"></div></section>`;}
async function fetchEvidenceRecords(){
 if(!evidenceSession||!client)return [];
 const p=await currentProject();if(!p)return [];
 const {data,error}=await client.from('evidence').select('id,title,text,source_kind,source_ref,source_url,source_date,verification_status,notes,created_at').eq('project_id',p.id).eq('section_code','S04').order('created_at',{ascending:false});
 if(error)throw error;evidenceCache=data||[];return evidenceCache
}
async function loadEvidence(){const list=$('#evidenceList'),note=$('#evidenceAuthNote');if(!list)return;if(!evidenceSession){note.textContent='Inicia sesión para guardar y consultar evidencia estructurada. Los campos generales de S04 siguen disponibles como borrador local.';$('#evidenceForm').classList.add('evidence-disabled');return;}$('#evidenceForm').classList.remove('evidence-disabled');note.textContent='La evidencia se guarda en la nube y queda asociada al proyecto autenticado.';try{const p=await currentProject();if(!p){list.innerHTML='<p class="evidence-empty">Primero guarda o sincroniza el proyecto.</p>';return;}const data=await fetchEvidenceRecords();$('#evidenceCount').textContent=`${data.length} ${data.length===1?'registro':'registros'}`;if(!data.length){list.innerHTML='<p class="evidence-empty">Aún no hay evidencia estructurada. Agrega la primera fuente cuando cuentes con un respaldo identificable.</p>';return;}list.innerHTML=data.map(r=>`<article class="evidence-item"><div class="evidence-item-top"><strong>${esc(r.title||'Evidencia')}</strong><span class="ev-status ${esc(r.verification_status)}">${esc(statusLabel[r.verification_status]||r.verification_status)}</span></div><p>${esc(r.text)}</p><dl><div><dt>Fuente</dt><dd>${esc(kindLabel[r.source_kind]||r.source_kind)}${r.source_ref?` · ${esc(r.source_ref)}`:''}</dd></div>${r.source_date?`<div><dt>Fecha</dt><dd>${esc(r.source_date)}</dd></div>`:''}${r.source_url?`<div><dt>Enlace</dt><dd><a href="${esc(r.source_url)}" target="_blank" rel="noopener">Abrir fuente</a></dd></div>`:''}${r.notes?`<div><dt>Notas</dt><dd>${esc(r.notes)}</dd></div>`:''}</dl><button class="ev-delete" type="button" data-delete="${r.id}">Eliminar registro</button></article>`).join('');}catch(e){list.innerHTML=`<p class="evidence-error">No fue posible cargar la evidencia: ${esc(e.message||'error desconocido')}</p>`;}}
async function addEvidence(ev){ev.preventDefault();if(!evidenceSession){$('#evidenceAuthNote').textContent='Debes iniciar sesión para registrar evidencia estructurada.';return;}const title=$('#evTitle').value.trim(),text=$('#evText').value.trim();if(!title||!text)return;const btn=$('#evSave');btn.disabled=true;btn.textContent='Guardando…';try{const p=await currentProject();if(!p)throw new Error('Guarda o sincroniza primero el proyecto.');const status=$('#evStatus').value;const payload={project_id:p.id,section_code:'S04',field_name:'evidencia_estructurada',title,text,source_kind:$('#evKind').value,source_ref:$('#evRef').value.trim()||null,source_url:$('#evUrl').value.trim()||null,source_date:$('#evDate').value||null,verification_status:status,verified:status==='verificada',notes:$('#evNotes').value.trim()||null,updated_at:new Date().toISOString()};const {error}=await client.from('evidence').insert(payload);if(error)throw error;$('#evidenceForm').reset();await loadEvidence();}catch(e){$('#evidenceAuthNote').textContent=`No fue posible guardar: ${e.message||'error desconocido'}`;}finally{btn.disabled=false;btn.textContent='Guardar evidencia';}}
async function removeEvidence(id){if(!evidenceSession||!confirm('¿Eliminar este registro de evidencia?'))return;const {error}=await client.from('evidence').delete().eq('id',id);if(error){$('#evidenceAuthNote').textContent=`No fue posible eliminar: ${error.message}`;return;}await loadEvidence();}
async function inject(){if(rendering)return;const counter=$('#counter'),fields=$('#fields');if(!counter||!fields||!counter.textContent.startsWith('S04')||$('#evidenceRegistry'))return;rendering=true;fields.insertAdjacentHTML('beforeend',shell());$('#evidenceForm').addEventListener('submit',addEvidence);$('#evidenceList').addEventListener('click',e=>{const id=e.target?.dataset?.delete;if(id)removeEvidence(id)});await loadEvidence();rendering=false;}
async function init(){if(!client)return;const {data}=await client.auth.getSession();evidenceSession=data.session;client.auth.onAuthStateChange((_e,s)=>{evidenceSession=s;evidenceProject=null;if($('#evidenceRegistry'))loadEvidence()});new MutationObserver(()=>inject()).observe(document.body,{subtree:true,childList:true,characterData:true});inject();}
window.fcGetEvidenceRecords=()=>evidenceCache.slice();window.fcLoadEvidenceRecords=fetchEvidenceRecords;
init();
})();
