(()=>{
function text(v){return String(v??'').replace(/\s+/g,' ').trim()}
function compact(v,max=30){const t=text(v);return window.fcWriting?.compactPresentationText?window.fcWriting.compactPresentationText(t,max):t}
function rowsFrom(fn){try{return typeof fn==='function'?(fn()||[]):[]}catch{return []}}
function addJson(wb,name,rows){const data=rows.length?rows:[{Estado:'Sin registros'}];const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=Object.keys(data[0]).map(k=>({wch:Math.min(55,Math.max(14,k.length+4))}));XLSX.utils.book_append_sheet(wb,ws,name)}
function addAoa(wb,name,aoa){const ws=XLSX.utils.aoa_to_sheet(aoa);const max=Math.max(1,...aoa.map(r=>r.length));ws['!cols']=Array.from({length:max},()=>({wch:34}));XLSX.utils.book_append_sheet(wb,ws,name)}
function treeProblemAoa(){const s=draft?.S07?.tree_state||JSON.parse(localStorage.getItem('formulador-cultural-problem-tree-v1')||'{}');const nodes=(s.nodes||[]).filter(n=>n.zone!=='outside');const order=[['indirect_effect','EFECTOS INDIRECTOS'],['direct_effect','EFECTOS DIRECTOS'],['central','PROBLEMA CENTRAL'],['direct_cause','CAUSAS DIRECTAS'],['indirect_cause','CAUSAS INDIRECTAS']];const a=[['ÁRBOL DE PROBLEMAS']];order.forEach(([z,l],i)=>{a.push([l]);const xs=nodes.filter(n=>n.zone===z);a.push(xs.length?xs.map(x=>text(x.text)):['Sin elementos']);if(i<order.length-1)a.push(['↑'])});return a}
function treeObjectiveAoa(){const s=draft?.S09?.objectives_state||JSON.parse(localStorage.getItem('formulador-cultural-objectives-v1')||'{}');const items=s.items||[];const order=[['indirect_effect','FINES INDIRECTOS'],['direct_effect','FINES DIRECTOS'],['central','OBJETIVO CENTRAL'],['direct_cause','MEDIOS DIRECTOS'],['indirect_cause','MEDIOS INDIRECTOS']];const a=[['ÁRBOL DE OBJETIVOS']];order.forEach(([z,l],i)=>{a.push([l]);const xs=items.filter(n=>n.zone===z);a.push(xs.length?xs.map(x=>text(x.text)):['Sin elementos']);if(i<order.length-1)a.push(['↑'])});return a}
function problemRelations(){const s=draft?.S07?.tree_state||{};const nodes=s.nodes||[],map=new Map(nodes.map(n=>[n.id,n]));return nodes.filter(n=>n.zone&&n.zone!=='outside').map(n=>({ID:n.id,Nivel:n.zone,Formulación:n.text||'',Conecta_con:n.parentId?(map.get(n.parentId)?.text||n.parentId):'',Justificación:n.justification||'[POR VERIFICAR]',Revisado:n.reviewed?'Sí':'No'}))}
function objectivesRows(){const items=rowsFrom(window.fcGetObjectives);return items.map(x=>({ID:x.id,Nivel:x.zone,Formulación:x.text||'',Fuente_S07:x.sourceText||'',Confirmado:x.confirmed?'Sí':'No'}))}
function alternativesRows(){return rowsFrom(window.fcGetAlternatives).map(x=>({ID:x.id,Alternativa:x.text,Confirmada:x.confirmed?'Sí':'No',Seleccionada:x.selected?'Sí':'No',Pertinencia:x.scores?.pertinencia??'',Viabilidad:x.scores?.viabilidad??'',Evidencia:x.scores?.evidencia??'',Alcance:x.scores?.alcance??'',Nota:x.note||''}))}
function resultsRows(){return rowsFrom(window.fcGetResults).map(x=>({ID:x.id,Objetivo_ID:x.objectiveId||'',Objetivo:compact(x.objectiveText||'',32),Resultado_producto:compact(x.text||'',32),Texto_original:x.text&&compact(x.text,32)!==text(x.text)?x.text:'',Confirmado:x.confirmed?'Sí':'No',Nota:x.note||''}))}
function activitiesRows(){return rowsFrom(window.fcGetActivities).map(x=>({ID:x.id,Resultado_ID:x.resultId||'',Resultado:compact(x.resultText||'',32),Objetivo_ID:x.objectiveId||'',Objetivo_o_medio:compact(x.objectiveText||'',32),Actividad:compact(x.text||'',28),Texto_original:x.text&&compact(x.text,28)!==text(x.text)?x.text:'',Confirmada:x.confirmed?'Sí':'No',Observación:x.note||''}))}
function indicatorsRows(){return rowsFrom(window.fcGetIndicators).map(x=>({ID:x.id,Tipo:x.linkedType||'Actividad',Elemento_ID:x.linkedId||x.activityId||'',Elemento:compact(x.linkedText||x.activityText||'',30),Indicador:x.indicator||'',Fórmula_o_criterio:x.formula||'[POR VERIFICAR]',Meta:x.meta||'[POR VERIFICAR]','Línea base':x.lineaBase||'[POR VERIFICAR]',Unidad:x.unidad||'[POR VERIFICAR]',Periodicidad:x.periodicidad||'[POR VERIFICAR]','Medio de verificación':x.medioVerificacion||'[POR VERIFICAR]',Responsable:x.responsable||'[POR VERIFICAR]',Plazo:x.plazo||'[POR VERIFICAR]',Confirmado:x.confirmed?'Sí':'No'}))}
function scheduleRows(){return rowsFrom(window.fcGetSchedule).map(x=>({ID:x.id,Actividad_ID:x.activityId||'',Actividad:compact(x.activityText||'',28),Texto_original:x.activityText&&compact(x.activityText,28)!==text(x.activityText)?x.activityText:'',Inicio:x.startDate||'[POR VERIFICAR]',Fin:x.endDate||'[POR VERIFICAR]',Duración:x.duration||'',Unidad:x.durationUnit||'',Dependencias:(x.dependencyIds||[]).join(','),Responsable:x.responsible||'[POR VERIFICAR]',Frecuencia:x.frequency||'',Confirmado:x.confirmed?'Sí':'No'}))}
function budgetRows(){return rowsFrom(window.fcGetBudget).map(x=>({ID:x.id,Actividad_ID:x.activityId||'',Actividad:compact(x.activityText||'',28),Tipo_recurso:x.resourceType||'',Recurso:x.description||'[POR VERIFICAR]',Unidad:x.unit||'',Cantidad:x.quantity??'',Frecuencia:x.frequency??'',Costo_unitario:x.unitCost??'[POR VERIFICAR]',Costo_total:x.totalCost??'',Fuente:x.fundingSource||'[POR VERIFICAR]',Tipo_costo:x.costType||'',Confirmado:x.confirmed?'Sí':'No'}))}
function riskRows(){return rowsFrom(window.fcGetRisks).map(x=>({ID:x.id,Tipo_origen:x.linkedObjectType||'',Origen_ID:x.linkedObjectId||'',Origen:compact(x.sourceText||'',30),Causa:compact(x.cause||'[POR VERIFICAR]',30),Evento:compact(x.event||'[POR VERIFICAR]',30),Efecto:compact(x.effect||'[POR VERIFICAR]',30),Probabilidad:x.probability||'',Impacto:x.impact||'',Nivel:x.riskLevel||'',Prevención:compact(x.preventiveResponse||'[POR VERIFICAR]',36),Contingencia:compact(x.contingencyResponse||'[POR VERIFICAR]',36),Responsable:x.owner||'[POR VERIFICAR]',Alerta:x.trigger||'[POR VERIFICAR]',Confirmado:x.confirmed?'Sí':'No'}))}
function sectionRows(code){const s=sections?.[code],d=draft?.[code]||{};return s?s.fields.map(([k,l])=>({Campo:l,Valor:d[k]??'',Estado:String(d[k]??'').trim()?'Registrado':'Vacío'})):[]}
function prepRows(){try{const s=draft?.S05?.vester_preparation||JSON.parse(localStorage.getItem('formulador-cultural-vester-prep-v1')||'{}');return (s.items||[]).map(x=>({ID:x.id,Entrada:x.sourceText||'',Formulación:x.text||'',Estado:x.status||'',Confirmada:x.confirmed?'Sí':'No',Razón:x.reason||''}))}catch{return[]}}
function vesterMatrix(){try{const s=draft?.S06?.vester_state||JSON.parse(localStorage.getItem('formulador-cultural-vester-v1')||'{}'),ps=s.selected||[],r=s.relations||{};if(!ps.length)return[['Matriz Vester'],['Sin variables']];const labels=ps.map((_,i)=>`P${i+1}`),a=[['MATRIZ VESTER',...labels,'Motricidad']];ps.forEach((p,i)=>{let t=0;const row=[labels[i]];ps.forEach(q=>{if(p.id===q.id)row.push('—');else{const v=r[`${p.id}>${q.id}`]?.score;if(Number.isInteger(v))t+=v;row.push(Number.isInteger(v)?v:'')}});row.push(t);a.push(row)});const dep=['Dependencia'];ps.forEach(q=>{let t=0;ps.forEach(p=>{const v=r[`${p.id}>${q.id}`]?.score;if(Number.isInteger(v))t+=v});dep.push(t)});dep.push('');a.push(dep);a.push([]);ps.forEach((p,i)=>a.push([labels[i],p.text]));return a}catch{return[['Matriz Vester'],['Sin datos']]}}
function causalRows(){try{const s=draft?.S06?.causal_validation||JSON.parse(localStorage.getItem('formulador-cultural-causal-validation-v1')||'{}');const vr=(s.variables||[]).map(v=>({Tipo:'Variable',ID:v.id,Elemento:v.text,Decisión:v.status,Rol:v.role,Nota:v.note||'',A_B:'',B_A:''}));const pr=(s.pairs||[]).map(p=>({Tipo:'Relación',ID:p.key,Elemento:`${p.aText} ↔ ${p.bText}`,Decisión:p.decision,Rol:'',Nota:p.note||'',A_B:p.ab,B_A:p.ba}));return [...vr,...pr]}catch{return[]}}
async function evidenceRows(){if(typeof session!=='undefined'&&session&&typeof sb!=='undefined'&&typeof ensureProject==='function'){try{const p=await ensureProject();const {data,error}=await sb.from('evidence').select('title,text,source_kind,source_ref,source_url,source_date,verification_status,notes').eq('project_id',p.id).eq('section_code','S04');if(error)throw error;return (data||[]).map(e=>({Título:e.title||'',Descripción:e.text||'',Tipo:e.source_kind||'',Referencia:e.source_ref||'',URL:e.source_url||'',Fecha:e.source_date||'',Estado:e.verification_status||'',Notas:e.notes||''}))}catch{}}return sectionRows('S04')}
function coherenceRows(){const r=window.fcGetCoherenceReport?.();return r?.checks?.map(x=>({Dimensión:x.dimension,Control:x.label,Estado:x.status,Diagnóstico:x.message}))||[]}
function traceRows(){return rowsFrom(window.fcGetTraceabilityRows)}
async function exportFull(){if(typeof XLSX==='undefined'){alert('No está disponible el generador Excel.');return}if(typeof window.fcPersistCurrent==='function')await window.fcPersistCurrent();const wb=XLSX.utils.book_new();addJson(wb,'01_Identificacion',sectionRows('S01'));addJson(wb,'02_Contexto',sectionRows('S02'));addJson(wb,'03_Poblacion',sectionRows('S03'));addJson(wb,'04_Evidencia',await evidenceRows());addJson(wb,'05_Situaciones',sectionRows('S05'));addJson(wb,'06_Preparacion_Vester',prepRows());addAoa(wb,'07_Matriz_Vester',vesterMatrix());addJson(wb,'08_Validacion_causal',causalRows());addJson(wb,'09_Relaciones_arbol',problemRelations());addJson(wb,'10_Objetivos_detalle',objectivesRows());addJson(wb,'11_Alternativas',alternativesRows());addJson(wb,'12_Resultados_productos',resultsRows());addJson(wb,'13_Actividades',activitiesRows());addJson(wb,'14_Indicadores_metas',indicatorsRows());addJson(wb,'15_Cronograma',scheduleRows());addJson(wb,'16_Presupuesto',budgetRows());addJson(wb,'17_Riesgos',riskRows());addJson(wb,'18_Coherencia',coherenceRows());addJson(wb,'19_Trazabilidad',traceRows());addJson(wb,'20_Reglas',[{Componente:'Evidencia',Regla:'Los vacíos permanecen [POR VERIFICAR].'},{Componente:'Vester',Regla:'La puntuación 0–3 la decide el usuario; el sistema calcula resultados.'},{Componente:'Validación causal',Regla:'Vester orienta; el usuario confirma, reformula o excluye.'},{Componente:'Árbol de problemas',Regla:'La ubicación causal requiere decisión explícita.'},{Componente:'Árbol de objetivos',Regla:'Las reformulaciones positivas deben confirmarse.'},{Componente:'Resultados',Regla:'Cada objetivo específico debe producir al menos un resultado verificable.'},{Componente:'Actividades',Regla:'Toda actividad debe vincularse con un resultado.'},{Componente:'Indicadores',Regla:'Deben mantener meta, línea base, fuente, temporalidad y responsable; datos faltantes quedan [POR VERIFICAR].'},{Componente:'Coherencia',Regla:'El índice solo considera dimensiones evaluables y siempre se acompaña de diagnóstico.'}]);const base=text(draft?.S01?.nombre_del_proyecto||'proyecto-cultural').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'proyecto-cultural';XLSX.writeFile(wb,`${base}-formulacion-completa.xlsx`)}
window.fcExportCompleteWorkbook=exportFull;window.fcExportProjectWorkbook=exportFull;
})();