(()=>{const $=s=>document.querySelector(s);
const stageDefs=[
{n:1,title:'Entender la situación',codes:['S01','S02','S03','S04','S05'],help:'Primero reunimos lo básico: dónde ocurre, a quién afecta, qué sabemos y qué situaciones observamos.'},
{n:2,title:'Encontrar el problema principal',codes:['S06','S07','S08'],help:'Ahora ordenamos relaciones entre situaciones y construimos una explicación clara del problema.'},
{n:3,title:'Definir qué queremos cambiar',codes:['S09'],help:'Transformamos el problema en objetivos claros y posibles.'},
{n:4,title:'Diseñar qué vamos a hacer',codes:['S10','S11','S12'],help:'Elegimos una ruta, definimos resultados, actividades y cómo comprobaremos los avances.'},
{n:5,title:'Revisar el proyecto',codes:[],help:'Al final revisamos si todo está conectado y si faltan datos antes de exportar el proyecto.'}
];
let lastJourneyKey='',lastGuideKey='';
function activeCode(){try{return typeof active!=='undefined'?active:($('#counter')?.textContent||'').slice(0,3)}catch{return ($('#counter')?.textContent||'').slice(0,3)||'S01'}}
function stageFor(code){return stageDefs.find(s=>s.codes.includes(code))||stageDefs[0]}
function navToStage(stage){if(stage.n===5){document.querySelector('#coherencePanel')?.scrollIntoView({behavior:'smooth',block:'start'});return}const code=stage.codes[0];if(code&&window.fcNavigate)window.fcNavigate(code)}
function renderJourney(){document.body.classList.add('guided-mode');const code=activeCode(),cur=stageFor(code),key=code+':'+cur.n;let wrap=$('#guidedJourney');if(!wrap){wrap=document.createElement('section');wrap.id='guidedJourney';wrap.className='guided-journey';$('.nav-wrap')?.insertAdjacentElement('afterend',wrap);lastJourneyKey=''}else{wrap.classList.add('guided-journey')}if(lastJourneyKey===key)return;lastJourneyKey=key;const curIdx=Math.max(0,stageDefs.findIndex(s=>s.n===cur.n));wrap.innerHTML='<div class="guided-journey-head"><div><strong>Tu recorrido</strong><p>Avanza una decisión a la vez. El detalle técnico se guarda por debajo.</p></div><button class="guided-review-btn" type="button">Revisar lo que llevo</button></div><div class="guided-steps">'+stageDefs.map((s,i)=>'<button type="button" class="guided-step '+(s.n===cur.n?'current':i<curIdx?'done':i>curIdx+1?'locked':'')+'" data-stage="'+s.n+'"><span>Paso '+s.n+'</span><b>'+s.title+'</b></button>').join('')+'</div>';wrap.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>navToStage(stageDefs.find(s=>String(s.n)===b.dataset.stage)));wrap.querySelector('.guided-review-btn').onclick=()=>navToStage(stageDefs[4])}
function renderSectionGuide(){const code=activeCode(),fields=$('#fields');if(!fields)return;const s=stageFor(code),key=code+':'+s.n;if(lastGuideKey===key&&fields.querySelector('.guided-section-note'))return;fields.querySelector('.guided-section-note')?.remove();const note=document.createElement('div');note.className='guided-section-note';note.innerHTML='<strong>Paso '+s.n+' · '+s.title+'</strong><p>'+s.help+'</p>';fields.prepend(note);lastGuideKey=key}
function simplifyVester(){const root=$('#vesterWizard');if(!root)return;const top=root.querySelector('.vester-top h3');if(top)top.textContent='Comparar situaciones';const p=root.querySelector('.vester-top p');if(p)p.textContent='Te mostraremos dos situaciones cada vez. Decide si una puede provocar cambios en la otra. El sistema hará los cálculos por detrás.';const core=root.querySelector('.vester-core-question');if(core){core.textContent='¿La primera situación puede provocar un cambio en la segunda?';if(!root.querySelector('.guided-vester-hint')){const h=document.createElement('div');h.className='guided-vester-hint';h.innerHTML='<strong>Cómo responder</strong><p>Piensa en el orden: si la primera situación cambiara, ¿la segunda cambiaría también? Si solo ocurren al mismo tiempo, elige “No cambia”.</p>';core.insertAdjacentElement('afterend',h)}}const labels=['No cambia','Cambia poco','Cambia bastante','Cambia mucho'];root.querySelectorAll('[data-score]').forEach(b=>{const sp=b.querySelector('span');if(sp)sp.textContent=labels[Number(b.dataset.score)]||sp.textContent});const just=root.querySelector('.vester-just textarea');if(just)just.placeholder='Una frase corta es suficiente. También puedes dejarlo vacío.';const assist=root.querySelector('.vester-actions');if(assist&&!assist.querySelector('.guided-help-toggle')){const b=document.createElement('button');b.type='button';b.className='guided-help-toggle';b.textContent='Necesito ayuda';b.onclick=()=>root.querySelector('[data-help="easy"]')?.click();assist.appendChild(b)}}
let scheduled=false;function mount(){scheduled=false;renderJourney();renderSectionGuide();simplifyVester()}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(mount)}
new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true});schedule();})();