(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const KEY='formulador-cultural-objectives-v1';
const TREE_KEY='formulador-cultural-problem-tree-v1';
const MAP={central:'Objetivo central',direct_cause:'Medio directo',indirect_cause:'Medio indirecto',direct_effect:'Fin directo',indirect_effect:'Fin indirecto'};
let state={items:[],sourceSignature:'',updatedAt:null};
function readTree(){try{return draft?.S07?.tree_state||JSON.parse(localStorage.getItem(TREE_KEY)||'{}')}catch{return {}}}
function sourceNodes(){return (readTree()?.nodes||[]).filter(n=>MAP[n.zone]).map(n=>({id:n.id,text:n.text,zone:n.zone,parentId:n.parentId||null}))}
function signature(){return sourceNodes().map(n=>`${n.id}:${n.zone}:${n.text}:${n.parentId||''}`).join('|')}
function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{};const cloud=typeof draft!=='undefined'?draft?.S09?.objectives_state:null;if(cloud){const lt=Date.parse(state.updatedAt||0)||0,ct=Date.parse(cloud.updatedAt||0)||0;if(!state.items.length||ct>=lt)state={...state,...cloud}}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));if(typeof draft!=='undefined'){draft.S09=draft.S09||{};draft.S09.objectives_state=state;draft.S09.objetivo_central=state.items.find(x=>x.zone==='central')?.text||'';draft.S09.medios_directos=state.items.filter(x=>x.zone==='direct_cause').map(x=>x.text).join('\n');draft.S09.medios_indirectos=state.items.filter(x=>x.zone==='indirect_cause').map(x=>x.text).join('\n');draft.S09.fines_directos=state.items.filter(x=>x.zone==='direct_effect').map(x=>x.text).join('\n');draft.S09.fines_indirectos=state.items.filter(x=>x.zone==='indirect_effect').map(x=>x.text).join('\n');localStorage.setItem(storeKey,JSON.stringify(draft))}}
function cleanProblemText(text){return String(text||'').replace(/^\s*\d+[.)-]?\s*/,'').replace(/^\s*P\d+\s*/i,'').replace(/^\s*\[POR REVISAR\]\s*/i,'').replace(/^\s*Situación deseada respecto de:\s*/i,'').replace(/\s+/g,' ').trim()}
function objectiveProposals(text,zone){
 const t=cleanProblemText(text);if(!t)return ['[POR VERIFICAR]'];const out=[];
 if(/^diferencias?\b/i.test(t)){out.push(t.replace(/^diferencias?\b/i,'Reducir las diferencias'));out.push(t.replace(/^diferencias?\b/i,'Lograr niveles más equilibrados en'));}
 else if(/^frecuencia desigual\b/i.test(t)){out.push(t.replace(/^frecuencia desigual\b/i,'Equilibrar la frecuencia'));out.push(t.replace(/^frecuencia desigual\b/i,'Lograr una frecuencia más equilibrada'));}
 else{let s=t,changed=false;const rules=[[/^falta de\s+/i,'Aumentar la disponibilidad de '],[/^ausencia de\s+/i,'Contar con '],[/^carencia de\s+/i,'Fortalecer la disponibilidad de '],[/\bbaja\b/ig,'mayor'],[/\bbajo\b/ig,'mayor'],[/\brestringid[oa]s?\b/ig,'ampliado'],[/\brestricción de\b/ig,'ampliación de'],[/\blimitad[oa]s?\b/ig,'ampliado'],[/\blimitaciones?\b/ig,'fortalecimiento'],[/\binsuficientes?\b/ig,'adecuadas'],[/\bdificultades? en\b/ig,'mejorar'],[/\bafectación de\b/ig,'mejora de'],[/\bfiltración sonora\b/ig,'reducción de la filtración sonora']];for(const [re,r] of rules){if(re.test(s)){s=s.replace(re,r);changed=true}}if(changed)out.push(s.charAt(0).toUpperCase()+s.slice(1));}
 if(!out.length)out.push(zone==='central'?`Mejorar la situación asociada a: ${t}.`:`Fortalecer la condición relacionada con: ${t}.`);
 return [...new Set(out)].slice(0,3)
}
function suggest(text,zone){return objectiveProposals(text,zone)[0]}
function refreshFromTree(force=false){const src=sourceNodes(),sig=signature();if(!state.items.length||force){const old=new Map(state.items.map(x=>[x.id,x]));state.items=src.map(n=>{const prev=old.get(n.id);return prev&&prev.sourceText===n.text?{...prev,zone:n.zone,parentId:n.parentId}:{id:n.id,zone:n.zone,parentId:n.parentId,sourceText:n.text,text:suggest(n.text,n.zone),confirmed:false}});state.sourceSignature=sig;save()}return sig}
function changed(){return !!state.sourceSignature&&state.sourceSignature!==signature()}
function counts(){return {central:state.items.filter(x=>x.zone==='central').length,means:state.items.filter(x=>x.zone==='direct_cause'||x.zone==='indirect_cause').length,ends:state.items.filter(x=>x.zone==='direct_effect'||x.zone==='indirect_effect').length,pending:state.items.filter(x=>!x.confirmed).length}}
function listHtml(){if(!state.items.length)return '<div class="objectives-warning"><strong>S07 no contiene un árbol utilizable.</strong><p>Define al menos el problema central y sus relaciones antes de construir S09.</p></div>';return `<div class="objective-list">${state.items.map(x=>`<article class="objective-card" data-obj="${x.id}"><header><div><strong>${esc(MAP[x.zone])}</strong><div class="objective-source">Problema de origen: ${esc(cleanProblemText(x.sourceText))}</div></div><span class="objective-status ${x.confirmed?'confirmed':'pending'}">${x.confirmed?'Confirmado':'Por revisar'}</span></header><div class="objective-question">¿Cómo debería verse esta situación si el proyecto logra mejorarla?</div><textarea data-obj-text="${x.id}">${esc(x.text)}</textarea><div class="objective-proposals">${objectiveProposals(x.sourceText,x.zone).map((p,i)=>`<article><small>Propuesta ${i+1}</small><p>${esc(p)}</p><button type="button" data-use-objective="${x.id}:${i}">Usar esta propuesta</button></article>`).join('')}</div><div class="objective-actions"><button type="button" data-suggest="${x.id}">Proponer reformulación</button><button type="button" data-confirm="${x.id}" class="primary">${x.confirmed?'Actualizar confirmación':'Confirmar formulación'}</button></div></article>`).join('')}</div>`}
function diagramHtml(){const order=['indirect_effect','direct_effect','central','direct_cause','indirect_cause'];return `<div class="objective-diagram">${order.map((z,i)=>{const xs=state.items.filter(x=>x.zone===z);return `<section class="objective-level"><h4>${esc(MAP[z])}</h4><div class="objective-level-grid">${xs.length?xs.map(x=>`<div class="objective-node ${z==='central'?'central':''}"><strong>${esc(x.text)}</strong><div class="objective-source">${x.confirmed?'Confirmado':'[POR REVISAR]'}</div></div>`).join(''):'<div class="objective-source">Sin elementos</div>'}</div></section>${i<order.length-1?'<div class="objective-arrow">↑</div>':''}`}).join('')}</div>`}
function render(){const host=$('#objectivesBody');if(!host)return;const c=counts();host.innerHTML=`${changed()?'<div class="objectives-warning"><strong>S07 cambió después de iniciar S09.</strong><p>Puedes conservar tus formulaciones o reconstruir las propuestas desde el árbol actualizado.</p><button type="button" id="refreshObjectives">Actualizar desde S07</button></div>':''}<div class="objectives-note"><strong>Regla metodológica</strong><p>S09 transforma situaciones negativas del árbol de problemas en estados positivos deseados. Las propuestas automáticas son borradores; el usuario confirma la redacción final.</p></div><div class="objectives-summary"><div><span>Objetivo central</span><strong>${c.central}</strong></div><div><span>Medios</span><strong>${c.means}</strong></div><div><span>Fines</span><strong>${c.ends}</strong></div><div><span>Por revisar</span><strong>${c.pending}</strong></div></div><div class="objectives-toolbar"><button type="button" id="showObjectiveList" class="primary">Revisar formulaciones</button><button type="button" id="showObjectiveDiagram">Ver árbol de objetivos</button><button type="button" id="saveObjectives">Guardar S09</button><button type="button" id="exportObjectivesWorkbook">Generar Excel completo</button></div><div class="objectives-note"><strong>Excel completo</strong><p>La exportación reúne S01–S09, evidencia, preparación y matriz Vester, resultados, árbol de problemas, árbol de objetivos, relaciones y trazabilidad. Se genera localmente en tu navegador.</p></div><div id="objectivesContent">${listHtml()}</div>`;
$('#refreshObjectives')?.addEventListener('click',()=>{if(confirm('Se reconstruirán las propuestas desde S07. Las formulaciones confirmadas solo se conservarán cuando el texto fuente no haya cambiado. ¿Continuar?')){refreshFromTree(true);render()}});
$('#showObjectiveList').onclick=()=>{$('#objectivesContent').innerHTML=listHtml();bindItems()};
$('#showObjectiveDiagram').onclick=()=>{$('#objectivesContent').innerHTML=diagramHtml()};
$('#saveObjectives').onclick=async()=>{save();if(typeof session!=='undefined'&&session&&typeof syncSection==='function'){try{await syncSection('S09');if(typeof setStatus==='function')setStatus('S09 guardada y sincronizada en la nube.',true)}catch(e){if(typeof setStatus==='function')setStatus(`S09 guardada localmente. Error de sincronización: ${e.message||'desconocido'}`)}}else if(typeof setStatus==='function')setStatus('S09 guardada localmente. Inicia sesión para sincronizar.')};
$('#exportObjectivesWorkbook').onclick=async()=>{const btn=$('#exportObjectivesWorkbook');const old=btn.textContent;btn.disabled=true;btn.textContent='Generando Excel…';try{save();if(typeof window.fcExportCompleteWorkbook!=='function')throw new Error('El módulo de exportación no está disponible.');await window.fcExportCompleteWorkbook()}catch(e){console.error(e);alert(`No fue posible generar el Excel: ${e.message||'error desconocido'}`)}finally{btn.disabled=false;btn.textContent=old}};
bindItems()}
function bindItems(){document.querySelectorAll('[data-use-objective]').forEach(b=>b.onclick=()=>{const [id,idx]=b.dataset.useObjective.split(':');const item=state.items.find(x=>x.id===id);if(!item)return;item.text=objectiveProposals(item.sourceText,item.zone)[Number(idx)]||item.text;item.confirmed=false;save();render()});document.querySelectorAll('[data-suggest]').forEach(b=>b.onclick=()=>{const item=state.items.find(x=>x.id===b.dataset.suggest);if(!item)return;item.text=suggest(item.sourceText,item.zone);item.confirmed=false;save();render()});document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>{const item=state.items.find(x=>x.id===b.dataset.confirm),ta=document.querySelector(`[data-obj-text="${b.dataset.confirm}"]`);if(!item||!ta)return;item.text=ta.value.trim();if(!item.text||/\[POR REVISAR\]/i.test(item.text)){item.confirmed=false;alert('Antes de confirmar, elige o escribe una formulación limpia, sin [POR REVISAR].');save();render();return}item.confirmed=true;save();render()});document.querySelectorAll('[data-obj-text]').forEach(ta=>ta.oninput=()=>{const item=state.items.find(x=>x.id===ta.dataset.objText);if(item){item.confirmed=false;item.text=ta.value}})}
function mount(){const counter=$('#counter'),fields=$('#fields');if(!counter||!fields||!counter.textContent.startsWith('S09'))return;if($('#objectivesWizard'))return;load();refreshFromTree(false);fields.innerHTML='<section id="objectivesWizard" class="objectives-wizard"><span class="objectives-mode">Árbol de objetivos</span><h3>Transformar el árbol de problemas en estados positivos deseados</h3><p>El sistema recupera S07 y propone reformulaciones. Ninguna se confirma automáticamente.</p><div id="objectivesBody"></div></section>';render()}
const obs=new MutationObserver(mount);obs.observe(document.body,{subtree:true,childList:true});mount();
})();