(()=>{
let evidenceRequested=false;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function arr(fn){try{return fn?.()||[]}catch{return []}}
function pct(a,b){return b?Math.round(a/b*100):0}
function money(v){return new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v)||0)}
function snapshot(){
 const codes=Array.from({length:15},(_,i)=>'S'+String(i+1).padStart(2,'0')),states=codes.map(c=>({code:c,status:window.fcSectionStatus?.(c)||'missing'}));
 const complete=states.filter(x=>x.status==='complete').length,progress=states.filter(x=>x.status==='progress').length,missing=states.filter(x=>x.status==='missing').length;
 const res=arr(window.fcGetResults).filter(x=>x.confirmed),acts=arr(window.fcGetActivities).filter(x=>x.confirmed),inds=arr(window.fcGetIndicators),sch=arr(window.fcGetSchedule),bud=arr(window.fcGetBudget),risks=arr(window.fcGetRisks),ev=arr(window.fcGetEvidenceRecords),bs=window.fcGetBudgetSummary?.()||{},coh=window.fcGetCoherenceReport?.()||{score:0,checks:[]};
 const obj=(draft?.S09?.objectives_state?.items||[]).filter(x=>x.confirmed&&(x.zone==='direct_cause'||x.zone==='indirect_cause'));
 const resObj=new Set(res.map(x=>x.objectiveId)),actRes=new Set(acts.map(x=>x.resultId)),indAct=new Set(inds.filter(x=>x.confirmed).map(x=>x.activityId)),schAct=new Set(sch.filter(x=>x.confirmed).map(x=>x.activityId)),bsState=window.fcGetBudgetState?.()||{},coveredBudget=new Set(Object.entries(bsState.activityStatus||{}).filter(([,v])=>v&&v!=='pending').map(([k])=>k));
 const riskCounts={Alto:risks.filter(x=>x.riskLevel==='Alto').length,Medio:risks.filter(x=>x.riskLevel==='Medio').length,Bajo:risks.filter(x=>x.riskLevel==='Bajo').length};
 const highOpen=risks.filter(x=>x.riskLevel==='Alto'&&!x.confirmed).length;
 const fieldLabels={formula:'Fórmula o criterio',unidad:'Unidad',lineaBase:'Línea base',meta:'Meta',medioVerificacion:'Medio de verificación',periodicidad:'Periodicidad',responsable:'Responsable',plazo:'Plazo'};
 const missingValue=v=>!String(v||'').trim()||/\[POR (VERIFICAR|REVISAR|DEFINIR)\]/i.test(String(v||''));
 const indicatorPending=inds.map(x=>{
  const missing=[];
  if(!x.confirmed||x.definitionStatus==='PENDIENTE'||missingValue(x.indicator))missing.push('Definición del indicador');
  if(x.confirmed)for(const k of Object.keys(fieldLabels))if(missingValue(x[k]))missing.push(fieldLabels[k]);
  const scheduleSuggestions=Object.entries(x.scheduleReconciliation?.fields||{}).filter(([k,v])=>missing.includes(fieldLabels[k])&&v?.value).map(([k,v])=>({field:fieldLabels[k],value:v.value,source:v.source}));
  return {id:x.id||x.indicatorId,label:(x.indicator&&!missingValue(x.indicator)?x.indicator:(x.linkedType||'Indicador')+' · '+(x.linkedText||x.activityText||'')),linkedType:x.linkedType||'',linkedText:x.linkedText||x.activityText||'',missing,scheduleSuggestions}
 }).filter(x=>x.missing.length);
 const undefinedIndicators=indicatorPending.filter(x=>x.missing.includes('Definición del indicador')).length;
 const incompleteIndicators=indicatorPending.filter(x=>!x.missing.includes('Definición del indicador')).length;
 const orphanResultItems=res.filter(r=>!acts.some(a=>a.resultId===r.id)).map(r=>({id:r.id,text:r.text,objectiveText:r.objectiveText||''}));
 const orphanResults=orphanResultItems.length;
 const ready=complete===codes.length&&coh.score>=80&&highOpen===0;
 const evidence={verified:ev.filter(x=>x.verification_status==='verificada').length,pending:ev.filter(x=>x.verification_status==='por_verificar').length,discarded:ev.filter(x=>x.verification_status==='descartada').length,total:ev.length};return {states,complete,progress,missing,completion:pct(complete,codes.length),res,acts,inds,sch,bud,risks,bs,coh,obj,riskCounts,evidence,highOpen,undefinedIndicators,incompleteIndicators,indicatorPending,orphanResults,orphanResultItems,ready,coverage:[
  ['Objetivos con resultados',pct(obj.filter(x=>resObj.has(x.id)).length,obj.length)],
  ['Resultados con actividades',pct(res.filter(x=>actRes.has(x.id)).length,res.length)],
  ['Actividades con indicadores',pct(acts.filter(x=>indAct.has(x.id)).length,acts.length)],
  ['Actividades programadas',pct(acts.filter(x=>schAct.has(x.id)).length,acts.length)],
  ['Actividades con tratamiento financiero',pct(acts.filter(x=>coveredBudget.has(x.id)).length,acts.length)]
 ]};
}
function bar(label,value){return '<div class="dash-bar"><div><span>'+esc(label)+'</span><b>'+value+'%</b></div><div class="bar-track"><i style="width:'+Math.max(0,Math.min(100,value))+'%"></i></div></div>'}
function render(){
 const c=$('#counter')?.textContent||'';if(!c.startsWith('S16'))return;const host=$('#fields');if(!host)return;const s=snapshot(),rv=draft?.S16?.review_state||{};
 if(!evidenceRequested&&s.evidence.total===0&&typeof window.fcLoadEvidenceRecords==='function'){evidenceRequested=true;window.fcLoadEvidenceRecords().then(()=>render()).catch(()=>{})}
 host.innerHTML='<section class="review-dashboard"><div class="review-hero '+(s.ready?'ready':'review')+'"><div><strong>'+(s.ready?'Proyecto listo para presentar':'Proyecto en revisión')+'</strong><p>'+(s.ready?'La cadena principal está conectada. Revisa los datos marcados [POR VERIFICAR] antes de cada convocatoria.':'Todavía hay secciones o relaciones que conviene completar antes de presentar.')+'</p></div><div class="big-score">'+s.completion+'%</div></div>'+
 '<div class="dash-grid"><article><h3>Avance de formulación</h3>'+bar('Secciones completas',s.completion)+bar('Coherencia interna',s.coh.score)+'<p><b>'+s.complete+'</b> completas · <b>'+s.progress+'</b> en curso · <b>'+s.missing+'</b> faltan</p></article>'+
 '<article><h3>Cadena lógica</h3>'+s.coverage.map(x=>bar(x[0],x[1])).join('')+'</article>'+
 '<article><h3>Evidencia</h3><div class="risk-metrics"><span>Verificada <b>'+s.evidence.verified+'</b></span><span>Por verificar <b>'+s.evidence.pending+'</b></span><span>Descartada <b>'+s.evidence.discarded+'</b></span></div><p>'+(s.evidence.total?'Registros estructurados disponibles.':'Abre S04 para cargar el registro estructurado en esta sesión.')+'</p></article><article><h3>Presupuesto</h3><div class="metric"><span>Total valorizado</span><strong>'+money(s.bs.total)+'</strong></div><div class="metric"><span>Monetario</span><strong>'+money(s.bs.monetary)+'</strong></div><div class="metric"><span>Aporte en especie</span><strong>'+money(s.bs.inKind)+'</strong></div></article>'+
 '<article><h3>Riesgos</h3><div class="risk-metrics"><span>Altos <b>'+s.riskCounts.Alto+'</b></span><span>Medios <b>'+s.riskCounts.Medio+'</b></span><span>Bajos <b>'+s.riskCounts.Bajo+'</b></span></div><p>'+(s.highOpen?'<b>'+s.highOpen+'</b> riesgo(s) alto(s) requieren respuesta.':'No hay riesgos altos sin respuesta confirmada.')+'</p></article></div>'+
 '<section class="review-actions"><h3>Pendientes concretos</h3><p>Se muestran únicamente elementos que todavía requieren una decisión o un dato.</p><div class="review-action-grid">'+
 s.indicatorPending.map(x=>'<article class="review-pending-card"><div><small>'+esc(x.linkedType||'Indicador')+'</small><b>'+esc(x.label)+'</b><p>Falta: '+esc(x.missing.join(' · '))+'</p>'+(x.scheduleSuggestions.length?'<p class="pending-source">Ya existe una propuesta desde el cronograma para: '+esc(x.scheduleSuggestions.map(v=>v.field).join(', '))+'.</p>':'')+'</div><button type="button" data-focus-indicator="'+esc(x.id)+'">Abrir este indicador</button></article>').join('')+
 s.orphanResultItems.map(r=>'<article class="review-pending-card"><div><small>Resultado sin actividades</small><b>'+esc(r.text)+'</b><p>Falta al menos una actividad vinculada a este resultado.</p></div><button type="button" data-focus-result="'+esc(r.id)+'">Revisar este resultado</button></article>').join('')+
 ((!s.indicatorPending.length&&!s.orphanResultItems.length)?'<p>No hay pendientes concretos en indicadores ni en la relación resultados → actividades.</p>':'')+
 '</div></section>'+
 '<details><summary>Otras secciones que siguen en curso</summary><div class="review-list">'+s.states.filter(x=>x.status!=='complete'&&!['S11','S12'].includes(x.code)).map(x=>'<button data-jump="'+x.code+'"><b>'+x.code+'</b><span>'+(x.status==='progress'?'En curso':'Falta')+'</span></button>').join('')+(s.states.filter(x=>x.status!=='complete'&&!['S11','S12'].includes(x.code)).length===0?'<p>No hay otras secciones pendientes.</p>':'')+'</div></details>'+
 '<details><summary>Diagnóstico de coherencia</summary><div class="coh-review">'+(s.coh.checks||[]).map(x=>'<article><b>'+esc(x.label)+'</b><p>'+esc(x.message)+'</p></article>').join('')+'</div></details>'+
 '<section class="exports"><h3>Documentos y exportaciones</h3><p>El documento final reúne la formulación conceptual, operativa, temporal, financiera y de riesgos.</p><div class="export-grid"><button id="expDocx">Documento editable (DOCX)</button><button id="expPdf">Documento formal (PDF)</button><button id="expHtml">Abrir/guardar en navegador (HTML)</button><button id="expXlsx">Respaldo técnico (Excel)</button><button id="expProblemSvg">Árbol de problemas (SVG)</button><button id="expObjectiveSvg">Árbol de objetivos (SVG)</button></div></section>'+
 '<div class="final-confirm"><label><input id="confirmReview" type="checkbox" '+(rv.confirmed?'checked':'')+'> Revisé el diagnóstico y entiendo los datos pendientes.</label><button id="saveReview" class="primary">Guardar revisión final</button></div></section>';
 host.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>window.fcNavigate?.(b.dataset.jump));
 host.querySelectorAll('[data-focus-indicator]').forEach(b=>b.onclick=()=>window.fcFocusIndicator?.(b.dataset.focusIndicator,{openCompletion:true}));
 host.querySelectorAll('[data-focus-result]').forEach(b=>b.onclick=()=>window.fcFocusResultActivities?.(b.dataset.focusResult));
 $('#expDocx').onclick=()=>window.fcExportProjectDOCX?.();$('#expPdf').onclick=()=>window.fcExportProjectPDF?.();$('#expHtml').onclick=()=>window.fcExportProjectHTML?.();$('#expXlsx').onclick=()=>window.fcExportCompleteWorkbook?.();$('#expProblemSvg').onclick=()=>window.fcExportProblemTreeSVG?.();$('#expObjectiveSvg').onclick=()=>window.fcExportObjectiveTreeSVG?.();
 $('#saveReview').onclick=()=>{draft.S16=draft.S16||{};draft.S16.review_state={confirmed:$('#confirmReview').checked,ready:s.ready,completion:s.completion,coherence:s.coh.score,updatedAt:new Date().toISOString()};localStorage.setItem(storeKey,JSON.stringify(draft));try{if(session)syncSection('S16')}catch{};window.fcRenderJourney?.();render()}
}
window.fcGetReviewSnapshot=snapshot;
const style=document.createElement('style');style.textContent='.review-dashboard{display:grid;gap:14px}.review-hero{display:flex;justify-content:space-between;gap:15px;align-items:center;border:2px solid var(--ink);border-radius:14px;padding:15px}.review-hero.ready{background:#eef9f1;border-color:#37a85b}.review-hero.review{background:#fff8df;border-color:#d5b446}.review-hero p{margin:5px 0}.big-score{font-size:2rem;font-weight:850}.dash-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.dash-grid article,.exports,.final-confirm,.review-dashboard details,.review-actions{border:1px solid var(--line);border-radius:12px;padding:12px;background:#fff}.review-actions h3{margin:0 0 8px}.review-action-grid{display:grid;gap:8px}.review-action-grid button{display:grid;gap:3px;text-align:left;border:1px solid #b9d9c8;background:#f5fbf7;border-radius:10px;padding:10px 12px;font:inherit;color:#173d2c}.review-action-grid button span{color:var(--muted);font-size:.84rem}.review-pending-card{display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center;border:1px solid #dbe6df;background:#fff;border-radius:11px;padding:11px}.review-pending-card small{display:block;color:var(--muted);font-weight:800;margin-bottom:3px}.review-pending-card p{margin:5px 0;color:var(--muted)}.review-pending-card .pending-source{color:#245e44}.review-pending-card button{align-self:center;white-space:nowrap}.dash-grid h3,.exports h3{margin:0 0 10px}.dash-bar{margin:9px 0}.dash-bar>div:first-child{display:flex;justify-content:space-between;font-size:.84rem}.bar-track{height:8px;background:#edf0f3;border-radius:999px;overflow:hidden;margin-top:4px}.bar-track i{display:block;height:100%;background:#52606d}.metric,.risk-metrics span{display:flex;justify-content:space-between;gap:8px;border-top:1px solid var(--line);padding:8px 0}.risk-metrics{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.risk-metrics span{display:block;border:1px solid var(--line);border-radius:8px;padding:8px}.review-list{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.review-list button{display:flex;justify-content:space-between;border:1px solid var(--line);background:#fff;border-radius:9px;padding:9px;font:inherit}.coh-review article{border-top:1px solid var(--line);padding:8px 0}.coh-review p{margin:4px 0;color:var(--muted)}.export-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.export-grid button,.final-confirm button{border:1px solid #aeb8c2;background:#fff;border-radius:9px;padding:10px;font:inherit}.final-confirm{display:flex;justify-content:space-between;gap:10px;align-items:center}.final-confirm .primary{background:var(--ink);color:#fff;border-color:var(--ink)}@media(max-width:760px){.dash-grid,.review-list,.export-grid{grid-template-columns:1fr}.final-confirm,.review-hero,.review-pending-card{display:grid;grid-template-columns:1fr}.risk-metrics{grid-template-columns:1fr}}';document.head.appendChild(style);
function mount(){const c=$('#counter')?.textContent||'';if(c.startsWith('S16')&&!$('#fields .review-dashboard'))render()}new MutationObserver(mount).observe(document.body,{subtree:true,childList:true});mount();
})();