(()=>{
if(typeof sections==='undefined'||typeof order==='undefined')return;
if(!sections.S09)sections.S09={title:'Árbol de objetivos',question:'¿Qué queremos cambiar y cómo se vería la situación mejorada?',meaning:'Transforma el árbol de problemas en objetivos y condiciones deseadas. La herramienta propone; tú revisas y confirmas.',fields:[['objetivo_central','Objetivo central',1],['medios_directos','Medios directos'],['medios_indirectos','Medios indirectos'],['fines_directos','Fines directos'],['fines_indirectos','Fines indirectos']]};
else{sections.S09.question='¿Qué queremos cambiar y cómo se vería la situación mejorada?';sections.S09.meaning='Transforma el árbol de problemas en objetivos y condiciones deseadas. La herramienta propone; tú revisas y confirmas.'}
if(!sections.S10)sections.S10={title:'Elegir la mejor alternativa',question:'¿Cuál camino de trabajo parece más adecuado para lograr los objetivos?',meaning:'Compara opciones de intervención de forma sencilla y elige una. La herramienta orienta; la decisión final es tuya.',fields:[['alternativa_seleccionada','Alternativa seleccionada',1],['criterios','Criterios de valoración'],['justificacion_seleccion','Justificación de la selección']]};
else{sections.S10.title='Elegir la mejor alternativa';sections.S10.question='¿Cuál camino de trabajo parece más adecuado para lograr los objetivos?';sections.S10.meaning='Compara opciones de intervención de forma sencilla y elige una. La herramienta orienta; la decisión final es tuya.'}
if(!sections.S11)sections.S11={title:'Resultados y actividades',question:'¿Qué debe quedar logrado y qué debemos hacer para conseguirlo?',meaning:'Primero define un resultado verificable. Después organiza las actividades necesarias para producirlo.',fields:[['resultados_productos','Resultados o productos',1],['actividades_confirmadas','Actividades confirmadas',1],['observaciones_actividades','Observaciones']]};
else{sections.S11.title='Resultados y actividades';sections.S11.question='¿Qué debe quedar logrado y qué debemos hacer para conseguirlo?';sections.S11.meaning='Primero define un resultado verificable. Después organiza las actividades necesarias para producirlo.';sections.S11.fields=[['resultados_productos','Resultados o productos',1],['actividades_confirmadas','Actividades confirmadas',1],['observaciones_actividades','Observaciones']]}
if(!sections.S12)sections.S12={title:'Cómo vamos a comprobar los avances',question:'¿Cómo sabremos si las actividades y resultados se cumplieron?',meaning:'Define indicadores, metas y fuentes de verificación. Si falta una cifra o dato, déjalo [POR VERIFICAR].',fields:[['indicadores_confirmados','Indicadores confirmados',1],['metas_confirmadas','Metas confirmadas'],['medios_verificacion','Medios de verificación']]};
else{sections.S12.title='Cómo vamos a comprobar los avances';sections.S12.question='¿Cómo sabremos si las actividades y resultados se cumplieron?';sections.S12.meaning='Define indicadores, metas y fuentes de verificación. Si falta una cifra o dato, déjalo [POR VERIFICAR].'}
if(!sections.S13)sections.S13={title:'Cronograma',question:'¿Cuándo haremos cada actividad y en qué orden?',meaning:'Organiza las actividades en el tiempo. La herramienta calcula fechas y revisa dependencias.',fields:[['cronograma_resumen','Cronograma resumido']]};
if(!sections.S14)sections.S14={title:'Recursos y presupuesto',question:'¿Qué necesita cada actividad y cuánto cuesta?',meaning:'El presupuesto nace de las actividades. Registra recursos, cantidades, unidades y costos sin inventar valores.',fields:[['presupuesto_resumen','Presupuesto resumido']]};
if(!sections.S15)sections.S15={title:'Riesgos',question:'¿Qué podría dificultar el proyecto y cómo nos prepararíamos?',meaning:'Diferencia problemas existentes de situaciones futuras que podrían afectar actividades, resultados u objetivos.',fields:[['riesgos_resumen','Riesgos resumidos']]};
if(!sections.S16)sections.S16={title:'Revisión y entrega',question:'¿El proyecto está conectado y listo para presentar?',meaning:'Revisa coherencia, pendientes, gráficas y genera los documentos finales.',fields:[['revision_final','Revisión final']]};
['S09','S10','S11','S12','S13','S14','S15','S16'].forEach(code=>{if(!order.includes(code))order.push(code)});
const boot=localStorage.getItem('fc_boot_target');if(boot&&order.includes(boot)){active=boot;localStorage.removeItem('fc_boot_target')}
if(typeof render==='function')render();
})();