(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const TREE_KEY='formulador-cultural-problem-tree-v1';
const ZONES=['outside','central','direct_cause','indirect_cause','direct_effect','indirect_effect'];
const LABELS={outside:'Fuera del árbol',central:'Problema central',direct_cause:'Causa directa',indirect_cause:'Causa indirecta',direct_effect:'Efecto directo',indirect_effect:'Efecto indirecto'};
let mounted=false,s05Warned=false;

function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return 'p'+(h>>>0).toString(36)}
function normalizeProblem(line){return line.trim().replace(/^([\-•*]|\d+[.)]|[A-Za-z][.)])\s*/,'').trim()}
function s05Problems(){const raw=(typeof draft!=='undefined'&&draft.S05?.situaciones_observables)||'';return [...new Map(String(raw).split(/\n+/).map(normalizeProblem).filter(Boolean).map(t=>[t.toLowerCase(),t])).values()].map(text=>({id:hashText(text),text}))}
function s05Signature(){return s05Problems().map(p=>`${p.id}:${p.text}`).join('|')}
function defaultState(){return {nodes:[],phase:'intro',sourceSignature:'',reviewed:{},updatedAt:null}}
function loadState(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(TREE_KEY)||'{}')}}catch{return defaultState()}}
let state=loadState();
function syncFromDraft(){if(typeof draft!=='undefined'&&draft.S07?.tree_state){state={...defaultState(),...draft.S07.tree_state};localStorage.setItem(TREE_KEY,JSON.stringify(state))}}
function saveState(){state.updatedAt=new Date().toISOString();localStorage.setItem(TREE_KEY,JSON.stringify(state));if(typeof draft!=='undefined'){draft.S07=draft.S07||{};draft.S07.tree_state=state;localStorage.setItem(storeKey,JSON.stringify(draft))}}
function centralNode(){return state.nodes.find(n=>n.zone==='central')||null}
function nodesIn(zone){return state.nodes.filter(n=>n.zone===zone)}
function currentS05Changed(){return !!state.sourceSignature&&state.sourceSignature!==s05Signature()}
function importFromS05(force=false){const incoming=s05Problems();if(!state.nodes.length){state.nodes=incoming.map(p=>({...p,zone:'outside',justification:'',parentId:null,reviewed:false,origin:'S05'}));state.sourceSignature=s05Signature();saveState();return}
  if(!force)return;
  const byId=new Map(state.nodes.map(n=>[n.id,n]));incoming.forEach(p=>{if(!byId.has(p.id))state.nodes.push({...p,zone:'outside',justification:'',parentId:null,reviewed:false,origin:'S05'});else{const n=byId.get(p.id);n.text=p.text;n.stale=false}});
  const incomingIds=new Set(incoming.map(p=>p.id));state.nodes.forEach(n=>{if(n.origin==='S05'&&!incomingIds.has(n.id))n.stale=true});
  state.sourceSignature=s05Signature();saveState();
}
function vesterSummary(){const vs=(typeof draft!=='undefined'&&draft.S06?.vester_state)||null;if(!vs?.selected?.length)return new Map();const totals=new Map(vs.selected.map(p=>[p.id,{text:p.text,influence:0,dependence:0}]));const ps=vs.selected;for(let i=0;i<ps.length;i++)for(let j=0;j<ps.length;j++){if(i===j)continue;const r=vs.relations?.[`${ps[i].id}>${ps[j].id}`];if(Number.isInteger(r?.score)){totals.get(ps[i].id).influence+=r.score;totals.get(ps[j].id).dependence+=r.score}}
  const rows=[...totals.entries()];if(!rows.length)return totals;const mi=rows.reduce((a,[,v])=>a+v.influence,0)/rows.length,md=rows.reduce((a,[,v])=>a+v.dependence,0)/rows.length;for(const [,v] of rows){const hi=v.influence>=mi,hd=v.dependence>=md;v.zone=hi&&hd?'crítico':hi&&!hd?'activo':!hi&&hd?'pasivo':'indiferente'}return totals}
function vesterHint(node){const v=vesterSummary().get(node.id);if(!v)return '';return `<div class="tree-vester-hint"><strong>Vester:</strong> influencia ${v.influence}, dependencia ${v.dependence} · ${esc(v.zone)}. Es una orientación para revisar, no una clasificación causal.</div>`}
function shell(){return `<section id="treeWizard" class="tree-wizard"><div class="tree-top"><div><span class="tree-mode">Árbol paso a paso</span><h3>Organizar problema central, causas y efectos</h3><p>El árbol ayuda a ordenar relaciones plausibles. No demuestra causalidad científica y ninguna ubicación se confirma sin tu decisión.</p></div><div id="treeProgress" class="tree-progress"></div></div><div class="tree-actions"><button type="button" data-tree-help="easy">Explícame fácil</button><button type="button" data-tree-help="central">Ayúdame a elegir el problema central</button><button type="button" data-tree-phase="direct_cause">Revisar causas</button><button type="button" data-tree-phase="direct_effect">Revisar efectos</button><button type="button" data-tree-help="where">¿Dónde ubicar este elemento?</button><button type="button" data-tree-phase="review">Revisar coherencia</button><button type="button" data-tree-phase="full">Ver árbol completo</button></div><div id="treeAssist" class="tree-assist hidden"></div><div id="treeChangeWarning"></div><div id="treeBody"></div></section>`}
function assist(text){const b=$('#treeAssist');if(!b)return;b.classList.remove('hidden');b.innerHTML=`<strong>Ayuda para razonar</strong><p>${esc(text)}</p><small>Sugerencia metodológica. No cambia la ubicación de ningún elemento ni añade evidencia.</small>`;b.scrollIntoView({behavior:'smooth',block:'center'})}
function progress(){const zones=state.nodes.filter(n=>n.zone!=='outside').length;$('#treeProgress').textContent=centralNode()?`${zones} elementos ubicados · problema central definido`:`${zones} elementos ubicados · falta problema central`}
function changeWarning(){const box=$('#treeChangeWarning');if(!box)return;if(!currentS05Changed()){box.innerHTML='';return}box.innerHTML=`<div class="tree-warning"><strong>S05 cambió después de iniciar el árbol.</strong><p>Existen elementos o relaciones asociados a la versión anterior. Los cambios no se aplican automáticamente para evitar perder decisiones.</p><button type="button" id="treeReviewS05">Revisar y actualizar candidatos</button><button type="button" id="treeKeepS05">Mantener árbol actual</button></div>`;$('#treeReviewS05').onclick=()=>{if(confirm('Actualizará los candidatos desde S05. Los elementos ya ubicados se conservarán; los eliminados en S05 quedarán marcados para revisión. ¿Continuar?')){importFromS05(true);renderBody()}};$('#treeKeepS05').onclick=()=>{state.sourceSignature=s05Signature();saveState();renderBody()}}
function introView(){return `<div class="tree-intro"><strong>¿Qué vas a hacer?</strong><p>Ahora vamos a organizar los problemas según la relación que parecen tener entre sí. Buscaremos un problema central, posibles causas que contribuyen a que ocurra y efectos que pueden aparecer como consecuencia.</p><p>Los problemas provienen de S05. Los resultados de Vester pueden darte pistas para revisar algunos elementos, pero no deciden por ti qué es causa, efecto o problema central.</p><button type="button" id="treeStart" class="primary">Comenzar por el problema central</button></div>`}
function centralView(){const c=centralNode();return `<div class="tree-step"><div class="step-kicker">Paso 1 · problema central</div><p>Elige una situación negativa observable y suficientemente específica. Evita redactarla como ausencia de un proyecto, objetivo en negativo o solución faltante.</p>${state.nodes.map(n=>`<article class="tree-candidate ${n.zone==='central'?'chosen':''}"><div><strong>${esc(n.text)}</strong>${n.stale?'<span class="tree-stale">Cambió o desapareció en S05</span>':''}</div>${vesterHint(n)}<button type="button" data-central="${n.id}" class="${n.zone==='central'?'primary':''}">${n.zone==='central'?'Problema central elegido':'Elegir como problema central'}</button></article>`).join('')}<div class="tree-custom"><label>O redacta un problema central propio<textarea id="customCentral" placeholder="Describe una situación negativa observable, concreta y delimitada.">${c?.origin==='manual'?esc(c.text):''}</textarea></label><button type="button" id="saveCustomCentral">Usar esta redacción</button></div><button type="button" data-next-phase="direct_cause" class="primary" ${c?'':'disabled'}>Continuar a causas directas →</button></div>`}
function relationQuestion(zone){return {direct_cause:'¿Este problema contribuye de manera próxima a que ocurra el problema central?',indirect_cause:'¿Este elemento contribuye a una causa directa y puedes explicar ese vínculo?',direct_effect:'¿Este problema aparece como consecuencia próxima del problema central?',indirect_effect:'¿Este elemento aparece después o a partir de un efecto directo?' }[zone]}
function phaseIntro(zone){return {direct_cause:'Paso 2 · causas directas',indirect_cause:'Paso 3 · causas indirectas',direct_effect:'Paso 4 · efectos directos',indirect_effect:'Paso 5 · efectos indirectos'}[zone]}
function phaseView(zone){const c=centralNode();const eligible=state.nodes.filter(n=>n.id!==c?.id);const parents=zone==='indirect_cause'?nodesIn('direct_cause'):zone==='indirect_effect'?nodesIn('direct_effect'):[];return `<div class="tree-step"><div class="step-kicker">${phaseIntro(zone)}</div><p>${relationQuestion(zone)}</p>${eligible.map(n=>nodeEditor(n,zone,parents)).join('')}<div class="step-nav"><button type="button" data-prev-tree="${zone==='direct_cause'?'central':zone==='indirect_cause'?'direct_cause':zone==='direct_effect'?'indirect_cause':'direct_effect'}">← Anterior</button><button type="button" data-next-phase="${zone==='direct_cause'?'indirect_cause':zone==='indirect_cause'?'direct_effect':zone==='direct_effect'?'indirect_effect':'review'}" class="primary">${zone==='indirect_effect'?'Revisar coherencia':'Continuar →'}</button></div></div>`}
function nodeEditor(n,focusZone,parents){const inFocus=n.zone===focusZone;return `<article class="tree-node-editor ${inFocus?'in-zone':''}" data-node-card="${n.id}"><div class="tree-node-head"><strong>${esc(n.text)}</strong><span>${LABELS[n.zone]}</span></div>${vesterHint(n)}<label>Ubicación<select data-zone-select="${n.id}">${ZONES.filter(z=>z!=='central').map(z=>`<option value="${z}" ${n.zone===z?'selected':''}>${LABELS[z]}</option>`).join('')}</select></label>${(n.zone==='indirect_cause'||n.zone==='indirect_effect')?parentSelect(n,parents):''}<label>Justificación de la relación <span>· opcional</span><textarea data-justification="${n.id}" placeholder="Explica brevemente cómo se conecta este elemento con el nivel anterior.">${esc(n.justification||'')}</textarea></label><div class="tree-node-actions"><button type="button" data-review-node="${n.id}">Revisar esta relación</button><button type="button" data-mark-reviewed="${n.id}">${n.reviewed?'Revisado ✓':'Marcar revisado'}</button></div></article>`}
function parentSelect(n,parents){return `<label>Se conecta principalmente con<select data-parent="${n.id}"><option value="">[POR VERIFICAR]</option>${parents.map(p=>`<option value="${p.id}" ${n.parentId===p.id?'selected':''}>${esc(p.text)}</option>`).join('')}</select></label>`}
function fullTreeView(){const order=['indirect_cause','direct_cause','central','direct_effect','indirect_effect'];return `<div class="tree-full"><div class="tree-legend"><strong>Árbol completo</strong><p>Puedes cambiar la ubicación desde cada tarjeta. Ningún movimiento se realiza automáticamente.</p></div>${order.map(z=>`<section class="tree-zone ${z}"><h4>${LABELS[z]}</h4>${nodesIn(z).length?nodesIn(z).map(n=>`<article class="tree-visual-node"><strong>${esc(n.text)}</strong>${n.justification?`<p>${esc(n.justification)}</p>`:''}<select data-zone-select="${n.id}">${ZONES.map(k=>`<option value="${k}" ${n.zone===k?'selected':''}>${LABELS[k]}</option>`).join('')}</select></article>`).join(''):'<p class="tree-empty">Sin elementos ubicados aquí.</p>'}</section>`).join('')}<section class="tree-zone outside"><h4>Fuera del árbol</h4>${nodesIn('outside').map(n=>`<article class="tree-visual-node"><strong>${esc(n.text)}</strong><select data-zone-select="${n.id}">${ZONES.map(k=>`<option value="${k}" ${n.zone===k?'selected':''}>${LABELS[k]}</option>`).join('')}</select></article>`).join('')||'<p class="tree-empty">Ningún elemento fuera del árbol.</p>'}</section><button type="button" data-tree-phase="review" class="primary">Revisar coherencia</button></div>`}
function reviewIssues(){const issues=[];const c=centralNode();if(!c)issues.push('Aún no se ha confirmado un problema central.');if(state.nodes.filter(n=>n.zone==='central').length>1)issues.push('Hay más de un problema central; el árbol requiere una decisión explícita sobre cuál ocupará ese lugar.');
  const texts=new Map();state.nodes.filter(n=>n.zone!=='outside').forEach(n=>{const k=n.text.trim().toLowerCase();texts.set(k,(texts.get(k)||0)+1)});for(const [t,count] of texts)if(count>1)issues.push(`Hay una formulación duplicada: “${t}”.`);
  for(const n of state.nodes.filter(n=>n.zone!=='outside')){if(/^(falta|ausencia|carencia) de (un |una |el |la )?(proyecto|programa|taller|estrategia|capacitación|campaña|plataforma|solución)/i.test(n.text))issues.push(`“${n.text}” parece formulado como ausencia de una solución. Revisa si puede expresarse como condición observable.`);if(n.text.length>220)issues.push(`“${n.text.slice(0,70)}…” es muy amplio; considera separar componentes.`);if((n.zone==='indirect_cause'||n.zone==='indirect_effect')&&!n.parentId)issues.push(`“${n.text}” está en un nivel indirecto pero su conexión con el nivel anterior está [POR VERIFICAR].`);if(n.justification&&/siempre|demuestra|comprobado|sin duda|definitivamente/i.test(n.justification))issues.push(`La justificación de “${n.text}” usa lenguaje demasiado concluyente para una relación metodológica.`)}
  if(nodesIn('indirect_cause').length&& !nodesIn('direct_cause').length)issues.push('Hay causas indirectas sin causas directas que permitan construir la cadena.');if(nodesIn('indirect_effect').length&&!nodesIn('direct_effect').length)issues.push('Hay efectos indirectos sin efectos directos que permitan construir la cadena.');return issues}
function reviewView(){const issues=reviewIssues();return `<div class="tree-review"><strong>Revisión final del árbol</strong><p>Estas son observaciones para revisar. No constituyen una calificación ni cambian automáticamente tu estructura.</p>${issues.length?`<ul>${issues.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:'<div class="tree-ok">Las reglas estructurales básicas no detectan inconsistencias evidentes. La plausibilidad causal y la suficiencia de la evidencia siguen requiriendo revisión humana.</div>'}<div class="tree-checks"><p><b>Comprueba además:</b> coherencia vertical, duplicaciones, relaciones débiles, formulaciones ambiguas, elementos sin conexión, posibles soluciones disfrazadas de problemas y afirmaciones que requieren verificación.</p></div><div class="tree-objectives"><strong>Conexión posterior con objetivos</strong><p>Problema central → objetivo general; causas → medios u objetivos específicos; efectos → fines o resultados esperados. Esta transformación deberá revisarse y no introducirá soluciones nuevas automáticamente.</p></div><button type="button" data-tree-phase="full">Ver árbol completo</button><button type="button" data-tree-phase="central">Volver a revisar desde el problema central</button></div>`}
function renderBody(){progress();changeWarning();const body=$('#treeBody');if(!body)return;body.innerHTML=state.phase==='intro'?introView():state.phase==='central'?centralView():['direct_cause','indirect_cause','direct_effect','indirect_effect'].includes(state.phase)?phaseView(state.phase):state.phase==='full'?fullTreeView():reviewView();bindBody()}
function setCentral(id){state.nodes.forEach(n=>{if(n.zone==='central')n.zone='outside'});const n=state.nodes.find(x=>x.id===id);if(n){n.zone='central';n.parentId=null;n.reviewed=true}saveState();renderBody()}
function moveNode(id,zone){const n=state.nodes.find(x=>x.id===id);if(!n)return;if(zone==='central'){setCentral(id);return}n.zone=zone;if(!['indirect_cause','indirect_effect'].includes(zone))n.parentId=null;n.reviewed=false;saveState();renderBody()}
function reviewNode(id){const n=state.nodes.find(x=>x.id===id);if(!n)return;const notes=[],c=centralNode(),centralText=c?.text||'[POR VERIFICAR]';if(n.zone==='direct_cause')notes.push('Estamos revisando si “'+n.text+'” contribuye de manera próxima a que ocurra “'+centralText+'”.');if(n.zone==='direct_effect')notes.push('Estamos revisando si “'+n.text+'” aparece como consecuencia próxima de “'+centralText+'”.');if(n.zone==='indirect_cause'){const p=state.nodes.find(x=>x.id===n.parentId);notes.push('Estamos revisando si “'+n.text+'” contribuye primero a “'+(p?.text||'[POR VERIFICAR]')+'” antes de llegar a “'+centralText+'”.')}if(n.zone==='indirect_effect'){const p=state.nodes.find(x=>x.id===n.parentId);notes.push('Estamos revisando si “'+n.text+'” aparece después de “'+(p?.text||'[POR VERIFICAR]')+'”, que a su vez se relaciona con “'+centralText+'”.')}if(/^(falta|ausencia|carencia) de (un |una |el |la )?(proyecto|programa|taller|estrategia|capacitación|campaña|plataforma|solución)/i.test(n.text))notes.push('La formulación “'+n.text+'” puede estar describiendo una solución ausente. Conviene reformular la condición observable que existe realmente en el proyecto.');if(!n.justification?.trim())notes.push('La justificación es opcional. Si esta relación concreta todavía no es clara, conserva [POR VERIFICAR] en lugar de inventar una explicación.');else if(/al mismo tiempo|coincid|simult|se relacionan|están relacionados/i.test(n.justification))notes.push('La justificación registrada para “'+n.text+'” parece describir asociación o simultaneidad. Revisa si explica realmente una influencia o consecuencia.');if(!notes.length)notes.push('La formulación “'+n.text+'” y su justificación son suficientemente concretas para continuar la revisión.');assist(notes.join(' '))}
function bindBody(){
  $('#treeStart')&&($('#treeStart').onclick=()=>{state.phase='central';saveState();renderBody()});document.querySelectorAll('[data-central]').forEach(b=>b.onclick=()=>setCentral(b.dataset.central));
  $('#saveCustomCentral')&&($('#saveCustomCentral').onclick=()=>{const t=$('#customCentral').value.trim();if(!t){assist('Escribe una situación negativa observable antes de usarla como problema central.');return}state.nodes.forEach(n=>{if(n.zone==='central')n.zone='outside'});let n=state.nodes.find(n=>n.origin==='manual'&&n.zone==='outside');if(!n){n={id:'manual-'+Date.now(),text:t,zone:'central',justification:'',parentId:null,reviewed:true,origin:'manual'};state.nodes.push(n)}else{n.text=t;n.zone='central';n.reviewed=true}saveState();renderBody()});
  document.querySelectorAll('[data-next-phase]').forEach(b=>b.onclick=()=>{state.phase=b.dataset.nextPhase;saveState();renderBody()});document.querySelectorAll('[data-prev-tree]').forEach(b=>b.onclick=()=>{state.phase=b.dataset.prevTree;saveState();renderBody()});
  document.querySelectorAll('[data-zone-select]').forEach(s=>s.onchange=()=>moveNode(s.dataset.zoneSelect,s.value));document.querySelectorAll('[data-parent]').forEach(s=>s.onchange=()=>{const n=state.nodes.find(x=>x.id===s.dataset.parent);if(n){n.parentId=s.value||null;n.reviewed=false;saveState()}});document.querySelectorAll('[data-justification]').forEach(t=>t.onblur=()=>{const n=state.nodes.find(x=>x.id===t.dataset.justification);if(n){n.justification=t.value.trim();saveState()}});document.querySelectorAll('[data-review-node]').forEach(b=>b.onclick=()=>reviewNode(b.dataset.reviewNode));document.querySelectorAll('[data-mark-reviewed]').forEach(b=>b.onclick=()=>{const n=state.nodes.find(x=>x.id===b.dataset.markReviewed);if(n){n.reviewed=!n.reviewed;saveState();renderBody()}});document.querySelectorAll('[data-tree-phase]').forEach(b=>b.onclick=()=>{state.phase=b.dataset.treePhase;saveState();renderBody();const body=$('#treeBody');if((state.phase==='direct_cause'&&!nodesIn('direct_cause').length)||(state.phase==='direct_effect'&&!nodesIn('direct_effect').length))assist(state.phase==='direct_cause'?'Todavía no hay causas directas ubicadas. Usa el modo paso a paso para decidir qué situaciones ocurren antes del problema.':'Todavía no hay efectos directos ubicados. Usa el modo paso a paso para decidir qué situaciones aparecen después del problema.');else body?.scrollIntoView({behavior:'smooth',block:'start'})})
}
function bindTop(){document.querySelectorAll('[data-tree-help]').forEach(b=>b.onclick=()=>{const t=b.dataset.treeHelp;if(t==='easy')assist('Primero elige una situación central. Luego pregunta qué condiciones contribuyen a que ocurra y qué consecuencias aparecen después. Puedes dejar cualquier relación [POR VERIFICAR] hasta tener una explicación o evidencia suficiente.');if(t==='central')assist('Busca una situación negativa observable y concreta. Pregunta: ¿se puede observar?, ¿a quién afecta?, ¿dónde ocurre?, ¿hay evidencia?, ¿evita describir una solución faltante? Vester puede orientar qué revisar, pero no decide el problema central.');if(t==='where')assist('Para ubicar un elemento, pregunta en orden: ¿contribuye a que ocurra el problema central?, ¿aparece después como consecuencia?, ¿solo describe contexto?, ¿es un síntoma o una solución redactada como problema? Si la respuesta no es clara, déjalo fuera del árbol o [POR VERIFICAR].')})}
function warnOnS05Edit(){const counter=$('#counter');if(!counter?.textContent.startsWith('S05')){s05Warned=false;return}const field=document.querySelector('[data-field="situaciones_observables"]');if(!field||field.dataset.treeWarnBound)return;field.dataset.treeWarnBound='1';field.addEventListener('focus',()=>{const hasLinks=(typeof draft!=='undefined'&&((draft.S06?.vester_state?.selected?.length||0)>0||(draft.S07?.tree_state?.nodes?.length||0)>0));if(hasLinks&&!s05Warned){s05Warned=true;const ok=confirm('Este campo ya tiene problemas asociados a Vester o al árbol. Puedes editarlo, pero las relaciones existentes no se actualizarán automáticamente. Al volver a S06 o S07 se te pedirá revisar los cambios. ¿Continuar?');if(!ok)field.blur()}})}
function mount(){const counter=$('#counter'),fields=$('#fields'),panel=$('#panel');warnOnS05Edit();if(!counter||!fields||!counter.textContent.startsWith('S07')){panel?.classList.remove('tree-mode-active');mounted=false;return}if(mounted&&$('#treeWizard'))return;syncFromDraft();if(!state.nodes.length)importFromS05();panel.classList.add('tree-mode-active');fields.insertAdjacentHTML('beforeend',shell());mounted=true;bindTop();renderBody()}
new MutationObserver(()=>mount()).observe(document.body,{subtree:true,childList:true,characterData:true});mount();
})();