(()=>{
const TREE_KEY='formulador-cultural-problem-tree-v1';
const CV_KEY='formulador-cultural-causal-validation-v1';
const norm=v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ');
function hashText(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return 'p'+(h>>>0).toString(36)}
function rawS05Signature(){const raw=typeof draft!=='undefined'?draft?.S05?.situaciones_observables||'':'';const vals=[...new Map(String(raw).split(/\n+/).map(x=>x.trim().replace(/^([\-•*]|\d+[.)]|[A-Za-z][.)])\s*/, '')).filter(Boolean).map(t=>[t.toLowerCase(),t])).values()];return vals.map(text=>`${hashText(text)}:${text}`).join('|')}
function cvState(){try{return (typeof draft!=='undefined'&&draft?.S06?.causal_validation)||JSON.parse(localStorage.getItem(CV_KEY)||'{}')}catch{return {}}}
function treeState(){try{return (typeof draft!=='undefined'&&draft?.S07?.tree_state)||JSON.parse(localStorage.getItem(TREE_KEY)||'{}')}catch{return {}}}
function saveTree(s){s.updatedAt=new Date().toISOString();localStorage.setItem(TREE_KEY,JSON.stringify(s));if(typeof draft!=='undefined'){draft.S07=draft.S07||{};draft.S07.tree_state=s;try{localStorage.setItem(storeKey,JSON.stringify(draft))}catch{}}}
function sync(){const cv=cvState(),vars=(cv.variables||[]).filter(x=>x.status==='confirmed'&&String(x.text||'').trim());if(vars.length<2)return false;const s={nodes:[],phase:'intro',sourceSignature:'',reviewed:{},...treeState()},existing=s.nodes||[],byId=new Map(existing.map(n=>[n.id,n])),byText=new Map(existing.map(n=>[norm(n.text),n])),confirmedIds=new Set();const next=[];for(const v of vars){let n=byId.get(v.id)||byText.get(norm(v.sourceText))||byText.get(norm(v.text));if(n){n={...n,id:v.id,text:v.text,stale:false,origin:n.origin==='manual'?'manual':'S06_VALIDATION',causalRole:v.role||'unclassified',causalNote:v.note||''}}else n={id:v.id,text:v.text,zone:'outside',justification:'',parentId:null,reviewed:false,origin:'S06_VALIDATION',stale:false,causalRole:v.role||'unclassified',causalNote:v.note||''};confirmedIds.add(v.id);next.push(n)}for(const n of existing){if(confirmedIds.has(n.id)||n.origin==='manual')continue;if(n.origin==='S05'||n.origin==='S06_VALIDATION'){next.push({...n,zone:'outside',stale:true,reviewed:false})}else next.push(n)}s.nodes=next;s.sourceSignature=rawS05Signature();s.causalValidationSignature=cv.sourceSignature||'';saveTree(s);return true}
function decisionText(p){if(p.decision==='a_to_b')return `${p.aText} → ${p.bText}`;if(p.decision==='b_to_a')return `${p.bText} → ${p.aText}`;if(p.decision==='indirect')return `${p.aText} ↔ ${p.bText}: relación indirecta o mediada`;if(p.decision==='association')return `${p.aText} ↔ ${p.bText}: asociación sin causalidad suficiente`;if(p.decision==='none')return `${p.aText} ↔ ${p.bText}: descartada para el árbol`;return ''}
function mountSummary(){
 const wizard=document.querySelector('#treeWizard');if(!wizard||wizard.querySelector('#causalBridgeSummary'))return;
 const cv=cvState(),vars=(cv.variables||[]).filter(x=>x.status==='confirmed'&&String(x.text||'').trim()),pairs=(cv.pairs||[]).filter(x=>x.decision&&x.decision!=='pending');
 const box=document.createElement('div');box.id='causalBridgeSummary';box.className='tree-warning';
 const varsHtml=vars.length?'<ul class="causal-bridge-vars">'+vars.map(v=>'<li><strong>'+v.text+'</strong>'+(v.role&&v.role!=='unclassified'?'<span>'+({possible_cause:'Revisada como posible causa',possible_central:'Revisada como posible problema central',possible_effect:'Revisada como posible efecto',context:'Revisada como condición de contexto'}[v.role]||v.role)+'</span>':'')+'</li>').join('')+'</ul>':'<p><b>[POR VERIFICAR]</b> No hay variables confirmadas disponibles.</p>';
 const pairsHtml=pairs.length?'<details><summary>Ver '+pairs.length+' relaciones revisadas</summary><ul>'+pairs.map(p=>'<li>'+decisionText(p)+'</li>').join('')+'</ul></details>':'<p><b>[POR VERIFICAR]</b> No hay relaciones causales confirmadas entre pares.</p>';
 box.innerHTML='<strong>Datos que llegan desde S06</strong><p>Estas son las situaciones que confirmaste para construir el árbol:</p>'+varsHtml+pairsHtml;
 const top=wizard.querySelector('.tree-top');top?.insertAdjacentElement('afterend',box)
}
function enforce(){const counter=document.querySelector('#counter');if(!counter?.textContent.startsWith('S07'))return;const cv=cvState(),ready=(cv.variables||[]).filter(x=>x.status==='confirmed').length>=2;if(!ready){const fields=document.querySelector('#fields');if(fields&&!document.querySelector('#causalGate')){const gate=document.createElement('div');gate.id='causalGate';gate.className='tree-warning';gate.innerHTML='<strong>Falta la validación causal de S06.</strong><p>Antes de construir el árbol, completa Vester y confirma al menos dos variables en “Validación causal”.</p><button type="button" id="goCausalValidation">Volver a S06</button>';fields.prepend(gate);gate.querySelector('#goCausalValidation').onclick=()=>window.fcNavigate?window.fcNavigate('S06'):document.querySelector('#nav button[data-k="S06"]')?.click()}}else{document.querySelector('#causalGate')?.remove();sync();mountSummary()}}

const bridgeStyle=document.createElement('style');bridgeStyle.textContent='.causal-bridge-vars{display:grid;gap:8px;margin:10px 0;padding:0;list-style:none}.causal-bridge-vars li{display:grid;gap:3px;border:1px solid #d9e5de;background:#fff;border-radius:11px;padding:9px 10px}.causal-bridge-vars li span{color:#607067;font-size:.82rem}';document.head.appendChild(bridgeStyle);
window.fcSyncCausalValidationToTree=sync;
/* Do not derive/write a tree at boot or during passive navigation. */new MutationObserver(enforce).observe(document.body,{subtree:true,childList:true,characterData:true});enforce();
})();