from __future__ import annotations
from typing import Protocol
from uuid import UUID
from domain import Project

class ProjectRepository(Protocol):
    def create(self, project: Project) -> Project: ...
    def get(self, user_id: UUID, project_id: UUID) -> Project | None: ...
    def save(self, project: Project) -> Project: ...
    def list_for_user(self, user_id: UUID) -> list[Project]: ...

class AIProvider(Protocol):
    def assist(self, *, section: str, field: str, context: dict) -> dict: ...

class WebSearchProvider(Protocol):
    def search(self, query: str, limit: int = 5) -> list[dict]: ...

class RAGProvider(Protocol):
    def retrieve(self, query: str, user_id: UUID, project_id: UUID | None = None, limit: int = 5) -> list[dict]: ...

class AuthProvider(Protocol):
    def resolve_user(self, token: str) -> UUID: ...
