from __future__ import annotations
from typing import Protocol
from .domain import VesterProblem, VesterRelation, VesterResults

class VesterAIPort(Protocol):
    def explain_relation(self, source: VesterProblem, target: VesterProblem) -> str: ...
    def review_justification(self, relation: VesterRelation, source: VesterProblem, target: VesterProblem) -> str: ...
    def interpret_results(self, results: VesterResults, problems: list[VesterProblem]) -> str: ...
